### ISSUE TITLE
Android: How can I send a Post request of an array of objects?

### ISSUE THREAD

**Issue by KalebPortillo** [kittinunf/Fuel#101]
I writing a app in Android Java, can someone give a example of how to post an array of objects, like: 
```
[
    {
       key: value,
       key: value
    },
    {
       key: value,
       key: value
    },
    {
       key: value,
       key: value
    }
]
```

**Comment by yoavst** [comment]
using a json lib that converts the array of objects to json?

**Comment by KalebPortillo** [comment]
But the post mothod just accept ai ArryList of Pair<>  as parameter

**Comment by kittinunf** [comment]
Can you use `.body()` to help you achieve what you want? 

``` Kotlin
val bodyStr = ....
Fuel.post("<>").body(bodyStr).responseString()
```

https://github.com/kittinunf/Fuel/blob/676f84cf43b25a65c5577f63c4e7cbaff1473147/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt#L100

**Comment by KalebPortillo** [comment]
Thanks
