### ISSUE TITLE
Way to retrieve redirection info

### ISSUE THREAD

**Issue by uranusjr** [kittinunf/Fuel#104]
I understand that auto redirection is implemented in #40, but how can I disable this? My use case is that I want to decide whether or not to redirect based on the Location header, but with auto-redirection I can only see the final response.

An alternative would be that I can in some way check where I have beed redirected to. But this also seems impossible—It seems to me URLs of both request and response in the callback are set to the original URL I requested from, not the final one that actually returns the non-redirection status.

**Comment by yoavst** [comment]
Not possible yet. 
Do you want to be able to disable the redirection feature? or just in specific cases?

**Comment by uranusjr** [comment]
I’d say just in specific cases. It doesn’t need to (shouldn’t) be the default, but there should be a way to change the behaviour. It could work as an optional parameter like this: (taking the idea from [Django’s test client API](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.Client.get).)

~~~kotlin
Fuel.get(url)    // Follows redirects (behaviour unchanged).
Fuel.get(url, follow = true)     // Explicitly follow redirects.
Fuel.get(url, follow = false)    // Does not follow redirects.
~~~

**Comment by yoavst** [comment]
Should be easy to implement, since we just need to move the location of the redirection interceptor to the request and not global.

**Comment by kittinunf** [comment]
@uranusjr In the meantime, you could remove all responseRedirection and add yours own to do whatever you want to.

Example is here;
https://github.com/kittinunf/Fuel/blob/master/fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt#L207

**Comment by kittinunf** [comment]
Close due to inactivity

**Comment by njasm** [comment]
I'm having the same problem that @uranusjr have, i need the headers to decide if i want to auto redirect or not, in fact my calling code should decide that. 

Removing all response interceptors doesn't really 'feels' right to me.. with the current FuelManager API, i feel that i might be removing more that a need/should.

**Comment by kenrube** [comment]
Agree with @uranusjr and @njasm, it's missing feature. Let's say alone way to get auth from my server is to get cookie header from first response in chain. But with auto redirection I can't do this without `removeAllResponseInterceptors()` which seems to be overhead in this case.

**Comment by knyttl** [comment]
Just for clarity, this is solved with `.allowRedirects(false)`
