### ISSUE TITLE
Specify Cookies through Fuel instead of using java.net.CookieManager

### ISSUE THREAD

**Issue by Maldaris** [kittinunf/Fuel#105]
Android uses a separate cookie manager for WebViews,  android.webview.CookieManager, which requires type coercion to properly load into the standard java.net.CookieManager, which is used by Fuel via HttpURLConnection. 

Would it be possible to have a Fuel standard interface for loading/retrieving/managing Cookies?

**Comment by erdoganbavas** [comment]
You can set cookie with "header" method right after your "get/post/.." request. And you can find cookies  in response's header data with "Set-Cookie" key.

**Comment by yoavst** [comment]
Code I use to find a specific cookie: https://gitlab.com/yoav-sternberg/mashov-api/blob/master/src/main/kotlin/com/yoavst/mashov/controller/CookieManagerImpl.kt

```kotlin
        headers["Set-Cookie"]?.flatMap { HttpCookie.parse(it) }?.find { it.name == "MashovSessionID" }?.let {
            mashovSessionId = it.value
        }
```

**Comment by Maldaris** [comment]
This isn't overwritten by CookieManager when using HttpUrlConnection?
