### ISSUE TITLE
Progress not updating

### ISSUE THREAD

**Issue by silverboyir** [kittinunf/Fuel#106]
Hi
i want update progress of ProgressDialog in progress method in download
but progress not updating on view , im seeing the percent in logcat 

progress=new ProgressDialog(activity);
            progress.setMessage(activity.getResources().getString(R.string.download_video));
            progress.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);
            progress.setIndeterminate(true);
            progress.setProgress(0);
            progress.setMax(100);
            progress.setIndeterminate(false);
            progress.show();

and in progress

int currentProgress = (int)(readBytes \* 100.0 / totalBytes + 0.5);
                    Log.d(BadansazApplication.TAG, "download Pogress :"+String.valueOf(currentProgress));
                    progress.setProgress(currentProgress);

**Comment by kittinunf** [comment]
Have you tried wrapped with `runOnUiThread`? View cannot update outside UI thread.

**Comment by kittinunf** [comment]
This issue seems to be staled. Please re-open it if the issue persists.
