### ISSUE TITLE
Possibility to invoke handler in background thread on Android

### ISSUE THREAD

**Issue by heyarne** [kittinunf/Fuel#109]
Is this possible? I am handling a very large JSON response and I offloaded parsing it to the background thread already, but I guess the String alone already makes the UI stutter a bit.

**Comment by kittinunf** [comment]
You could do one of the following.

1. If making a String really does slow you down, you could opt to use `fun response(handler: (Request, Response, Result<ByteArray, FuelError>) -> Unit)`. Then, wrapping the parsing `ByteArray` by using Gson, Mochi, and whatnots on the background thread.

2. You could use built-in deserialization support, i.e. `fun <T> responseObject(deserializer: ResponseDeserializable<T>, handler: (Request, Response, Result<T, FuelError>) -> Unit)`. I did call `deserialize` method in background thread so you could take adv that right off the bat.

Let me know if one of the two could help solve your problem.

**Comment by heyarne** [comment]
Thanks, solution number two worked like a charm. :)
