### ISSUE TITLE
httpGet() and httpPost() differ in request encoding?

### ISSUE THREAD

**Issue by sitexa** [kittinunf/Fuel#111]
What's the reason?  No1 use httpGet, No2 use httpPost, the same parameter "科特林"，different out put , the last is correct.

No1===
Client side:
val url = "http://localhost:1234/member"
val p1 = Pair("name","科特林")
val list = listOf(p1)
val (request, response, result) = url.httpGet(list).responseString()

Server side:
No1, "GET" request parameter:
val name = request.queryParams["name"]
log.info("name:" + name)  //out put : name:%E7%A7%91%E7%89%B9%E6%9E%97

No2===
Client side:
val url = "http://localhost:1234/member"
val p1 = Pair("name","科特林")
val list = listOf(p1)
val (request, response, result) = url.httpPost(list).responseString()

Server side:
val name = request.bodyParams["name"] as String 
log.info("name:"+name)    //out put : name:科特林

**Comment by kittinunf** [comment]
I believe both of them using the same encoding. Feel free to reopen the issue if you find that the problem still occurs.
