### ISSUE TITLE
Useless try-catch block

### ISSUE THREAD

**Issue by dstd** [kittinunf/Fuel#112]
There's no reason for the following try-catch block in [HttpClient.kt](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L65), because there's the outer try-catch block that will catch any exception

```
                //try - catch just in case both methods throw
                try {
                    httpStatusCode = connection.responseCode
                    httpResponseMessage = connection.responseMessage
                } catch(exception: IOException) {
                    throw exception
                }
```

**Comment by kittinunf** [comment]
Thanks!

**Comment by kittinunf** [comment]
Removed!
