### ISSUE TITLE
JRE 7 required to use Basic Authentication

### ISSUE THREAD

**Issue by nyfd** [kittinunf/Fuel#116]
https://github.com/kittinunf/Fuel/releases/tag/1.3.1

Using Basic Authentication on Oracle JRE 6 (Debian) fails with an exception.

Apparently Basic Authentication uses Base64 encoding classes which are are compiled with target compatibility JVM 7.

See com.github.kittinunf.fuel.util.Base64.class

**Comment by yoavst** [comment]
In a library of mine I use:
```
sourceCompatibility = 1.6
targetCompatibility = 1.6
```

But I don't know if it really works.

**Comment by nyfd** [comment]
It should work, and it's easy to rebuild from sources with JRE compatibility set to 1.6

The problem is that the published JAR (https://github.com/kittinunf/Fuel/releases/tag/1.3.1) already contains those Base64-classes that require JRE 7 to run, and we prefer to use published artefacts from JCenter repository instead of building from sources.

**Comment by nyfd** [comment]
Hmm, I'd like to understand how this could happen - I guess that the release was built on a system with JDK 7 installed as default Java.

Kotlin compiler produces class files targeted for JVM 6 automatically. 

Base64.java seems to be the only class written in pure Java so JDK 7 built it with target compatibility 7. 

You need to provide bootstrap path with JRE 6 runtime JARs when building for JRE 6 on a JDK 7/8/9 machine, which is not a big problem.
Probably it would be much easier to build the next release with JDK 6, if it's possible.

**Comment by kittinunf** [comment]
I will do that for the next release.

**Comment by kittinunf** [comment]
It is addressed by #123

**Comment by kittinunf** [comment]
This should be fixed with latest version. 1.4.0
