### ISSUE TITLE
help for keeping session open

### ISSUE THREAD

**Issue by HosseinR65** [kittinunf/Fuel#121]
Hi 
i started working on an existing project that currently using DefaultHttpClient of apache
this project will just create DefaultHttpClient  one time and keep it in a static variable , so the session will kept open for a while 
how i can achieve this functionality with fuel to replace this section ?

seems i can keep the request object in static variable , and with header method i can change parameter , but how i can at first remove all parameters ? also seems i cant reset request url, means setUrl and setPath not work as expected and i in succsess method i get the first request url (also im not sure keeping request object as static variable can help or not at all)

Thanks

**Comment by yoavst** [comment]
Fuel doesn't support `keep-open` requests.
