### ISSUE TITLE
(Java) Passing body / header in an upload task

### ISSUE THREAD

**Issue by SebastienFCT** [kittinunf/Fuel#122]
Hey there,

I'm trying to perform an upload task passing both body and header.

I searched everywhere in your doc, but can't find out how to manage this.

This is what I'm doing so far for the headers: 

    HashMap<String, String> headers = new HashMap<>();
    headers.put("header-field", "header-value");
    Fuel.upload(Utilities.UPLOAD_BINARY_URL, Method.POST)
                        .set
                        .header(headers)
                        .source(new Function2<Request, URL, File>() {
                            @Override
                            public File invoke(Request request, URL url) {
                                return signatureFile;
                            }
                        })
                        .responseString(new Handler<String>() {
                            @Override
                            public void success(@NotNull Request request, @NotNull Response response, String s) {
                                
                            }
                            @Override
                            public void failure(@NotNull Request request, @NotNull Response response, @NotNull FuelError fuelError) {
                                Log.e("upload", response.toString());
                            }
                        });

Concerning the body (most important in my case), I've been trying to use the `.body` without success.

Thanks in advance

**Comment by kittinunf** [comment]
Close as implemented in #129
