### ISSUE TITLE
Cant find responseJson

### ISSUE THREAD

**Issue by wahoho** [kittinunf/Fuel#124]
I am using the latest 1.3.1 but I can't seem to find responseJson. I can see response, responseString, and responseObject. Is the responseJson already removed from verion 1.3.1?

**Comment by yoavst** [comment]
it is moved to `fuel-android`

**Comment by wahoho** [comment]
Oh Ok I thought it was still in fuel 1.3.1 since responseJson was still in the README. Thank you for the info.

**Comment by jivimberg** [comment]
Any reason why it was moved to `fuel-android` instead of being part of `fuel` core?

**Comment by yoavst** [comment]
Fuel is now fully Java compatible and used in some of my pure jvm projects
