### ISSUE TITLE
Add exception catcher in httpGet for Android?

### ISSUE THREAD

**Issue by edwinevans** [kittinunf/Fuel#128]
If an exception occurs in the code for processing httpGet response nothing gets logged to logcat. I think if an exception escapes from the thread processing the response then fuel should log it.

**Comment by kittinunf** [comment]
I think you should be able to retrieve it from `Result`. Can you see whether you get what you want inside it?

**Comment by edwinevans** [comment]
I mean if there is an exception in the client code that handles the callback...

       url.httpGet().responseString { request, response, result ->
            // EXCEPTION HERE has no default handler

**Comment by edwinevans** [comment]
I'm not seeing this issue with my latest environment. I think it's getting caught by an android default thread exception handler and logging fine. I'm not sure what was going on. Closing issue.

**Comment by kittinunf** [comment]
Oh okay. Thanks for reporting this (and close this). 👍
