### ISSUE TITLE
how to post a json as body

### ISSUE THREAD

**Issue by qgliu** [kittinunf/Fuel#132]
What I'm trying to do is very simple, I need to add a JSON structured string in post.

For example, in posting to "users/login", the body should be {email: aaa, password: bbb}. I use kotson gson to construct the JSON
`                    val dataJson: JsonObject = jsonObject(
                            "email" to "$email",
                            "password" to "$password"
                    )`
`val data = dataJson.toString()`
`"/users/login".httpPost().body(data).response { request, response, result ->`

Up to dataJson.toString(), things look good
`{"email":"aaa","password":"bbb"}`
However, on the server side, the posted data is in a strange format with extra parentheses and colon.
`{ '{"email":"aaa","password":"bbb"}': '' }`

I am fairly new to android development, could someone show me where is the mistake?

Thanks.

**Comment by qgliu** [comment]
Even use the example code in README
`"{ \"foo\" : \"bar\" }"`
The server is getting `{ '{ "foo" : "bar" }': '' }`

**Comment by tumasgiu** [comment]
Try setting the content type header :

```
val request = "/users/login".httpPost().body(data)
request.httpHeaders["Content-Type"] = "application/json"
request.response { request, response, result -> ...
```

**Comment by qgliu** [comment]
Thanks.
