### ISSUE TITLE
Missing PATCH-Verb

### ISSUE THREAD

**Issue by heyarne** [kittinunf/Fuel#133]
Is there a possibility to issue PATCH-requests without using the semi-standard `X-HTTP-Method-Override` header, e.g. `Fuel.patch(...)`?

Maybe I'm just not seeing it, there is a patch method defined [here](https://github.com/kittinunf/Fuel/blob/5ce5955b34a2f237ed3b3c223415da74619ad4ab/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Method.kt#L8) but it's not exposed like GET, POST, PUT or DELETE. Is there a reason for this?

**Comment by andreparodi** [comment]
I was looking for this as well. Although the enum is defined it looks like the appropriate methods in the Fuel class are not defined to do the patch request. see [here](https://github.com/kittinunf/Fuel/blob/513cbb78115ace90524333a732d990be32ae1dae/fuel/src/main/kotlin/com/github/kittinunf/fuel/Fuel.kt#L124)

it looks like it should be pretty easy to add. 

how did you do the request with the X-HTTP-Method-Override?

**Comment by kittinunf** [comment]
I will cover this issue by #156

**Comment by henryfjordan** [comment]
This was such a dark pattern. It led to me spending a few hours banging my head against a mystery 405 response code until I logged into our API gateway and started tracing requests.

💩

**Comment by SleeplessByte** [comment]
Is it currently not correctly documented?
