### ISSUE TITLE
RxJava extension: favor Observable.defer + ReplaySubject over Observable.create 

### ISSUE THREAD

**Issue by VictorAlbertos** [kittinunf/Fuel#137]
Hi @kittinunf :)

Creating an `Observable` using its static built-in `create` method could lead to unexpected results, and because of that its usage is generally disallowed. 

> This method requires advanced knowledge about building operators and data sources; please consider other standard methods first

Extracted from the official docs. 

That's why I would recommend to change the current implementation to use `defer` and `ReplaySubject`:

```kotlin
private fun <T : Any> Request.rx_response(deserializable: Deserializable<T>): Observable<Pair<Response, T>> =
        Observable.defer {
            val source = ReplaySubject.create<Pair<Response, T>>()
            response(deserializable) { request, response, result ->
                when (result) {
                    is Result.Success -> {
                        source.onNext(response to result.value)
                        source.onCompleted()
                    }

                    is Result.Failure -> {
                        source.onError(result.error)
                    }
                }
            }
            source.doOnSubscribe { this.cancel() }
        }
```

If you agree with this proposal I could make a PR :)

**Comment by kittinunf** [comment]
I agree that using `create` should be discouraged but I don't see why do we need a `ReplaySubject` in here? Can you explain a bit more on that.

**Comment by VictorAlbertos** [comment]
In this entry on [StackOverflow](http://stackoverflow.com/questions/36765336/rxjava-observable-alternative-to-create-in-async-call) David Karnok suggets to use `AsyncSubject` as an alternative to `Obseravble.create`.

Its main difference regarding `ReplaySubject` is the next one:

AsyncSubject
> It will emit this same final value to any subsequent observers. 

ReplaySubject
> It emits to any observer all of the items that were emitted by the source Observable(s).

Extracted from the [`Subject`official docs](http://reactivex.io/documentation/subject.html)

On the contrary, `BehaviorSubject` and `PublishSubject` would not signal if the subscription takes place after the emission. So, for instance, the suite won't be able to pass its tests -I've already checked it :).

So, in my opinion, `AsyncSubject` is the best alternative to replace `Obseravble.create`; because, due to the nature of Fuel lib, only one element is expected to be signal by each `Observable` instantiation.

The final implementation would be as follow (pretty much the same as the previous one):

```kotlin
Observable.defer {
    val source = AsyncSubject.create<Pair<Response, T>>()
    response(deserializable) { request, response, result ->
        when (result) {
            is Result.Success -> {
                source.onNext(response to result.value)
                source.onCompleted()
            }

            is Result.Failure -> {
                source.onError(result.error)
            }
        }
    }
    source.doOnSubscribe { this.cancel() }
}
```

**Comment by kittinunf** [comment]
Sure! I think using `AsyncSubject` made much more sense. Thank you for suggesting this by the way. If you would scarifice your time a little to help me out, that would be awesome too!!

**Comment by VictorAlbertos** [comment]
Of course :) Already done at #138

**Comment by kittinunf** [comment]
This should be closed then! Thanks @VictorAlbertos so much for helping me out ❤️
