### ISSUE TITLE
Missing code for com.github.kittinunf.result.Result

### ISSUE THREAD

**Issue by paksv** [kittinunf/Fuel#141]
Not sure what's happened, but library is unusable now.

**Comment by paksv** [comment]
Apparently, RTFM required.

**Comment by kittinunf** [comment]
Oh can you please share what actually happened? So that I could add into the installation process. Thanks!

**Comment by paksv** [comment]
I was very straightforward - just downloaded the 1.5.0 release and used it in my app. Didn't read the README.md as usual :).
It would be nice to have the complete package (with deps) in release. That would save time for people like me.
Other than that worked great for my needs. Thank you for that library.

**Comment by kittinunf** [comment]
Ah, sorry for my naive knowledge that everyone uses `gradle` these days ? Really sorry for that I will update README.md so that it should be able to understand a little better, what do you think?

**Comment by yoavst** [comment]
@kittinunf is right, most of the libraries nowadays works only with build system, so they no longer mention their dependencies on their README.

**Comment by paksv** [comment]
I always prefer downloading a release vs building against the latest sources for numerous reasons. It's quite clear in README that dependency is located in different repo. I just didn't expect that. Usually, release library contains all the dependencies.

**Comment by yoavst** [comment]
@paksv Would you be OK with adding `Result` jar in releases page?

**Comment by paksv** [comment]
@yoavst yes, that would be great. Thank you.

**Comment by yoavst** [comment]
Done.
