### ISSUE TITLE
Android block mode -> Cannon resolve responseString

### ISSUE THREAD

**Issue by Tchoupinax** [kittinunf/Fuel#143]
Hello, 

I have a problem with trying to use the blocking mode code.
```Java
try {
    Triple<Request, Response, String> data = Fuel.get("http://www.google.com").responseString();
    Request request = data.getFirst();
    Response response = data.getSecond();
    Result<String,FuelError> text = data.getThird();
} 
catch (Exception networkError) {
}
```

First of all, it seems to be good to replace _Triple<Request, Response, String>_ by _Triple<Request, Response,  **Result<String,FuelError>**>_ (Android studio helps me to find it. ^^)

However for this line :
```Java
Triple<Request, Response, String> data = Fuel.get("http://www.google.com").responseString();
```

responseString() triggers "cannot resolve methode responseString()". I tried to change the variable type, try many things but don't know why it does not work. response() works seemingly but i want my string ! :D

Anyone has the solution ? 
Thanks for your time.

**Comment by dyas90** [comment]
Same problem with me. 
i use this code
`val (request, response, result) = "http://httpbin.org/get".httpGet().responseString()`
get result `[Failure: Exception : null]`
but if i use code
`"http://httpbin.org/get".httpGet().responseJson {req, resp, res -> }`
get result `[Success: com.github.kittinunf.fuel.android.core.Json@4c0076a]`
what wrong?

**Comment by kittinunf** [comment]
Hi, thank you you both for reporting!

The full explanation of the exception is this (Sorry, I think the current version the exception string is not good enough, it doesn't provide useful information).

```
java.lang.AssertionError: 
Expected: null
     but: was <Exception : sun.security.validator.ValidatorException: PKIX path building failed: java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.>
Expected :null
     
Actual   :<Exception : sun.security.validator.ValidatorException: PKIX path building failed: java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.>
```

So, it looks like you need to do either;

1. Configure the SSLContext with a TrustManager that accepts any cert or
2. Configure the SSLContext with an appropriate trust store that includes your cert
3. Add the cert for that site to the default java trust store.

You should be able to configure those via [FuelManager](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt)

**Comment by Tchoupinax** [comment]
Hello,
i do not really understand what to do... i just want to use the function. :D 
Why must i configure context for block mode while aynschronus mode is working well without anything else ? ^^
Thank you for answer

**Comment by kittinunf** [comment]
@Tchoupinax I am not sure what you mean but for me, both sync and async are failure to me with same exception. I also attached screenshot for you as reference.

<img width="1338" alt="screen shot 2017-03-24 at 0 05 23" src="https://cloud.githubusercontent.com/assets/4669517/24254220/a9f18408-1025-11e7-91fb-5863eb877da1.png">

**Comment by Tchoupinax** [comment]
@kittinunf My problem is this following 
![d](https://cloud.githubusercontent.com/assets/9136206/24292319/1f766ec0-108d-11e7-91c4-951ef949d1b1.jpg)

While this following is working without any problem !
```Java
//get
Fuel.get("http://httpbin.org/get", params).responseString(new Handler<String>() {
    @Override
    public void failure(Request request, Response response, FuelError error) {
    	//do something when it is failure
    }

    @Override
    public void success(Request request, Response response, String data) {
    	//do something when it is successful
    }
});
```

As you mentionned in your description : "It returns the same parameters as the async version, but it blocks the thread. It supports all the features of the async version.".
I need to use the blocking mode in my project.. ^^

My gradle file : 
```Gradle
compile 'com.github.kittinunf.fuel:fuel-android:1.5.0'
```

Regards,

**Comment by kittinunf** [comment]
Oh, you are talking about compile error? I see. Because I am no longer use Java regularly so that I didn't know that some of the interface was not properly translated for Java user.

In the meantime, I think you can do this;

``` Java
Fuel.get("http://httpbin.org/get", params).responseString(Charset.defaultCharset());
```

I will make sure that I address those inconveniences for Java user in the next release. 🙏

**Comment by kittinunf** [comment]
Can you confirm whether this issue is somehow solved by using workaround?

**Comment by Tchoupinax** [comment]
Yeah ... Sorry i thought i have answered and closed. Thank you man ! :)
