### ISSUE TITLE
Progress handler for simple GET/POST requests

### ISSUE THREAD

**Issue by 17plus9** [kittinunf/Fuel#146]
Unfortunately, the progress handler seems to only be implemented/useable with the upload/download functions which are not appropriate for all use cases. It is therefore requested to have this functionality for all kinds of transmissions such as custom GET/POST requests.

**Comment by kittinunf** [comment]
Yes, that is something I has planned to do but I haven't got time to really implement it. If you would love to contribute in this area, please let me know.

**Comment by yoavst** [comment]
I think the solution would be wrapping the `inputStream` we provides the user to serialize (in `ResponseDeserializable` with a wrapper that reports progress on use.
