### ISSUE TITLE
How can I set a source (local) IP address for HttpRequest?

### ISSUE THREAD

**Issue by amalakhov** [kittinunf/Fuel#148]
We have few external ip's. How can I specify source (local) IP address for HttpRequest?

Simple test case: I would like to use 127.0.0.5 to connect to my server on 127.0.0.1

**Comment by romanvolkov-io** [comment]
https://en.wikipedia.org/wiki/IP_address_spoofing

**Comment by kittinunf** [comment]
close as inactive
