### ISSUE TITLE
Proguard breaks Deserializer

### ISSUE THREAD

**Issue by westlinkin** [kittinunf/Fuel#149]
I have a problem. If I enables Proguard, it breaks Deserializer. For example: 
```kotlin
"http://xxx.yyy.zzz".httpGet().responseObject(A.Deserializer()) { request, response, result ->
   Log.d(TAG, response.toString())
   val a = result.result.component1()
 }
```

In this example, I can see logcat shows the response with a Body. But the value of `a` is empty, not `null` but empty. All the variables in `Class A` is the default value.

Here is `A`: 
```kotlin
class A: Serializable {

    var page = 0
    var explicit = false
    var list: ArrayList<SubA> = ArrayList<SubA>()

    class Deserializer : ResponseDeserializable<A> {
        override fun deserialize(content: String) =Gson().fromJson(content, A::class.java)
    }
}
 ```

And `SubA`:
```kotlin
class SubA: Serializable {
    var duration = 0L
    var id = String()

    class Deserializer : ResponseDeserializable<SubA> {
        override fun deserialize(content: String) =Gson().fromJson(content, SubA::class.java)
    }
}
```

How to fix this?

**Comment by westlinkin** [comment]
Update: If I enable `-dontobfuscate` feature, it works fine. When I disable `-dontobfuscate`, get empty `A` variable.

**Comment by kittinunf** [comment]
Thanks for reporting. Would you mind help me documenting this in the README.md so that others can benefit from it? Thank you in advance!
