### ISSUE TITLE
NoClassDefFoundError: kotlin.collections.EmptyList

### ISSUE THREAD

**Issue by pablobaldez** [kittinunf/Fuel#151]
i'm getting an exception when i'm initiallizing the FuelManager
For some reason the baseParams can't be initialized with emptyList() method.

I'm using kotlin 1.1.1

**Comment by kittinunf** [comment]
I have been used it with no error. Would you mind adding more info in here so that we can hunt down the problem?

**Comment by kittinunf** [comment]
Close as inactive.
