### ISSUE TITLE
ArrayList is posted as String

### ISSUE THREAD

**Issue by Vincent-Loi** [kittinunf/Fuel#152]
Hi, I'm trying to post an ArrayList of strings to the server but it is passed as a string array. See below example:

Expected Results:
```
  some_key: [some_value, some_second_value],
```

Actual Results:
```
  some_key: '[some_value, some_second_value]',
```

Notice that there is a ' ' wrapped around the array representing a string. 

 ```
val parameters = listOf("some_key" to object.listOfValues)
```
listOfValues is an ```ArrayList<String>```

Currently, the Fuel post request looks like this:
 ```Fuel.post(url, listOf("some_key" to object.listOfValues)).responseJson()```

I have tried converting to different types of list, to an JSON string and then passing this in ```.body()``` but results weren't what I expected.

**Comment by kittinunf** [comment]
Ah, thanks so much for reporting the issue. Yes, `Fuel` by itself do not know how to serialize it so you need to manually supply it in the `body()` block.
Can you elaborate more on why

**Comment by kittinunf** [comment]
I am gonna close this because it is inactive.
