### ISSUE TITLE
Customizations for multi file upload

### ISSUE THREAD

**Issue by Querschlag** [kittinunf/Fuel#161]
First of all, great thing that multi file upload has been implemented!

I propose adding some options to allow setting
- media type
- file name
- field value

for example: in OkHttp I can do this:
```
body.addFormDataPart("images[]", "image_name.jpg", RequestBody.create(MediaType.parse("image/jpeg"), imageFile))
```

**Comment by babedev** [comment]
Sound interesting. It will be supported in next release.

**Comment by o-nix** [comment]
> media type
Related to #155

**Comment by Querschlag** [comment]
Brilliant!
Could you also add an option for the field value the files get assigned to?
Maybe a data class that hold the files + the field value...

**Comment by yoavst** [comment]
@Querschlag I'm not knowledgeable in the field of HTTP Upload, so was the feature you asked for was added?

**Comment by kittinunf** [comment]
I think it should be supported already. Closing this.
