### ISSUE TITLE
POST form-data without file

### ISSUE THREAD

**Issue by rostopira** [kittinunf/Fuel#165]
Backend dev with who I'm working currently is a bit strange. He sending me data in JSON, but I must send him form-data 0_o

I implemented the same with OkHttp3, but looking forward new releases to get rid of it

```
        val client = OkHttpClient()
        val body = FormBody.Builder().add("status", status.toString()).build()     // status == 2
        val req = Request.Builder()
            .header("Authorization", FuelManager.instance.baseHeaders!!["Authorization"])
            .url("$URL")
            .post(body)
            .build()
        doAsync {
            val resp = client.newCall(req).execute()
            Log.wtf("Response", resp.toString())
        }
```

BTW, thanks for such great library, I really enjoying developing with it ^_^

P.S.: Just checked, in another API I must post simple values and a file at the end...

**Comment by Naetmul** [comment]
Maybe related with this issue: https://github.com/kittinunf/Fuel/issues/154

**Comment by ParkerK** [comment]
PR #162 made this possible. On your specify an empty list for `.dataParts{}` and you can do uploads without passing files

```
val body= listOf("Email" to "mail@example.com", "Name" to "Joe Smith" )

Fuel.upload("/post", param = body)
    //Upload normally requires a file, but we can give it an empty list of `DataPart`
    .dataParts{ request, url -> listOf<DataPart>() } 
    .responseString { request, response, result ->
        ...
    }
```

**Comment by rostopira** [comment]
Thanks for that. For those, who love copy paste, correct version of code above

```
Fuel.upload("/post", parameters = body)
                .dataParts { _, _ -> listOf() }
                .responseString { request, response, result -> 
                    
                }
```
