### ISSUE TITLE
Reactor support

### ISSUE THREAD

**Issue by austinv11** [kittinunf/Fuel#167]
I see you have an RxJava extension, I think you should consider adding a [Reactor](https://github.com/reactor/reactor-core/) extension as well. It is pretty similar to rxjava so it shouldn't require too much effort.

**Comment by austinv11** [comment]
I could probably PR support later if you'd like

**Comment by kittinunf** [comment]
👍  please. I am more than happy to accept your PR.

**Comment by austinv11** [comment]
Do you have a place where I can discuss this with you? I am having some difficulties in setting the project up in intellij.

**Comment by kittinunf** [comment]
Stale issue as I don't think we have a plan for this.
