### ISSUE TITLE
Form-data with file upload?

### ISSUE THREAD

**Issue by bramhaag** [kittinunf/Fuel#169]
I'm trying to upload a file with form-data, but I can't find the correct way to do it. This is what it looks like in Retrofit:
```java
MultipartBody.Part.createFormData("files[]", fileName, requestBody);
```

Is there a way in Fuel to do this?

**Comment by babedev** [comment]
You can do with `source` like this

```Kotlin
.upload("/post")
.source { request, url ->
   File(currentDir, fileName)
}
.name { "files" }
.responseString { req, res, result -> }
````

Hope this answer your question :)

**Comment by bramhaag** [comment]
Sadly that doesn't fix my issue, the form data is still not set

**Comment by ParkerK** [comment]
I *think* you can do .upload("/post, params=YourFormData)

Put your params in the List<Pair<String, Any>> format. I may be mistaken though if this works without a file

**Comment by ParkerK** [comment]
Update: You can do this, see my response in #165

**Comment by yoavst** [comment]
Closing as inactive, please reopen if you need more help on this question.

**Comment by C06A** [comment]
I tried this, but the resulting multipart body still collect separate part for each file. The name of the part is "files1", "files2", etc.
What I need (and seams the originator of this topic) the multipart with single part named "files" and containing the list of files.

How can we do THAT?
