### ISSUE TITLE
LiveData support

### ISSUE THREAD

**Issue by KucherenkoIhor** [kittinunf/Fuel#174]
Are you going to add LiveData support?

**Comment by kittinunf** [comment]
Yes, I do love to do that 👍  Thanks for asking.

I would not mind pull request too if you want to do one. I am more than happy to accept it. :)

**Comment by KucherenkoIhor** [comment]
Thank you. I will do it:)

**Comment by KucherenkoIhor** [comment]
I created [pull request](https://github.com/kittinunf/Fuel/pull/175)

**Comment by KucherenkoIhor** [comment]
Could you check out!??

**Comment by kittinunf** [comment]
Yes! Thanks so much as sorry for the delay 🙏
