### ISSUE TITLE
File upload from InputStream directly

### ISSUE THREAD

**Issue by jilees** [kittinunf/Fuel#176]
I try to upload file from internal Uri using ContentResolver. I have got filename and Uri (I can open inputstream over ContentResolver) but I have no File. 
There's a stream and a filename inside UploadTaskRequest but I cannot access them. 
The only workaround I found is to create temporary file.
Could you please consider about create alternative way of UploadTaskRequest initialization?

**Comment by Naetmul** [comment]
I second this.

It'd be better if we can call `upload` with (a list of) `InputStream`(s), instead of (a list of) `File`(s).

**Comment by twinone** [comment]
Would be really useful if added!
