### ISSUE TITLE
NoClassDefFoundError: kotlin.jvm.internal.Intrinsics

### ISSUE THREAD

**Issue by inciler88** [kittinunf/Fuel#182]
I use fuel for my android project. If I use api level 21 or more it is okey however if I use api level 19 or lower it have "NoClassDefFoundError" issue.

**Comment by SimplySerenity** [comment]
Had the same error when building for JVM, and I was able to solve it by building as a Shadow jar. So it was just a case of not all dependencies being included in the build for some reason.

**Comment by yoavst** [comment]
Closing the issue as fixed.
