### ISSUE TITLE
responseJSON is not usable in blocking call

### ISSUE THREAD

**Issue by gperdomor** [kittinunf/Fuel#183]

**Comment by kittinunf** [comment]
Can you leave more useful information in hunting down this problem?

**Comment by ParkerK** [comment]
@gperdomor I'm using `responseJSON()` as a blocking call in one of my projects without issue. It may be a problem with your code, can you share or close this?

**Comment by yoavst** [comment]
`responseJson` is defined [here](https://github.com/kittinunf/Fuel/blob/5ce5955b34a2f237ed3b3c223415da74619ad4ab/fuel-android/src/main/kotlin/com/github/kittinunf/fuel/android/extension/Requests.kt). Closing this as `responseJson` is available in both sync and async mode.
