### ISSUE TITLE
maven?

### ISSUE THREAD

**Issue by DanoOM** [kittinunf/Fuel#185]
I have been trying to include this in a maven kotlin project..but..no luck..
I searched: https://bintray.com/bintray/jcenter
for com.github.kittinunf.fuel.fuel
but it does not appear to find the artifact?
my maven pom:
 <repository>
      <id>jcenter</id>
      <url>http://jcenter.bintray.com </url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>never</updatePolicy>
        <checksumPolicy>warn</checksumPolicy>
      </snapshots>
       <releases>
         <enabled>true</enabled>
         <checksumPolicy>warn</checksumPolicy>
      </releases>
   </repository>
..

<properties>
    <kotlin.version>1.1.2-5</kotlin.version>
 </properties>  
  <dependencies>
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib-jre8</artifactId>
        <version>${kotlin.version}</version>
    </dependency>
    <dependency>
        <groupId>com.github.kittinunf.fuel</groupId>
        <artifactId>fuel</artifactId>
        <version>${kotlin.version}</version>
    </dependency>

**Comment by kittinunf** [comment]
Hmm can you try this?

``` XML
<dependency>
  <groupId>com.github.kittinunf.fuel</groupId>
  <artifactId>fuel</artifactId>
  <version>1.8.0</version>
  <type>pom</type>
</dependency>
```

**Comment by DanoOM** [comment]
It appears to be an issue with how we ‘proxy’ maven-central..not sure I would have expected the repository in my local pom file to override that, but apparently not.
Once I ‘blew-away’ my .m2/settings.xml it started working. ☺

**Comment by kittinunf** [comment]
Closing this issue then.
