### ISSUE TITLE
.progress{} repeats and shows totalBytes=0 the second time

### ISSUE THREAD

**Issue by ParkerK** [kittinunf/Fuel#188]
I'm using the `.progress{}` handler to track uploading a form with a file. For some reason though, after it's "uploaded all the bytes" it starts the progress over, with a `totalBytes` value of `0`. Am I doing something wrong or misunderstanding something? Or is this a bug?

Relevant code:

```
var f = FuelManager()
f.baseHeaders = mapOf(...)


 f.upload("URL", Method.POST, params)
                    .sources { request, url -> myFiles}
                    .name { "file" }
                    .progress { readBytes, totalBytes ->
                         info("read $readBytes  --- total $totalBytes")
                    }. responseString{ ...

```

Results in:

> read 1132   --- total 9215
> read 2156   --- total 9215
> read 3180   --- total 9215
> read 4204   --- total 9215
> read 5228   --- total 9215
> read 6252   --- total 9215
> read 7276   --- total 9215
> read 8137   --- total 9215
> read 9215   --- total 9215
> read 1132   --- total 0
> read 2156   --- total 0
> read 3180   --- total 0
> read 4204   --- total 0
> read 5228   --- total 0
> read 6252   --- total 0
> read 7276   --- total 0
> read 8137   --- total 0
> read 9215   --- total 0
> read 1132   --- total 0
> read 2156   --- total 0
> read 3180   --- total 0
> read 4204   --- total 0
> read 5228   --- total 0
> read 6252   --- total 0
> read 7276   --- total 0
> read 8137   --- total 0
> read 9215   --- total 0

Thanks for this library by the way! :)

**Comment by yoavst** [comment]
@ParkerK is it still an issue?

**Comment by markGilchrist** [comment]
@ParkerK I haven't been able to recreate this in the current version, can you confirm this is still an issue if not we would like to close this. many thanks

**Comment by SleeplessByte** [comment]
Since this has been stale for so long, let's close it. It may always be re-opened at later time.
