### ISSUE TITLE
Does it support handle 304 not modified response?

### ISSUE THREAD

**Issue by edipo2s** [kittinunf/Fuel#191]
304 response don't send body again, so in this case it should recover body from a previous cached response. I've search for "ETag", "Cache-Control" and "If-None-Match" in source code, but don't found anything about.

This library can handle "304 Not Modified" responses, if I add header like "Cache-Control: max-age=604800" in resquest?

**Comment by ParkerK** [comment]
Fuel currently does not support 304, that being said, a server shouldn't be returning 304 to Fuel, as Fuel never sends `If-None-Match` or `If-Modified-Since` in the headers, if I'm understand you correctly

**Comment by kittinunf** [comment]
It seems like we could close this down.
