### ISSUE TITLE
how to send Post/Get request?

### ISSUE THREAD

**Issue by WanderingJew** [kittinunf/Fuel#192]
I have spent few hours and i haven't understand what i should write to send request to server:
Fuel...
or "name".http...

**Comment by KucherenkoIhor** [comment]
@WanderingJew Do you use Kotlin or Java?
For Kotlin:
```
"http://httpbin.org/get".httpGet().responseString { request, response, result ->
	//do something with response
	when (result) {
        is Result.Failure -> {
            error = result.getAs()
        }
        is Result.Success -> {
            data = result.getAs()
        }
    }
}
```
For Java:
```
Fuel.get("http://httpbin.org/get", params).responseString(new Handler<String>() {
    @Override
    public void failure(Request request, Response response, FuelError error) {
    	//do something when it is failure
    }

    @Override
    public void success(Request request, Response response, String data) {
    	//do something when it is successful
    }
});
```
It works!!!

**Comment by WanderingJew** [comment]
@KucherenkoIhor What i should import to do this actions?

_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KucherenkoIhor** [comment]
@WanderingJew 
```

import com.github.kittinunf.fuel.*
import com.github.kittinunf.fuel.core.FuelError
import com.github.kittinunf.fuel.core.FuelManager
import com.github.kittinunf.fuel.core.Response
import com.github.kittinunf.fuel.core.ResponseDeserializable
import com.github.kittinunf.fuel.core.interceptors.loggingResponseInterceptor
import com.github.kittinunf.fuel.livedata.liveDataObject
import com.github.kittinunf.fuel.rx.rx_object
import com.github.kittinunf.result.Result
```
[android sample](https://github.com/kittinunf/Fuel/blob/master/sample/src/main/kotlin/com/example/fuel/MainActivity.kt)

**Comment by WanderingJew** [comment]
@KucherenkoIhor Spasibo!

_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WanderingJew** [comment]
@KucherenkoIhor My server doesnt see request. Request from Js server can see, but with your code exist problems. It works, but server cant see any actions)

_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KucherenkoIhor** [comment]
@WanderingJew do you see request in your client's logcat?

**Comment by WanderingJew** [comment]
@KucherenkoIhor How i can check it?)

_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KucherenkoIhor** [comment]
@WanderingJew Just look at the logcat!

**Comment by WanderingJew** [comment]
![image](https://user-images.githubusercontent.com/24897685/28085363-3d4f942e-6684-11e7-8805-23a5bfe519a0.png)

**Comment by feelfreelinux** [comment]
@WanderingJew **You need to have ` <uses-permission android:name="android.permission.INTERNET" />` permission in `AndroidManifest.xml`**. Then, just use `Log.v("APP", result.getAs<String>());`. So this code should work:
`"your url".httpGet().responseString { request, response, result ->
	when (result) {
        is Result.Failure -> {
            error = result.getAs()
        }
        is Result.Success -> {
            Log.v("APP", result.getAs<String>())
        }
    }
}`

This will show your response in logcat tab of android studio.

**Comment by yoavst** [comment]
Closing as non-active.
