### ISSUE TITLE
Async return

### ISSUE THREAD

**Issue by WanderingJew** [kittinunf/Fuel#196]
I am writing app and i am using this Async construction:
```kotlin
async { 
val result = await { 
     //Long running code }
 // Use result
 }
```
Get req located in await body but i want to use"data" from Fuel.get in "use result" field. How i can do it?

_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yoavst** [comment]
Just use `Fuel` in blocking mode as described [here](https://github.com/kittinunf/Fuel#blocking-mode) inside `await`.
