### ISSUE TITLE
Condition on README snippet seems inverted

### ISSUE THREAD

**Issue by jivimberg** [kittinunf/Fuel#198]
Error condition on README async example for Kotlin seems to be inverted: https://github.com/kittinunf/Fuel/blob/62daa920d93fc1d7cc5ef1bd3dbbd7b6804c475c/README.md#L78

**Comment by kittinunf** [comment]
Can you elaborate a bit on that? Even better, if you can open a PR to resolve that.

**Comment by kittinunf** [comment]
Close this.
