### ISSUE TITLE
Multiple instances of Fuel

### ISSUE THREAD

**Issue by deive** [kittinunf/Fuel#204]
At the moment everything is hard-coded to singletons. Would it be possible to make this usable as separate objects? 
A lot of applications require the use of more than just a single API, so being able to set variables like base URL for each of the APIs would be useful.

**Comment by kittinunf** [comment]
If you don't want to use the Singletons, you can do 

``` Kotlin
val manager = FuelManager()
manager.basePath = "http://httpbin.org"
manager.request(Method.GET, "/get")

val manager2 = FuelManager()
manager2.basePath = "http://example.com"
manager2.request(Method.POST, "/post")
```
FuelManager can be instantiated and used in any way you can possibly think of. Do you think that would help you solve your problem?

**Comment by deive** [comment]
I am sorry, donno how I missed that!
Thanks for your response

**Comment by dpmaycry** [comment]
So can I use "http://www.google.com".httpget() or  fuel.get("http://www.google.com") way in Multiple instances of Fuel? And How?
