### ISSUE TITLE
How to use Fuel to scrape data

### ISSUE THREAD

**Issue by jbdev** [kittinunf/Fuel#205]
I'd like to use Fuel to scrape some data, but it's important to have the  features:

- Cookie jar: Is needed to 
- HTTP proxy + authentication 
- SOCKS5 proxy + authentication 
- Define the Charset of the encoded data

Thanks

**Comment by yoavst** [comment]
When I use fuel to scrap, I handle the cookie saving myself. About proxy, you can define it from Java  probably, not?

**Comment by jbdev** [comment]
I'll test, @yoavst. Thanks

**Comment by yoavst** [comment]
Close as non-active.
