### ISSUE TITLE
Make Either sealed

### ISSUE THREAD

**Issue by mplatvoet** [kittinunf/Fuel#21]
M13 introduces the concept of [sealed classes](http://kotlinlang.org/docs/reference/classes.html#sealed-classes) which improves pattern matching so you are not required to use an `else` case anymore.

**Comment by kittinunf** [comment]
Definitely, we should mark it sealed.

Would you mind wait a little, I will bundle this together with M13 support branch. :)

**Comment by mplatvoet** [comment]
Of course I don't mind :)
