### ISSUE TITLE
First-class support for Jackson

### ISSUE THREAD

**Issue by asarkar** [kittinunf/Fuel#211]
Something like:
`responseJson<T>(handler: (Request, Response, Result<T, FuelError>) -> Unit)`, where `T` can be `Json` or a Jackson type like `JsonNode`.

**Comment by kittinunf** [comment]
I don't have anything against this aside from I don't use Jackson for JSON parsing library myself (PS. Gson seems to be satisfied my needs in many of situation). If you are willing to make a PR, I wouldn't mind taking a look. 👍

**Comment by asarkar** [comment]
I opened https://github.com/kittinunf/Fuel/issues/225 which is a superset of this ticket.
