### ISSUE TITLE
Can't convert LinkedMapTree to MyClass

### ISSUE THREAD

**Issue by bbetter** [kittinunf/Fuel#215]
Same works for retrofit
structure of response is something like
[{
 "field1": 10,
"field2":"hello",
"field3": [10.0,52.0,52.6] 
},{
 "field1": 1,
"field2":"sdg",
"field3": [10.5,12.0,1.6]
}]

**Comment by ParkerK** [comment]
Not sure exactly what you're asking, but it sounds like https://github.com/kittinunf/Fuel#gson-deserialization could be what you need?

**Comment by bbetter** [comment]
Here is my POKO
`data class Rate(val txt: String, val rate: Double, val cc: String, val date: Date)`
Here is request
```
  url.httpGet()
                    .rx_object(GsonDeserializer<List<Rate>>())
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .doOnError {
                        it.printStackTrace()
                    }

                    .map {
                        (obj, _) ->
                        obj.orEmpty()
                    }
                    .doOnSuccess {
                        cachedRates = it
                        lastUpdated = Calendar.getInstance().timeInMillis
                    }
```
Here is error 
<img width="911" alt="screen shot 2017-08-23 at 1 45 41 pm" src="https://user-images.githubusercontent.com/6604503/29612308-7be74f28-8809-11e7-8fe8-9cdabfe2b99d.png">

**Comment by ParkerK** [comment]
`-keep class your.app.package.Rate`
and whatever is here: https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg

to your ProGuard

**Comment by bbetter** [comment]
it's not release build i experience this issue, but debug
it has no proguard applied

**Comment by foxsake** [comment]
i have the same issue on my project.
it occurs on my entity's dao implementation on build.

**Comment by pltanton** [comment]
Got same issue, when I try something like
```kotlin
...

data class ScheduleEntry(
        var componentName: String,
        var pluginKey: String,
        var version: String,
        var installedVersion: String?)

data class ScheduleResponse(var schedule: Array<ScheduleEntry>, var status: String)

fun Client.getSchedule() : ScheduleResponse {
    val (_, _, result) = Fuel.get(this.apiURL(API_SCHEDULE_ENTRIES)).responseObject<ScheduleResponse::class.java>()
...
```

But if I replace 'generic' style `responseObject` invocation with 'deserializer' style like this:
```kotlin
data class ScheduleEntry(
        var componentName: String,
        var pluginKey: String,
        var version: String,
        var installedVersion: String?)

data class ScheduleResponse(var schedule: Array<ScheduleEntry>, var status: String) {
    class Deserializer: ResponseDeserializable<ScheduleResponse> {
        override fun deserialize(content: String) = Gson().fromJson(content, ScheduleResponse::class.java)
    }
}

fun Client.getSchedule() : ScheduleResponse {
    val (_, _, result) = Fuel.get(this.apiURL(API_SCHEDULE_ENTRIES)).responseObject(ScheduleResponse.Deserializer())
...
```
everything seems fine.

**Comment by KucherenkoIhor** [comment]
Hi, @bbetter. It looks like [a problem with Gson](https://github.com/google/gson/issues/550), not Fuel.
So, I think you have to write your deserializer.

**Comment by yoavst** [comment]
Probably same issue as #233

**Comment by kittinunf** [comment]
I think this has been resolved, feel free to reopen if you think otherwise.
