### ISSUE TITLE
Iterating response headers throws NPE while the same works in OkHttp

### ISSUE THREAD

**Issue by asarkar** [kittinunf/Fuel#217]
```
class Main {
    private val url = "https://fantasy.premierleague.com/drf/elements/"

    fun syncGetOkHttp() {
        println("\n===")
        println("OkHttp")
        println("===")
        val client = OkHttpClient()

        val request = Request.Builder()
                .url(url)
                .header("Accept", "application/json")
                .build()

        println("Request headers ===>")
        request.headers().toMultimap().forEach { k, v -> println("$k ===> $v.") }

        val response = client.newCall(request).execute()
        if (!response.isSuccessful) throw IOException("Unexpected code: ${response.code()}.")

        println("Status code ===> ${response.code()}.")
        println("Body ===> ${String(response.body()!!.bytes())}.")

        val responseHeaders = response.headers()

        println("Response headers ===>")
        responseHeaders.toMultimap().forEach { k, v -> println("$k ===> $v.") }
    }

    fun syncGetFuel() {
        println("\n===")
        println("Fuel")
        println("===")

        val (request, response, result) = url.httpGet().run {
            httpHeaders.put("Accept", "application/json")

            responseString()
        }

        println("Request headers ===>")
        request.httpHeaders.forEach { k, v -> println("$k ===> $v.") }

        println("Status code ===> ${response.httpStatusCode}.")

        when (result) {
            is Result.Failure -> {
                result.error.exception.printStackTrace()
            }
            is Result.Success -> {
                println("Body ===> ${result.get()}.")

                println("Response headers ===>")
                response.httpResponseHeaders.forEach { k, v -> println("$k ===> $v.") }
            }
        }
    }
}
```

Output:
===
OkHttp
===
Request headers ===>
accept ===> [application/json].
Status code ===> 200.
Body ===> . // blank! Issue reported in this [SO thread](https://stackoverflow.com/q/45702466/839733)
Response headers ===>
accept-ranges ===> [bytes].
connection ===> [close].
content-length ===> [0].
content-type ===> [application/json].
date ===> [Wed, 16 Aug 2017 04:00:44 GMT].
retry-after ===> [0].
server ===> [Varnish].
via ===> [1.1 varnish].
x-cache ===> [MISS].
x-cache-hits ===> [0].
x-served-by ===> [cache-sea1047-SEA].
x-timer ===> [S1502856045.965729,VS0,VE0].

Fuel
===
Request headers ===>
Accept-Encoding ===> compress;q=0.5, gzip;q=1.0.
Accept ===> application/json.
Status code ===> 200.
Body ===> // elided
Response headers ===>
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.example.Main$syncGetFuel$3.accept, parameter k
	at com.example.Main$syncGetFuel$3.accept(Main.kt)
	at com.example.Main$syncGetFuel$3.accept(Main.kt:13)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at com.example.Main.syncGetFuel(Main.kt:66)
	at com.example.MainKt.main(Main.kt:75)

Process finished with exit code 1

**Comment by kittinunf** [comment]
Hmm this is very interesting. Let me try to investigate this and get back to you.

**Comment by ParkerK** [comment]
Here's the HTTPHeader response @kittinunf 

`{null=[HTTP/1.1 200 OK], X-Cache=[HIT, HIT], Server=[nginx], Edge-Control=[max-age=60], Connection=[keep-alive], Date=[Thu, 17 Aug 2017 14:48:36 GMT], X-Timer=[S1502981316.182794,VS0,VE1], Via=[1.1 varnish, 1.1 varnish], Allow=[GET, HEAD, OPTIONS], Accept-Ranges=[bytes], X-Frame-Options=[DENY], Fastly-Debug-Digest=[fdb44d2dd7c0b26c639a8b3476f8c63661c68707cc3b9446f8ed3941cd3fe01e], Cache-Control=[no-cache, no-store, must-revalidate, max-age=0], X-Served-By=[cache-lcy1120-LCY, cache-ord1735-ORD], Content-Encoding=[gzip], Vary=[Accept-Encoding], Content-Length=[40337], X-Cache-Hits=[3, 1], Age=[44], Content-Language=[plfplen], Content-Type=[application/json]}`

It seems to do this for all urls actually as `http://google.com` gives:

`>>> response.httpResponseHeaders
{X-Frame-Options=[SAMEORIGIN], null=[HTTP/1.1 200 OK], Server=[gws], Cache-Control=[private, max-age=0], Content-Encoding=[gzip], Set-Cookie=[NID=110=Q-wJHpMG3ZCMHTZjA3e1mioOs0JbHkFuXMnQ6su15hkqCgFGZOZNlKL5f4R-iJ5ehBgX5f3JFJ3lJwOdoU1sHZOsv5utjOP_pVbnWe-od4HHdiGEaj351owm9uixfoa2; expires=Fri, 16-Feb-2018 14:49:49 GMT; path=/; domain=.google.com; HttpOnly], Expires=[-1], X-XSS-Protection=[1; mode=block], Content-Length=[4495], P3P=[CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."], Date=[Thu, 17 Aug 2017 14:49:49 GMT], Content-Type=[text/html; charset=ISO-8859-1]}`

**Comment by asarkar** [comment]
While we are discussing headers, I filed another issue about that.
https://github.com/kittinunf/Fuel/issues/220

**Comment by yoavst** [comment]
Closing this issue as #218 should fix it. Please comment if it is still an issue.
