### ISSUE TITLE
java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by foxsake** [kittinunf/Fuel#224]
Got this error when trying to run [this](https://github.com/KucherenkoIhor/Android-Architecture-Components) sample

Stack trace:
`08-23 10:30:03.379 14286-14286/com.ik.exploringviewmodel W/System.err: com.google.gson.JsonSyntaxException: java.io.IOException: Stream closed
08-23 10:30:03.379 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:825)
08-23 10:30:03.379 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:775)
08-23 10:30:03.379 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.github.kittinunf.fuel.gson.GsonDeserializer.deserialize(FuelGson.kt:16)
08-23 10:30:03.379 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.github.kittinunf.fuel.core.ResponseDeserializable$DefaultImpls.deserialize(Deserializable.kt:18)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.github.kittinunf.fuel.gson.GsonDeserializer.deserialize(FuelGson.kt:13)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:85)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.github.kittinunf.fuel.rx.RxFuelKt$rx_result$1.subscribe(RxFuel.kt:31)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.Single.subscribe(Single.java:2703)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.Single.subscribe(Single.java:2703)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.Single.subscribe(Single.java:2703)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.Single.subscribe(Single.java:2703)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:56)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.flowable.FlowableElementAtSingle$ElementAtSubscriber.onNext(FlowableElementAtSingle.java:87)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:129)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:637)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at java.lang.Thread.run(Thread.java:776)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err: Caused by: java.io.IOException: Stream closed
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at java.util.zip.GZIPInputStream.ensureOpen(GZIPInputStream.java:61)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:111)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
08-23 10:30:03.380 14286-14286/com.ik.exploringviewmodel W/System.err:     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:184)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1346)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1582)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:806)
08-23 10:30:03.381 14286-14286/com.ik.exploringviewmodel W/System.err: 	... 25 more`

**Comment by KucherenkoIhor** [comment]
Hi,  @foxsake  . Thank you! Does this error happen all the time?

**Comment by yoavst** [comment]
@foxsake was it resolved?

**Comment by ivanovstepan** [comment]
get same issue on  .responseObject<SomeClass>() 
when i have addResponseInterceptor

**Comment by markGilchrist** [comment]
@foxsake  can you post the code you are using so I can recreate?

**Comment by foxsake** [comment]
@markGilchrist i linked the code that i was trying to run on the post. Here it is again in case [https://github.com/KucherenkoIhor/Android-Architecture-Components](https://github.com/KucherenkoIhor/Android-Architecture-Components). I had the same implementation as that repo on my project. I also tried to recompile that repo and got the same issue(the stack trace i posted is from that repo). I can't say if it was already resolved since im not using the library anymore, you can test that repo.

Cheers!

**Comment by SleeplessByte** [comment]
The sample has not been updated in over a year. This might have been fixed. Since this has been stale for so long, let's close it. It may always be re-opened at later time.
