### ISSUE TITLE
Add documentation for PATCH

### ISSUE THREAD

**Issue by jervan** [kittinunf/Fuel#226]
PATCH does not send proper Method to server. HttpURLConnection does not support a PATCH method. FUEL adds a X-HTTP-Override-Method header to a POST request. While this is semi-standard in the industry not all servers utilize this header by default. Please add documentation that explains this. 

Supported Methods of HttpURLConnection http://download.java.net/jdk7/archive/b123/docs/api/java/net/HttpURLConnection.html#setRequestMethod(java.lang.String)

**Comment by KucherenkoIhor** [comment]
Hi, @jervan. Thank you. As I can see, you have a great experience on this topic. So, could you please create a pull request with this changes in the documentation. If you have other ideas how to improve Fuel, we will glad to merge it.
