### ISSUE TITLE
Cannot access request header fields after connection is set

### ISSUE THREAD

**Issue by mradzinski** [kittinunf/Fuel#228]
Attempting to execute:

```
"http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en".httpGet().response { request, response, result -> 
     println(request)
     println(response)
}
```

produces:
```
java.lang.IllegalStateException: Cannot access request header fields after connection is set
     at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:69)
     at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:16)
     at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:13)
     at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:49)
     at java.lang.Thread.run(Thread.java:761)
```

Using the `cUrlLoggingRequestInterceptor` I got the following curl that when executed on a terminal it works:

```curl -i -H "Accept-Encoding:compress;q=0.5, gzip;q=1.0" "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en"```

**Comment by kittinunf** [comment]
I cannot reproduce your error. What I did is following;

Go to sample folder in Fuel project and change the https://github.com/kittinunf/Fuel/blob/508dd2e05b7b88d1a3edb3fdc63d1861cecd89fd/sample/src/main/kotlin/com/example/fuel/MainActivity.kt#L44-L55 to 

<img width="888" alt="screen shot 2017-08-27 at 3 06 15" src="https://user-images.githubusercontent.com/4669517/29743875-baa7109a-8ad4-11e7-89f6-e931be2866f5.png">

Then, the emulator show the result as expected. (I clicked button multiple times)

![screenshot_1503770814](https://user-images.githubusercontent.com/4669517/29743880-cb2d59c4-8ad4-11e7-9ab6-ea84bc3afd27.png)

Is there anything more into this so I can reproduce the error?

**Comment by mradzinski** [comment]
Hey @kittinunf, Seems I'm not the only one. #229 is having the exact same exception. I'm using Fuel's latest version on Android Studio 3.0 Beta 3, `com.android.tools.build:gradle:3.0.0-beta3`. I tried the same and it's the same. I didn't even had to modify it, the same isn't working at all.

**Comment by mradzinski** [comment]
Also, Fuel seems to be the only library having this issue. I tried both, Retrofit and OkHttp, and all of them are working fine.

**Comment by apognu** [comment]
Author of #229 here.

Quite the same situation. Other libraries work fine, only the first request with Fuel succeeded any subsequent one fails with this error.

**Comment by KucherenkoIhor** [comment]
Hi, all! @apognu or @mradzinski, if you can reproduce this error may be you can to try fix one and create merge request. We will glad to merge it.

**Comment by mradzinski** [comment]
@KucherenkoIhor, well, I actually had to move away from Fuel due to this issue. As for reproducing it: Just download the sample from this repo, update its gradle & kotlin dependency and run it; Hint: It'll fail.

**Comment by kittinunf** [comment]
@mradzinski I think the sample fails because of other issues. Let's us focus on your issue first, shall we?

I will try to mimic your situation as much as possible. 

I have create this test [repo](https://github.com/kittinunf/FuelTest). 

I have push the commit I tested with your API endpoint. But I am unable to reprouce your issue. If you don't mind, could you please try in that repo and show it to me whether you could make it work or not.

**Comment by kittinunf** [comment]
Is there any update on your side @mradzinski ?

**Comment by saletrak** [comment]
I have exactly the same problem, but that isn't appeard whenever, i can't figure out where it depends.

**Comment by PichuChen** [comment]
Hello there, this problem happen on my Pixel (Android 8.0) and not happen on Samsung S7 (Android 7)

**Comment by kittinunf** [comment]
@PichuChen that is a bit weird. Do you know what could possibly trigger the problem? I have made the repo here. If you do have time, even better if you could come up with a test that fails?

**Comment by PichuChen** [comment]
@kittinunf Testing result on Pixel is successful, is really weird...
I will try to copy my code to reproduce this problem.

**Comment by molchanoviv** [comment]
I also faced this exception. But it happens only when i enable advanced profiling. With disabled profiler it works well.

**Comment by tteichner** [comment]
I've faced the same problem a few days ago. From my point of view there was a problem with the ide (android studio 3.1.3) and the used kotlin plugin. I could solve it by updating kotlin and the plugin to 1.2.50 and then all used com.android.support* libraries to 27.1.1. In addition i've cleaned my project entirely (fresh clone of repo) after a new build of the application the problem disappeared.

**Comment by markGilchrist** [comment]
is this still an issue?

**Comment by kittinunf** [comment]
Let's close this as it looks quite stale to me.
