### ISSUE TITLE
Is it possible to send POST request with prams in URL?

### ISSUE THREAD

**Issue by pltanton** [kittinunf/Fuel#231]
By default params is applyed to body, as form param, not as query params. Is it possible to change POST request params behavior like in GET request?

**Comment by KucherenkoIhor** [comment]
Hi, @pltanton. Please, provide an example of your request.

**Comment by pltanton** [comment]
If you use `Fuel.get("http://myapi", listOf("foo" to "bar"))` the GET request would be generated with empty body:
```
--> GET (http://myapi?foo=bar)
Body : (empty)
```

But if you use  `Fuel.post("http://myapi", listOf("foo" to "bar"))` params would be injected as form body params, not as query params:
```
--> POST (http://myapi)
Body : foo=bar
```

Is it possible to use params as query params for POST request?

**Comment by pltanton** [comment]
As I can see in sources, [post](https://github.com/kittinunf/Fuel/blob/ee3d422d0dca4e4868ebb3fe3bc92991cb5912b0/fuel/src/main/kotlin/com/github/kittinunf/fuel/Fuel.kt#L40-L49) method defined just like all other methods and didn't support to chose how to represent params in request.

As far as I understand params representation are chosed by `Encoding::encoder` method. What do you think about extending `get`, `post`, e.t.c methods by addotional parameter `paramsEncoding` of `enum class ParamsEncodingMethod { FORM, MULTIPART_FORM, QUERY, JSON_IN_BODY, e.t.c }` (or something like that)?

It is very useful to have possibility to chose that behaviour. Some REST APIs do not support parameters in POST request in form format, for example JIRA's API (at least if you trying to develop custom plugin). Futhermore it is also could be useful to pass params for get request in body.

**Comment by yoavst** [comment]
Imo, the signature of `Fuel.VERB` method should be just the URL and parameters should be provided as a method. This way you could do `Fuel.post(url).urlParams(...).bodyParams(...)` (naming is bad, I know).

**Comment by nanodeath** [comment]
As another data point, this limitation makes it impossible (or hard, at least) to use properly with the CouchDB API. [Updating documents](http://docs.couchdb.org/en/2.1.0/api/document/common.html#put--db-docid) is a PUT operation that requires a `rev` query parameter. Actually...I think I can set an `If-Match` header instead, but the other query parameter options have no header alternative.

**Comment by mrenou** [comment]
Waiting, is there any workaround to add a query param in a POST request ?

Thanks for the library

**Comment by pltanton** [comment]
@mrenou, you can just pass your query params directly in url like `Fuel.post('https://example.com?param=value&otherParam=otherValue')`

**Comment by markGilchrist** [comment]
@pltanton are you happy for this to be closed?

**Comment by pltanton** [comment]
ok.

**Comment by kittinunf** [comment]
We'll close this one.

**Comment by mobiletoly** [comment]
Found this post because was looking for the same functionality - how to append http query parameters to POST in Fuel. Ended up writing my own very small library that simplifies working with URL and HTTP parameters in Kotlin. While it is not Fuel-specific, but if anybody is interested, it has a small example with Fuel in README:

https://github.com/mobiletoly/urlsome
