### ISSUE TITLE
Why is responseJson only in fuel-android? 

### ISSUE THREAD

**Issue by deiga** [kittinunf/Fuel#232]
Writing a backend application which gets JSON kind of needs a way to deserialize JSON and I'm currently wondering why fuel core doesn't support this?

**Comment by yoavst** [comment]
`responseJson` is for [org.json](https://developer.android.com/reference/org/json/package-summary.html) library from android SDK. Fuel isn't depend on android, therefore it isn't included. 
In addition, Fuel has a module  for GSON support: https://github.com/kittinunf/Fuel#gson-deserialization

If you can tell me which Json library you use, I can help you with writing a deserializer.

**Comment by deiga** [comment]
Thanks. I just hadn't figured out how to use Fuel properly :)
