### ISSUE TITLE
? is added to the url

### ISSUE THREAD

**Issue by yoavst** [kittinunf/Fuel#24]
Dark magic has happened to me during development:
```kotlin
Log.e("tag", url)
val request = url.httpGet()
Log.e("tag", request.url.toString())
```
```
E/tag: http://ohel-shem.com/php/changes/changes_sys/index.php?layer=11
 E/tag: http://ohel-shem.com/php/changes/changes_sys/index.php?layer=11?
``` 

This `?` is breaking the url for this site.
Even adding `/` a the end of the url seem to doesn't work.

Edit: Encoding.kt
```kotlin
 if (encodeParameterInUrl(method)) {
            val query = if (path.last().equals("?")) "" else "?"
            modifiedPath += query + queryFromParameters(parameters)
```

**Comment by kittinunf** [comment]
It looks like a bug in encoding process. Let me fix this as soon as possible. 



—

**Comment by kittinunf** [comment]
In the meantime, can you use param to supply the query parameter?

PS. Sorry I was replying the previous answer on my mobile phone and github web somehow truncated my answer.

``` Kotlin
val url = "http://ohel-shem.com/php/changes/changes_sys/index.php"
val request = url.httpGet(mapOf("layer" to 11))  //this should properly encode the correct url
```

**Comment by yoavst** [comment]
I'm trying to separate the implementation from the classes, so there is a wrapper. Currently there is only a single request, so I'll keep it as is.

I'm using this method to fix it now:
```kotlin
private fun Request.bugFix(url: String): Request {
        this.path = url
        this.url = URL(url)
        return this
    }
```
