### ISSUE TITLE
Flexible toString method for Request

### ISSUE THREAD

**Issue by pltanton** [kittinunf/Fuel#240]
`toString` method of Request looks great and pretty useful in many cases now. It is useful to use it for logging before sending request, but often, when you use upload method you want to send some binary file to the remote REST service and when you do something like `log.info(request.toString())` it produses tons of non-ascii binary trash for logfile or console.

It would be really great if output of binary data would reduced automatically by libraray or by some additonal parameters or some representational class, which would incapsulate current toString logic.

It could be part of #225

**Comment by markGilchrist** [comment]
can we close this?
