### ISSUE TITLE
DELETE not sending body even though it was specified

### ISSUE THREAD

**Issue by mishaxz** [kittinunf/Fuel#245]
is this by design? or do I need to configure something? It shows the body in `request.toString()` but it does not send it with the actual request

**Comment by daleksandrovms** [comment]
yes, i see the same...

**Comment by mishaxz** [comment]
unfortunately because of this I had to switch to another library :( I really did like this library but I couldn't work around it

IF this behaviour ever changes, please drop a comment here so that I know about it - thanks!

**Comment by markGilchrist** [comment]
I am closing this as I believe it is a duplicate of 306 and that is now merged in
