### ISSUE TITLE
 com.google.gson.internal.LinkedTreeMap cannot be cast to java.util.List

### ISSUE THREAD

**Issue by 7hundeR** [kittinunf/Fuel#247]
BaseBean<T> baseBean =  new Gson().fromJson(jsonString, new TypeToken<BaseBean<T>>(){}.getType());
Why is it returned LinkedTreeMap?

**Comment by yoavst** [comment]
does it have anything to do with fuel?

**Comment by kittinunf** [comment]
Agree with @yoavst. Could you please elaborate more? @7hundeR ?

**Comment by 7hundeR** [comment]
Thank you. I found the reason

**Comment by utsavdotpro** [comment]
Hey @thundeGG, can you share what was the reason and how you resolved it?
Thanks
