### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by harryd31** [kittinunf/Fuel#248]
When making a request it's throwing an android.os.NetworkOnMainThreadException

**Comment by JairAviles** [comment]
Hey, I am doing a post using block mode and having the same error. Was it similar to your problem? How did you resolve it?

**Comment by harryd31** [comment]
There seemed to have been something wrong with my emulator. I know it sounds silly but also make sure the device you're testing on has access to the internet, on one occasion the device was on airplane mode and I also got that error (not sure how or why)

**Comment by JairAviles** [comment]
Thanks for your reply. In my case, I was testing on a real device, thus I called the Fuel post method in an Asycnk Task and problem solved. I am not sure, if this is a good practice, [though](http://simonvt.net/2014/04/17/asynctask-is-bad-and-you-should-feel-bad/).
