### ISSUE TITLE
POST Parameter encoding

### ISSUE THREAD

**Issue by mbreithu** [kittinunf/Fuel#249]
I'm trying to send some parameters to my API (Laravel project) using POST. The request works fine, but if one of the parameters contains a '+' (plus) character, the character is replaced with a ' ' (space) once the request reaches the server! 

After digging into the Encoding class, i found that when using POST, the content-type header is set to: "application/x-www-form-urlencoded" but the params themselves are not checked for special (reserved) characters. For urlencoded params the + sign will be interpreted as a space.

Solution would be to check params for reserved characters and replace them with their corresponding percent-encoding.

**Comment by romanstingler** [comment]
I'm having the exactly same behaviour.

I hope it isn't intended to escape by myself

**Comment by kittinunf** [comment]
Ah ... this is an oversight on my part. Would you be so kind to open PR for a patch? 🙏

**Comment by mbreithu** [comment]
Will do!
