### ISSUE TITLE
Update repository README.MD with Mocking code samples

### ISSUE THREAD

**Issue by JairAviles** [kittinunf/Fuel#251]
Regarding the issue stated on #186 the proper way to mock a method called from the Fuel client is to create a fake one, isn't it?

Thus, I would suggest adding a code sample covering how to create a Fuel client in **Kotlin** and **Java** as well, concerning unit testing. My arguments are that having great references on the documentation for this incredible library would make points to choose Fuel client rather than Retrofit (too much boilerplate for me) just for saying something.

There's a lot of apps still in Java and before considering moving to Kotlin, I think this would be helpful to maintain that legacy code.

**Comment by kittinunf** [comment]
@JairAviles Thanks for the comment and feedback. Great idea.

The documentation of this library is far from ideal. I will keep working on it. Please hang tight.

**Comment by kittinunf** [comment]
I really want to address this issue. 

To be able to close this, in what specific area you want us to improve? 

@JairAviles If you don't mind to spare 5 mins to share specifically what we should add?

**Comment by yoavst** [comment]
@kittinunf Maybe we can provide a testing module with a custom `FuelManager` that allows easy mocking of requests?

**Comment by JairAviles** [comment]
I agree with @yoavst suggestion.

**Comment by ransomhall** [comment]
+1 on some sample unit test documentation. I"m currently working through an issue with mockk and Fuel, and it would be helpful to know my (very simple) tests are correctly setup to begin with.

**Comment by geertberkers** [comment]
Yup, thats an good idea. Trying to make some calls to another server, and continuously getting SSL Handshake errors in the unit tests. Calling from postman/browser/mobile it self just works...

**Comment by SleeplessByte** [comment]
The test library has mocking, and per #444 all the projects use it. 

You may always override `FuelManager.client` to be a function where you control the response (executeRequest response).
