### ISSUE TITLE
Unable to download using gradle

### ISSUE THREAD

**Issue by zlepper** [kittinunf/Fuel#257]
I'm currently attempting to use Fuel, however i'm having some issues making gradle actually pull Fuel in as  a dependency. I can't make it work in my full project using spring, and I have tried making a minimum case, and that does not work either. 

Any ideas?

```gradle
group 'com.testproblem'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.1.51'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile 'com.github.kittinunf.fuel:fuel'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by yoavst** [comment]
What is the error?
`compile 'com.github.kittinunf.fuel:fuel'`
have you forgotten the version?

**Comment by zlepper** [comment]
Apparently that was it... I could have sworn we had tried with specifying version too, without any luck. 

Must have been a hickup on our computers/internet.
Sorry for being a bother. 

But how come I can pull spring framework without specifying version, but not Fuel? Is it something with jcentral?

**Comment by kittinunf** [comment]
I think you just get away by using '+' in lieu of the version number.

However, adding dependency without a specific version is never a good idea. I would recommend you to specify the version instead.
