### ISSUE TITLE
JSON deserialization behaves differently in blocking vs async mode

### ISSUE THREAD

**Issue by mdesmons** [kittinunf/Fuel#265]
Using Fuel and Fuel-Jackson v1.11.0.
I have a service returning a JSON UserProfile object mapped to a Kotlin class:
`    data class UserProfile(var name:String)
`
If I use Fuel in in async mode, the response gets properly deserialised to a UserProfile object:
```
   url.http_get().responseObject<UserProfile >(){request, response, result ->
           logger.info(result.value.name)
```

Whereas if I use Fuel in blocking mode, the responseObject signature returns a triplet with "result" being typed as Result<Any, FuelError> instead of Result<UserProfile, FuelError>.

Besides, result.value contains a HashMap<String, Any> with the response fields, and not a UserProfile object.

I can't see any reason why the blocking mode would behave differently from the async mode and not deserialize the response as expected?

**Comment by kittinunf** [comment]
This is true! I will open a PR for fixing this.
