### ISSUE TITLE
Use proper package name

### ISSUE THREAD

**Issue by Ribesg** [kittinunf/Fuel#27]
Hi, your project seems cool!

But it doesn't follow package naming standards, so if you don't have any other website, Fuel's package name should be `com.github.kittinunf.fuel` :)

Thanks

**Comment by kittinunf** [comment]
Thanks. I am appreciated that.

Yeah I think at the end, I think I would change the package name.

However, this is a breaking change. Since Kotlin is going to hit 1.0 now, I will clean up everything once and for all when 1.0 is hit.

**Comment by yoavst** [comment]
![](https://pbs.twimg.com/media/CR7E4D7UkAAfA34.png:large)
