### ISSUE TITLE
;ore Detailed explanation for Unexperiencced users

### ISSUE THREAD

**Issue by AleFachini** [kittinunf/Fuel#272]
Hello:
I am very new to android /java and Kotlin. And i find this very long sentences confusing. Can you provide more detailes examples with explanations? 
I am trying to replace Volley with this library, but im struggling to undersetand how to get a simple JSON as string and save it to a variable. wouldbe nice if we have methods explained as in Android Developers.
Yes I am very unexperienced but there  is no one basic tutorial in the main page? In my case i use GSON and Im using RuntimeTypeAdapterFactory for my complex JSON and i will use fuel to get those. 

Im sorry this may not be usefull but i would really like more examples and more detailed explanations, Just asking if that is possible, If i manage to do this work iLL gladly upload my examples.
Regards

**Comment by kittinunf** [comment]
Have you checked out sample folder? Both in Java and Kotlin?

**Comment by kittinunf** [comment]
I am closing this because of the staleness.
