### ISSUE TITLE
Download response empty

### ISSUE THREAD

**Issue by toemat** [kittinunf/Fuel#275]
Trying to use the download file feature but for some reason `string` inside the responseString { } block is always empty _unless_ I put a breakpoint inside the destination { } block.

Am I using this the wrong way or is there a thread timing issue going on?

```kotlin
"http://httpbin.org/ip".httpDownload().destination { response, url ->
    File(this.filesDir, "test.txt")
}.responseString { request, response, result ->
    val (string, error) = result
    string...
}
```

(The file seems to be created and written correctly, but I figured I would use the result/string instead of immediately opening and reading the file, assuming it's supposed to be available.)

**Comment by danshev** [comment]
Hitting this same issue with the `.response { request, response, result ->` handler.  Created [a stackoverflow question](https://stackoverflow.com/questions/48739045/fuel-download-returns-empty-bytes) about it.

**Comment by C06A** [comment]
In order to write the content of the file Fuel need to read it from the body of the response. As a result at the point of responseString(...) the body of the response is actually empty.

I don't know if there is a way to not write content to the file, but then the body will content some wrapping code in addition to file content.

**Comment by markGilchrist** [comment]
@danshev you are right I have a branch in which I have written a failing test that matches what you are saying, I will look in to this further and see if I can find a solution

**Comment by markGilchrist** [comment]
@danshev  I have a pr that fixes this, I am not sure if my approach has other limitation, however I am sure @kittinunf  will soon let me know

**Comment by markGilchrist** [comment]
@toemat This should be resolved as of the latest release, can you comment to indicate if you are happy to close?

**Comment by toemat** [comment]
This is great, thank you for the fix, @markGilchrist 🙏
