### ISSUE TITLE
There is no json post example

### ISSUE THREAD

**Issue by qwertukg** [kittinunf/Fuel#276]
How to add `JSON` body to request and send it? plz add an example of it to readme

And also will be good if u will add `httpGet` (and others) extension to `URL` class

**Comment by medyas** [comment]
I'm trying to accomplish it using java, but not getting the json as expected in the server side. here's my code:

        onCreate Class {
        JSONObject obj = new JSONObject();
        try {
            obj.put("client_uid", client.getUid());
            obj.put("tokenId", refreshedToken);
        }
        catch(Exception e) {
            Toast.makeText(this, "Could not send data", Toast.LENGTH_LONG);
        }


        params = obj.toString();
        postData();
        }


       private void postData() {
        Log.w("Sending data", "sending ");
        Fuel.post("https://itransfo.tk/setToken/").body(params.getBytes()).responseString(new Handler<String>() {
            @Override
            public void failure(@NotNull Request request, @NotNull Response response, @NotNull FuelError error) {
                //do something when it is failure
                Log.w("Error", error);
            }

            @Override
            public void success(@NotNull Request request, @NotNull Response response, String data) {
                //do something when it is successful
                Log.w("success", data);

            }
        });
    }
