### ISSUE TITLE
[Feature] upload file with http-formpost

### ISSUE THREAD

**Issue by Euronames** [kittinunf/Fuel#278]
Hello,
I have an endpoint that takes an http-formpost for a fileupload and i would like to be able to upload to this endpoint using Fuel.
I have tried

```kotlin
         var (_,_,result) = Fuel.upload("${fileConfigProperties.url}/api/file")
                .blob { _, _ -> Blob(file.name, file.size, { file.inputStream })}
                .response(fileUploadResponseDeserializer)
``` 
and i'm getting this response Required request part &#39;file&#39; is not present

I've checked the documentation which makes me believe that this is a feature request as this does not seem possible atm.

**Comment by kittinunf** [comment]
I think it should be included in the later release. Closed as fixed.
