### ISSUE TITLE
Fuel.testMode NetworkOnMainThreadException

### ISSUE THREAD

**Issue by Querschlag** [kittinunf/Fuel#284]
I get the exception above when I configure Fuel for the testMode in my Application class. 

```
Fuel.testMode {
	timeout = 5000
}
```

My code makes the network call in a non-blocking way like so: `"https://foo.com".httpGet().responseString { request, response, result -> }`
I tested with a physical android device (Pixel 1).

**Comment by markGilchrist** [comment]
can you try 
```
Fuel.testMode {
	timeout = 5000
        blocking = false
}
```

**Comment by markGilchrist** [comment]
@Querschlag  did this resolve the issue? can we close this?

**Comment by Querschlag** [comment]
I'm currently unable to test this. I'd say you can close this for now and I will reopen or create a new issue once I encounter this problem again.
