### ISSUE TITLE
Responses not validated after redirect

### ISSUE THREAD

**Issue by cifa** [kittinunf/Fuel#285]
Following a redirect `Response.Success` is returned even if the requested resource does not exist.  Consider the following tests:  
```
    @Test
    fun failsIfRequestedResourceReturns404() {
        val manager = FuelManager()
        val (_, _, result) = manager.request(Method.GET, "http://www.something.cz/dolly").response()

        assertThat(result, `is`(instanceOf(Result.Failure::class.java)))
    }

    @Test
    fun failsIfRedirectedToResourceReturning404() {
        val manager = FuelManager()
        val (_, _, result) = manager.request(Method.GET,
                "http://httpbin.org/redirect-to",
                listOf("url" to "http://www.something.cz/dolly"))
                .header(mapOf("User-Agent" to "Fuel"))
                .response()

        assertThat(result, `is`(instanceOf(Result.Failure::class.java)))
    }
```
While the first one passes as `Result.Failure` is returned as expected the other one fails with 
```
java.lang.AssertionError: 
Expected: is an instance of com.github.kittinunf.result.Result$Failure
     but: <[Success: [B@7e0ea639]> is a com.github.kittinunf.result.Result$Success
```
I believe the issue is the root cause of the issue is line 28 in `RedirectionInterceptor.kt` which simply returns `manager.request(encoding).response().second` instead of submitting the result to subsequent interceptors (i.e. `validatorResponseInterceptor`).

**Suggested solution**
Change line 28 in `RedirectionInterceptor.kt` to
```
next(request, manager.request(encoding).response().second)
```

**Comment by kittinunf** [comment]
Hmm, can you suggest with a PR, and we can continue discussion in there?

**Comment by kittinunf** [comment]
Close with #288
