### ISSUE TITLE
"README.md: Wrong function in example "Specify custom field names for files

### ISSUE THREAD

**Issue by davbrama** [kittinunf/Fuel#289]
https://github.com/kittinunf/Fuel/blob/master/README.md#specify-custom-field-names-for-files
`Fuel.upload("/post").sources { request, url ->
    listOf(
        //DataPart takes a file, and you can specify the name and/or type
        DataPart(File.createTempFile("temp1", ".tmp"), "image/jpeg"), 
        DataPart(File.createTempFile("temp2", ".tmp"), "file2"),
        DataPart(File.createTempFile("temp3", ".tmp"), "third-file", "image/jpeg")
    )
}.responseString { request, response, result ->
    ...
}`
should be:
`Fuel.upload("/post").dataParts { request, url ->
    listOf(
        //DataPart takes a file, and you can specify the name and/or type
        DataPart(File.createTempFile("temp1", ".tmp"), "image/jpeg"), 
        DataPart(File.createTempFile("temp2", ".tmp"), "file2"),
        DataPart(File.createTempFile("temp3", ".tmp"), "third-file", "image/jpeg")
    )
}.responseString { request, response, result ->
    ...
}`

**Comment by kittinunf** [comment]
Close by #292
