### ISSUE TITLE
Kotlin 1.0 Beta Candidate support

### ISSUE THREAD

**Issue by Ribesg** [kittinunf/Fuel#29]
Please update Fuel for Kotlin 1.0 Beta Candidate.

http://blog.jetbrains.com/kotlin/2015/10/kotlin-1-0-beta-candidate-is-out/

**Comment by kittinunf** [comment]
Sure. I am working on it. Thanks :)



—

**Comment by peleteiro** [comment]
Fuel 0.56, using Kotlin 1.0-beta plugins; IntelliJ and Android Studio says classes.jar has an unsupported format.

**Comment by kittinunf** [comment]
@peleteiro I am not sure what is going wrong? Should I clean it and pack another version to see whether it helps?

**Comment by peleteiro** [comment]
@kittinunf I did that and worked. I checked out Fuel code and clean build it.

**Comment by kittinunf** [comment]
Ok I'll do it.

**Comment by kittinunf** [comment]
I have push 0.57 to fix this. Can you try to see whether it helps?

**Comment by peleteiro** [comment]
It worked! Thank you very very much!
