### ISSUE TITLE
responseJson only available in android extention?

### ISSUE THREAD

**Issue by Guppster** [kittinunf/Fuel#290]
I was trying to use the responseJson method as shown in the detailed instructions section of the readme but I couldn't find it. After looking through the repo I realized it is only available for the Android extension of Fuel. 

Is this a mistake or is it suppose to be this way? Either way, it's not clearly represented in the README, which shows the response, responseString, responseJson, and responseObject methods like they are equally available.  

I'm sure many users will be as confused as I was when the method isn't found but stated to exist in the readme.

**Comment by kittinunf** [comment]
Close by his PR #291
