### ISSUE TITLE
Fuel running in a worker thread?

### ISSUE THREAD

**Issue by pablodeafsapps** [kittinunf/Fuel#294]
Hi,
            I come from the 'Retrofit' world and I am used to Rx, i.e. using 'observeOn()' and 'subscribeOn()' to avoid doing too much work in the Main Thread. I know Fuel is compatible with Rx, but my question is: does Fuel run in a worker thread by default?! Or, as I think, it run asynchronously in the Main Thread unless you use the Rx compatible feature?!
            Thanks and regards,

**Comment by kittinunf** [comment]
I think I leave the thread usage to be the responsibility of the client so that you can just use `observeOn` and `subscribeOn` in any threads you desire? Is this working as expected or not?

**Comment by pablodeafsapps** [comment]
Hey! Thanks for your response.
The behavior is the expected when using the Rx feature. I was simply wondering what is the standard approach that Fuel uses; I mean whether it swaps thread for the query or it simply sticks to the main thread. Thanks!

**Comment by kittinunf** [comment]
Ah, in `Fuel` default implementation, it runs on the worker threads by default so you don't have to worry about it. In Android implementation, `Fuel` also calls the callback in the mainThread environment for you automatically.

**Comment by kittinunf** [comment]
I think this issue can be closed :)
