### ISSUE TITLE
Unicode problems

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [kittinunf/Fuel#300]
I'm having problems with accents, on the response I'm getting the unicode value instead of an accent.

Ex original response: "programación"
Ex response: "programaci\u00f3n"

**Comment by kindraywind** [comment]
Hi
I tried with mocked api: https://d82474de-3989-4a29-89d8-6af2d7759262.mock.pstmn.io/uni
and the response looks fine to me
```
<-- 200 (https://d82474de-3989-4a29-89d8-6af2d7759262.mock.pstmn.io/uni?key=value)
                                                      Response : OK
                                                      Length : 13
                                                      Body : (programación)
```

Make sure that the header's Content-Type includes `charset=utf-8` 👍

**Comment by QUIQUELHAPPY** [comment]
I don't understand what's going on. I do get the accent right with your mocked api, but with my site I'm not getting regular accents BUT in the browser I do! look: 
![b13067fff27ab9d80f17b66f886626df](https://user-images.githubusercontent.com/12534357/35947957-8957a5aa-0c6a-11e8-9a38-5c3d5aee941b.png)

I'm using the header with the charset already... 😕 
![2012481a89ffc0c25c97ab3e8569ca01](https://user-images.githubusercontent.com/12534357/35948002-bd417ee0-0c6a-11e8-835f-3662c280b5d6.png)
