### ISSUE TITLE
validatorResponseInterceptor always response FuelError

### ISSUE THREAD

**Issue by babedev** [kittinunf/Fuel#301]
Fuel: `v1.12.0`

I add `validatorResponseInterceptor(200..499)` to `FuelManager`
Should it allow 200 to 499 as valid status code?

I checked `FuelManager` that it add `validatorResponseInterceptor` as new interceptor, but it already has `validatorResponseInterceptor(200..299)`. So it might do the `200..299` before my interceptor and response error.

Here is my code
```kotlin
with(FuelManager.instance) {
    basePath = BuildConfig.BASE_URL

    addResponseInterceptor(validatorResponseInterceptor(200..499))
}
```

```kotlin
"xxx".httpPost()
    .responseObject(...) { _, _, result ->
        // status code is 422
        result.fold({ items ->
             // Should it response here?
        }, { error ->
             // Always get error         
        })
    }
```

**Comment by kittinunf** [comment]
Yeah, if you really need (200..499), you need to remove the existing one first. Then, add your custom one. Does it make sense to you?

**Comment by babedev** [comment]
Should it replace the old one? Because there is no need to have multiple `validatorResponseInterceptor`.

**Comment by kittinunf** [comment]
Hmm, why do you want to replace 200.299 ?

**Comment by babedev** [comment]
I want to allow 200..499. But it failed because it has `validatorResponseInterceptor(200..299)` as default validator. 
Would it better if new `validatorResponseInterceptor` replace the existing one?

**Comment by kittinunf** [comment]
Yeah, but 200..499 won't work. Because 300...499 shouldn't be treated as Success, should we?

**Comment by babedev** [comment]
Um.... yes, you are right. I have scenario which I need to get JSON response body from status 4xx.
So I might go this way.

```kotlin
{ _, res, result ->
   result.fold({
      // Success
   }, { 
      // Deserialise String(res.data)
   })
}
```

Should we have JSON deserialiser for error case?

**Comment by kittinunf** [comment]
True ... I think we should do that. Sound like a good item for another PR.

I think we could improve in this block.

https://github.com/kittinunf/Fuel/blob/0001c44efe9bf1389ba742292a45b62837723801/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Deserializable.kt#L69-L73

**Comment by kittinunf** [comment]
Yeah. I think I could find sometime this weekend to tackle this

**Comment by athasamid** [comment]
anyone solve this proble, or there is patch or solution for this issue?

**Comment by SleeplessByte** [comment]
The solution is in this issue: remove the old response interceptor and add it back with the full range.
