### ISSUE TITLE
android 4.4- API Call send callback in on failure() but in other android version it works fine

### ISSUE THREAD

**Issue by smi22** [kittinunf/Fuel#305]
Fuel.get(Constants.defaultChannelURL).responseString(new Handler<String>() {
            @Override
            public void success(Request request, Response response, String s) {
                if (response.getStatusCode() == 200) {
                    try {
                        String result = s;
                        Log.d(SplashActivity.this.getClass().toString(), "Fuel response = " + result);
                        DefaultChannel defaultChannel = new Gson().fromJson(result, DefaultChannel.class);
                        if (defaultChannel != null) {
                            if (defaultChannel.getChannels() != null) {
                                List<Channel> list = defaultChannel.getChannels();
                                defaultChannels = defaultChannel.getChannels();
                                syncWithFirebase(list);
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        AToast.error(SplashActivity.this, e.getMessage().toString());
                    }
                }
            }
}
            @Override
            public void failure(Request request, Response response, FuelError fuelError) {
                fuelError.printStackTrace();
                Log.d(SplashActivity.this.getClass().toString(), "Fuel failure");
                AToast.error(SplashActivity.this, fuelError.getMessage().toString());
            }
        });

**Comment by babedev** [comment]
What is an error from `printStackTrace`?
