### ISSUE TITLE
How to get response body on error?

### ISSUE THREAD

**Issue by jurgel** [kittinunf/Fuel#314]
If the API return status code 400 (Bad Request) with some message on the body, how do I get the body from FuelError?

```kotlin
Fuel.post(url).body(jsonData).responseObject<JsonObject> { request, response, result ->
    Log.v(TAG, request.toString())
    Log.v(TAG, response.toString())
    Log.v(TAG, result.toString())

    val (json, error) = result
    if (json != null) {
        // handle success
    } else {
        // json is null, how to get the response body?
    }
}
```

Example message:
```json
{"code":201,"result":"invalid credentials"}
```

I want to parse the code and result text, but I can't even get the response body.

**Comment by yoavst** [comment]
try `response.data`. It will return `ByteArray`.

**Comment by jurgel** [comment]
I thought it's inside error object, I should check it first, :smile: 
thanks a lot man.
