### ISSUE TITLE
Why is there a JVM version and an Android version?

### ISSUE THREAD

**Issue by alexnix** [kittinunf/Fuel#321]
This is somehow confusing since Android is actually a JVM library. There fore "JVM version" should work for Android too.

**Comment by kittinunf** [comment]
It works on Android as well, however, if you use `Android`, you will benefit from Android specific stuff, for example, you call back will run on Main thread automatically.

In short, `JVM` target usage outside Android context, meanwhile `Android` aims to support usage under Android development.
