### ISSUE TITLE
Headers in Fuel

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [kittinunf/Fuel#322]
For me using `url.http...().headers().response...()` will work fine, but it will not send the actual headers in the request. They are displayed when logging and therefore also stored in the `request` parameter, but they do not work, i.e. they are not sent with the request.

**Comment by kittinunf** [comment]
Can you give more info about this? I think it should be fine with the current implementation. I will close this for now but if you think this is an issue still, feel free to come back and give more info.
