### ISSUE TITLE
blocking mode does not work in Activity but works in Service (Android)

### ISSUE THREAD

**Issue by tyaslab** [kittinunf/Fuel#328]
The documentation states that

> You can also wait for the response. It returns the same parameters as the async version, but it blocks the thread. It supports all the features of the async version.

It works perfectly in **Service** but it doesn't work in **Activity**. I have tried in fresh new Android Project file and it still doesn't work (except in Service).

The script is

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val (_, response, _) = Fuel.get("http://example.com").responseString()
        Log.d(TAG, String(response.data))
        Log.d(TAG, String(response.statusCode))
    }
}

```

The *Log.d* for response.data doesn't return anything but response.statusCode returns **-1**

Did I do it wrong? Or is this a bug? How to do blocking request in Fuel in best practice? Thank you.

**Comment by yoavst** [comment]
Yea, Android blocks you from having a network request on main thread.
