### ISSUE TITLE
Fuel http request identified as "Browser Client" by Spring Boot

### ISSUE THREAD

**Issue by ryanm35** [kittinunf/Fuel#333]
I am making api calls to a spring boot service and whatever user agent Fuel is using is being identified as a browser client by spring boot. This causes undesirable behavior. I have not this problem when using Apache HttpClient directly.

**Comment by kittinunf** [comment]
It is because of the header? I would love to see how spring boot identify whether the client is a browser client, do you have more info on that?

**Comment by ParkerK** [comment]
@ryanm35 have you tried setting custom headers? https://github.com/kittinunf/Fuel/wiki/Quick-Glance-Usage#headers

**Comment by SleeplessByte** [comment]
You (@ryanm35) probably only need to override the `User-Agent` header, which is, unfortunately, often used to detect "clients" and is leaky as best.

**Comment by kittinunf** [comment]
Sound like we can close this. Please reopen if you don't think it can be done.

Thanks @ParkerK and @SleeplessByte for support ❤️
