### ISSUE TITLE
Could not resolve com.github.kittinunf.launcher_icon:launcher_icon-android:1.12.0.

### ISSUE THREAD

**Issue by SeppPenner** [kittinunf/Fuel#336]
When I try to add the following lines to my build.gradle file:

 ```gradle
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon:1.12.0'
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon-android:1.12.0'
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon-livedata:1.12.0'
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon-rxjava:1.12.0'
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon-gson:1.12.0'
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon-jackson:1.12.0'
    implementation 'com.github.kittinunf.launcher_icon:launcher_icon-moshi:1.12.0'
```

I get the following error:

> Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.kittinunf.launcher_icon:launcher_icon-android:1.12.0.
> 
> Could not resolve com.github.kittinunf.launcher_icon:launcher_icon-android:1.12.0.
> Required by:
>     project :app
>  > Could not resolve com.github.kittinunf.launcher_icon:launcher_icon-android:1.12.0.
>     > Could not get resource 'https://jitpack.io/com/github/kittinunf/launcher_icon/launcher_icon-android/1.12.0/launcher_icon-android-1.12.0.pom'.
>           > Could not GET 'https://jitpack.io/com/github/kittinunf/launcher_icon/launcher_icon-android/1.12.0/launcher_icon-android-1.12.0.pom'. Received status code 401 from server: Unauthorized

**Comment by kittinunf** [comment]
Hmm, what is `launcher_icon`?

**Comment by SeppPenner** [comment]
I think I found the issue... I somehow copied the launcher_icon as string to all of the lines that originally were the following:

```gradle
implementation 'com.github.kittinunf.fuel:fuel:1.12.0'
implementation 'com.github.kittinunf.fuel:fuel-android:1.12.0'
implementation 'com.github.kittinunf.fuel:fuel-livedata:1.12.0'
implementation 'com.github.kittinunf.fuel:fuel-rxjava:1.12.0'
implementation 'com.github.kittinunf.fuel:fuel-gson:1.12.0'
implementation 'com.github.kittinunf.fuel:fuel-jackson:1.12.0'
implementation 'com.github.kittinunf.fuel:fuel-moshi:1.12.0'
```

But don't ask me why. Can be an IDE error, too, maybe...

**launcher_icon.png** is a file I use to show on app startup. But nevermind, was a stupid copy-paste error...
