### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.kittinunf.fuel:fuel-rxjava:1.12.1.

### ISSUE THREAD

**Issue by Kudzai3** [kittinunf/Fuel#338]
Happening for all dependencies listed below today.

implementation 'com.github.kittinunf.fuel:fuel-rxjava:1.12.1'
implementation 'com.github.kittinunf.fuel:fuel-gson:1.12.1'
implementation 'com.github.kittinunf.fuel:fuel-jackson:1.12.1'
implementation 'com.github.kittinunf.fuel:fuel-moshi:1.12.1'

**Comment by kittinunf** [comment]
Let's close this, as there is no response from the reporter.
