### ISSUE TITLE
unparsed Json with POST in server side

### ISSUE THREAD

**Issue by medyas** [kittinunf/Fuel#340]
hi, im new to this library and just started using it and trying to send a post request with Json data to a server. i managed to do that but the received data cannot be parsed as json. here is my code:

I'm trying to accomplish this using java, but not getting the json as expected in the server side. here's my code:

```
    onCreate Class {
    JSONObject obj = new JSONObject();
    try {
        obj.put("client_uid", client.getUid());
        obj.put("tokenId", refreshedToken);
    }
    catch(Exception e) {
        Toast.makeText(this, "Could not send data", Toast.LENGTH_LONG);
    }


    params = obj.toString();
    postData();
    }


   private void postData() {
    Log.w("Sending data", "sending ");
    Fuel.post("https://itransfo.tk/setToken/").body(params.getBytes()).responseString(new Handler<String>() {
        @Override
        public void failure(@NotNull Request request, @NotNull Response response, @NotNull FuelError error) {
            //do something when it is failure
            Log.w("Error", error);
        }

        @Override
        public void success(@NotNull Request request, @NotNull Response response, String data) {
            //do something when it is successful
            Log.w("success", data);

        }
    });
}

i get this data in the server and can't parse it to json. i'm using nodejs and firebase cloud function in the server side.
{"{\"client_uid\":\"dfgdhghg\",\"tokenId\":\"jhgfh:ghghggrglSA-iCURvtqJChEYd27smRMJ-jjhgjh\"}":""}
```

any help. and Thank you.

**Comment by ParkerK** [comment]
try `responseJson` instead of `responseString` if you're expecting a JSON result

**Comment by medyas** [comment]
already found a solution, i change everything to kotlin and it worked fine.

**Comment by rip32700** [comment]
How exactly did you solve this? I have the same problem like you.

`     val data = JSONObject()
        data.put("email", "blabla")
        data.put("password", "bla")

        Log.d(TAG, data.toString())

        // send the HTTP request
        url
            .httpPost()
            .body(data.toString())
            .responseJson { _, _, result ->
                val (data, error ) = result
                if (error == null) {
                    this.token = data?.obj()?.getString("token")
                } else {
                    Log.e(TAG, "Error while retrieving token: $error")
                }
            }`

**Comment by medyas** [comment]
```
try {
            obj.put("client_uid", uid)
            obj.put("tokenId", refreshedToken)
        } catch (e: Exception) {
            Toast.makeText(this, "Could not send data", Toast.LENGTH_LONG).show()
}
postData(obj.toString())

private fun postData(p:String?) {
        Log.w("Sending data", "sending ")
        "/setToken/".httpPost().body(p!!)
                .responseString { request, _, result ->
                    Log.w("Request", result.toString())
                    //update(result)
                }
}
```

and for my server, i was using nodeJs, so just used these : 
```
app.use(bodyParser.json()); // for parsing application/json
app.use(bodyParser.urlencoded({ extended: true, inflate: true })); // for parsing application/x-www-form-urlencoded
```
