### ISSUE TITLE
Can't add multiple headers with the same name (cookies)

### ISSUE THREAD

**Issue by Fibonacci-** [kittinunf/Fuel#343]
The code:

```
val (request, response, result) = reqUrl.httpGet()
                        .header(Pair("Cookie", "val1=x"),
                                Pair("Cookie","val2=y"),
                                Pair("Cookie","val3=z"))
                        .responseString()
```

Expected functionality:

All cookies are included in request

Actual functionality:

Only the last Pair with val3 is included in the request

This happens because, in Request.kt line 28, the headers variable is a MutableMap, instead of perhaps an ArrayList of Pairs or a similar datatype.

Multiple headers with the same name is allowed in the [HTTP spec, section 4.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

**Comment by ParkerK** [comment]
>Multiple message-header fields with the same field-name may be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. 

From my understanding, I think that means you need to send the values as 
`Pair("Cookie", "val1=x,val2=y,val3=z"),` ?

**Comment by markGilchrist** [comment]
@Fibonacci-  I am rereading this and feel that this issue is not resolved, if you can tell me how you want the output of the headers to look I will raise a pr and make the changes

**Comment by Fibonacci-** [comment]
@markGilchrist No problem - [here's a working example](https://github.com/Fibonacci-/CWCompat/blob/master/app/src/main/java/com/helwigdev/cwcompat/LoginActivity.kt#L304) of this same scenario written out with the OkHttp library (please excuse my code), and here's what I'd like it to look like in plain HTTP:

```
GET  HTTP/1.1
Host: example.com
Cookie: val1=x
Cookie: val2=y
Cookie: val3=z
```

I think if headers in Request.kt was an ArrayList or similar instead of a Map, it would solve the problem - but I'm sure there's more refactoring that needs to go into it. Thank you!

**Comment by markGilchrist** [comment]
@Fibonacci-  
if as a consumer you could do 

```
.header(Pair("Cookie", listOf("val1=x","val2=y",val3=z"))

```

would this be a suitable?

**Comment by markGilchrist** [comment]
I think I have a solution that would give the following output

`Cookie: [val1=x, val2=y, val3=z]`

is that a satisfactory outcome or do you insist it has to be in the format?

```
Cookie: val1=x
Cookie: val2=y
Cookie: val3=z
```

**Comment by Fibonacci-** [comment]
That works for me - it's what the spec defines. I think the server I'm working with will throw a fit, but that's an issue with that specific server and not with Fuel.

**Comment by markGilchrist** [comment]
could you please look at https://github.com/kittinunf/Fuel/pull/393

please check that the unit test produces the results you are looking for and please comment on any concerns you may have

thank you for taking the time raising this issue

**Comment by SleeplessByte** [comment]
As per the spec: https://tools.ietf.org/html/rfc2616#section-4.2

```
   Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma. The order in which header fields with the same
   field-name are received is therefore significant to the
   interpretation of the combined field value, and thus a proxy MUST NOT
   change the order of these field values when a message is forwarded.
```

This can be translated into a server *MUST* accept `Cookie: val1=x, val2=y, val3=z` (@Fibonacci-). @markGilchrist those brackets shouldn't be present, but I think you just intended to show it would be a list.

However from experience I know that this format:
```
Cookie: val1=x
Cookie: val2=y
Cookie: val3=z
```

is not accepted by ALL nodes out there (especially older software/nodes will simply drop all but the first or drop all but the last).
