### ISSUE TITLE
[Bug] Request GET works differently between kotlin code and curl

### ISSUE THREAD

**Issue by j-elmer123** [kittinunf/Fuel#346]
this is my code to get data from URL
```kotlin
Fuel.get("http://my.host.ip/api/task/", null).responseJson() { request, response, result ->
    request.header("Content-Type" to "application/json")
    request.header("Authorization" to "Token xxxxxxxx")
    result.fold(success = { json ->
        tasks = json.array()
    }, failure = { error ->
        Toast.makeText(this, error.message, Toast.LENGTH_LONG).show()
    })
}
```
always saying unauthorized.

When I use cURL from `request.cUrlString()`
```cURL
curl -i -H "Accept-Encoding:compress;q=0.5, gzip;q=1.0" -H "Content-Type:application/json" -H "Authorization:Token xxxxxxxx" http://my.host.ip/api/task/
```
I get the JSON data from that specific API after using cURL.

**Comment by kittinunf** [comment]
That was not the correct way of using `Fuel` in the `{ request, response, result ->` that is the request `after` the connection has been made. In your example, you configure the header *before* the connection is made.

Consider something like
``` Kotlin
Fuel.get("http://my.host.ip/api/task/").header("foo", "bar") { request, response, result ->
}
```
in order to achieved you desired result.

**Comment by j-elmer123** [comment]
Oh, now I understand how to properly use it. thank you.

**Comment by BrunoVernay** [comment]
For the record, I think the header should be "Accept: ..." instead of "Content-Type" : https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation
