### ISSUE TITLE
Wrong way of reacting to the coroutine being cancelled

### ISSUE THREAD

**Issue by mtopolnik** [kittinunf/Fuel#351]
[This code](https://github.com/kittinunf/Fuel/blob/c9f1e871774ddcf07a0da6687f85ff8d3bed1704/fuel-coroutines/src/main/kotlin/com/github/kittinunf/fuel/coroutines/Coroutines.kt#L19):

```kotlin
suspendCancellableCoroutine { continuation ->
    continuation.invokeOnCompletion {
        if (continuation.isCancelled) {
            continuation.cancel()
        }
    }
    ...
```

checks if a continuation is cancelled, only to do nothing but cancel it again. Instead this should be the place to cancel the HTTP request.

**Comment by kittinunf** [comment]
Ah this is something that we might have overlooked. Your suggestion makes sense to me. Would you mind open a PR for this?
