### ISSUE TITLE
Fuel.upload with form data not sending form data 

### ISSUE THREAD

**Issue by InvertedX** [kittinunf/Fuel#352]
Fuel Upload supports optional form data parameter.i passed this parameter and multipart data to upload , but only file upload works form data not associated with request

```kotlin 

 val formData = listOf(
                "title" to "test",
                "desc" to "test")

        FuelRequest = Fuel.upload(URL, method = Method.POST, parameters = formData)
                .dataParts { request, url -> listOf(DataPart(File(FILE_URL), "file")) }

```
i logged request object but it only contains.
BTW if we pass empty data part array formdata will be submitted 
 
this is what request obj look like 

> "Body : --163773469cc
                                                                                   Content-Disposition: form-data; name="file"; filename="ydu.mp4"
                                                                                   Content-Type: 
 ������ftypmp42��������is

and without file (empty datapart array)

>  -"Body : --1637736aeab
 Content-Disposition: form-data; name="title"
 Content-Type: text/plain
                                                                                   
> test
                                                                                
> --1637736aeab
> Content-Disposition: form-data; name="desc"
Content-Type: text/plain
                                                                                   
>test
 --1637736aeab--
  "
"Headers : (3)"
Accept-Encoding : compress;q=0.5, gzip;q=1.0
Content-Type : multipart/form-data; boundary=1637736aeab

**Comment by ParkerK** [comment]
It's because you're not passing the `formData` value properly. It's `param` not `parameters` :)

It should be `Fuel.upload(... param= formData)`

**Comment by jahirfiquitiva** [comment]
@ParkerK Actually, you're wrong. Check [this](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/Fuel.kt#L83)

**Comment by InvertedX** [comment]
yeah @jahirfiquitiva is correct . i tried multiple time but nothing works

**Comment by markGilchrist** [comment]
@jahirfiquitiva  please change 

`.dataParts { request, url -> listOf(DataPart(File(FILE_URL), "file")) }`

to

`.dataParts { request, url -> listOf(DataPart(File(FILE_URL), type = "file")) }`
