### ISSUE TITLE
function "Request.awaitResponse" in fuel-coroutines cannot catch NullPointerException while response is null

### ISSUE THREAD

**Issue by not3** [kittinunf/Fuel#353]
sample code
```kotlin
Fuel.post("http://www.baidu.com").timeoutRead(100)
  .awaitResponse().third.fold({ data ->
    response().end(Buffer.buffer(data))
  }, { error ->
    response().apply {
      statusCode = 500
      end(error.message)
    }
  })
```
debug infomation
![fuel debug info](https://user-images.githubusercontent.com/211266/40274944-5a9a4e60-5c16-11e8-9362-d9ae1ca1e0ab.png)

**Comment by markGilchrist** [comment]
I have an open pr which I think will fix this

https://github.com/kittinunf/Fuel/pull/369

all suggestions welcome

**Comment by kittinunf** [comment]
This should be closed by the latest version. Feel free to reopen it, if it doesn't.
