### ISSUE TITLE
How to get the JSON object response from FuelError object in failure response?

### ISSUE THREAD

**Issue by chaitanya-vanapamala** [kittinunf/Fuel#357]
If user sends a bad request, Im sending json object {"status" : "fail"}, But from error object im unable to get the json object. Please help me.

**Comment by markGilchrist** [comment]
can you share the code you are using?

**Comment by lucasvalenteds** [comment]
The `Response` object has a `data` property which represents the response body. It can be decoded using `fuel-jackson`, `fuel-gson` or any parser library you want.

If I understood the issue correctly, the API returns status code 400 and a JSON object with the field `status` in the body. If that is the case, the code below should work.

```kotlin
data class ApiResponseBody(val status: String)

object ApiResponseDeserializer : ResponseDeserializable<ApiResponseBody> {
    override fun deserialize(bytes: ByteArray) =
        jacksonObjectMapper().readValue<ApiResponseBody>(bytes)
}

fun main(args: Array<String>) {
    val url = "http://your.api.com/"
    val (_, response, _) = Fuel.get(url).responseObject(ApiResponseDeserializer)

    val apiResponseBody = ApiResponseDeserializer.deserialize(response.data)
    println(apiResponseBody.status) // "fail"
    println(response.statusCode) // 400
}
```

**Comment by kittinunf** [comment]
Close for inactivity, feel free to reopen this if you have any further question.
