### ISSUE TITLE
how to pass use array parameter in a get request?

### ISSUE THREAD

**Issue by xinwo** [kittinunf/Fuel#360]
for example,
http://xx.xxx..x?a[]=1&a[]=2
usually means parameter a is an array, having 2 values - 1 and 2.

when i do below
val a = arrayOf(1, 2)
uri.httpGet(listOf("a" to a))

and check the log on server, it turns out something like below
a=%5BLjava.lang.String%3B%4095f9361

does that mean fuel doesn't support array parameter?

**Comment by kittinunf** [comment]
Let's close this!
