### ISSUE TITLE
The response.data is empty when use .responseObject()

### ISSUE THREAD

**Issue by lokielse** [kittinunf/Fuel#362]
https://github.com/kittinunf/Fuel/blob/4e75b338b7f6c6576b206df91aca5637ac2b0e74/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Response.kt#L29-L35

It can log the response body by using `response()` or `responseString()`, but not `responseObject()`

`responseObject` will print

```
    Response : OK
    Length : -1
    Body : ((empty))
    Headers : (13)
    Cache-Control : [no-cache, private]
    Connection : [keep-alive]
    Content-Type : [application/json]
    Date : [Sun, 10 Jun 2018 09:55:28 GMT]
    Server : [nginx]
    ...
```

It it a bug? how to print the response body when use `responseObject()`?

**Comment by kittinunf** [comment]
When you use `responseObject` the response body should be consumed and decoded with the decode library of your choice, can you tell me why you want to see the response data again? You object that was decoded is not done correctly?

**Comment by lokielse** [comment]
OK, I got it. I just want copy the response json to create a model class. Maybe I should use the cURL debug info.
