### ISSUE TITLE
Upload Images 400 Error

### ISSUE THREAD

**Issue by amorenew** [kittinunf/Fuel#363]
I have this web service 
Url:   http://menatservice.menatbb.com/MenaServiceCommon.svc/TestUploadImage
Form Data:
```
ListId : 10
ListType : 1
MenaImage:  >> put any image
```

I tried

     
    val formData = listOf("ListId" to moduleId, "ListType" to moduleType,
               "MenaImage" to listOf{images[0].file.readBytes()})
      return Constants.TestUploadImage.httpUpload(Method.POST, formData)
 

but I got 400 bad request error while in Postman it is working as the image below
what should I do to make it work
![image](https://user-images.githubusercontent.com/2842459/41221756-aab17be0-6d6d-11e8-8947-1bf502187ab9.png)

**Comment by lucasvalenteds** [comment]
Hi @amorenew. The code below should do what you need. Be aware that it depends on `fuel-jackson` module, but you can easily change it to `fuel-gson` or even use `responseString` instead of `responseObject` and throw away `ApiResponse` and `ApiResponseDeserializer`.

```kotlin
data class ApiResponse(
        val Isvalid: Boolean,
        val ResponseCode: String,
        val ResponseMessage: String)

object ApiResponseDeserializer : ResponseDeserializable<ApiResponse> {
    override fun deserialize(content: String) =
            jacksonObjectMapper().readValue<ApiResponse>(content)
}

fun main(args: Array<String>) {
    val apiUrl = "http://menatservice.menatbb.com/MenaServiceCommon.svc/TestUploadImage"
    val basicParameters = listOf("ListId" to 10, "ListType" to 1)
    val image = Paths.get("/home/lucas/10524730.jpeg").toFile()

    val (_, _, result) = Fuel.upload(path = apiUrl, parameters = basicParameters)
            .dataParts { _, _ -> listOf(DataPart(image, "MenaImage", "image/jpeg")) }
            .responseObject(RoutingSampleTest.ApiResponseDeserializer)

    result.fold({ data ->
        println(data.Isvalid) // true
        println(data.ResponseCode) // "111"
        println(data.ResponseMessage) // "Success"
    }, { error ->
        println("An error happened: ${error.message}")
    })
}
```
