### ISSUE TITLE
Coroutine API deprecation as of v.0.23.0

### ISSUE THREAD

**Issue by raharrison** [kittinunf/Fuel#368]
The current version of Fuel relies on Kotlin coroutines 0.22.5, the latest being 0.23.4 as of writing.

0.23.0 brought some quite big changes and Fuel will currently break when using this version.

https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md#version-0230

In `Coroutines.kt` we make use of `CancellableContinuation.invokeOnCompletion` which is now deprecated (interestingly on my machine this method no longer exists). It sounds like the semantics surrounding this were changed anyway which may be causing other issues.

From the docs it looks like it needs to be replaced with `invokeOnCancellation` instead. There are a few other outstanding issues raised for coroutines so maybe we can merge this in with one of those.

**Comment by markGilchrist** [comment]
@raharrison I am working on a PR as you know I am happy to make these changes in the pr

**Comment by kittinunf** [comment]
I think this is a really good idea! Thanks for the PR.

**Comment by markGilchrist** [comment]
@raharrison  are you happy for me to close this issue following pr #369 ?

**Comment by raharrison** [comment]
I have been waiting on a new release of the lib so haven't done any testing yet.

@kittinunf Any chance of a version bump?

**Comment by kittinunf** [comment]
I've been planning to merge the #373 then releasing the new version. If you are not in a heavy rush, do you think it is reasonable for that to be done? 🙏

**Comment by raharrison** [comment]
Yeah sure, no rush.

**Comment by raharrison** [comment]
Closed by #369
