### ISSUE TITLE
Automatic redirection on unsafe method POST with 302 response

### ISSUE THREAD

**Issue by genevieveBock** [kittinunf/Fuel#375]
Hi, 

I send a POST request on an URL that returns a 302 (Found) response, and Fuel automatically follows the redirect and sends a POST request again. 
The problem is that the redirect URL sent by the API is not an endpoint on which I should execute a POST again, but one I should send a GET request on to obtain the result of the first POST.
Doing a POST on that URL, like Fuel is doing gives me a 404.

According to the HTTP spec, HTTP clients should not automatically follow redirects on POST requests with another POST, since POST are not safe requests (they have side effects).
I know that the redirection can be disabled globally using ```FuelManager.instance.removeAllResponseInterceptors()```, but is there a way to make Fuel follow the redirect with a GET?

```kotlin
fun main(args: Array<String>) {
    "http://www.mocky.io/v2/5b3e89273000003a06abc730"
        .httpPost()
        .responseString()
}
```

With this function, "http://www.mocky.io/v2/5b3f83443400002b00001b31" POST responds with 302 (Found) and the location [http://www.mocky.io/v2/5b3f8320340000c809001b30]. The following redirect's response status code is 200 (OK). 
I do use a different API, in my case the redirect responds with a 404 on POST request.

**Comment by genevieveBock** [comment]
Thank you for your comment.
I tested your patch and Fuel still follows the redirect with a second POST request. (It does not fix the redirect.)

**Comment by SleeplessByte** [comment]
#388 fixes this and redirects a 302 with `GET`
