### ISSUE TITLE
About Line Notify (Notification) 

### ISSUE THREAD

**Issue by bosskanaka** [kittinunf/Fuel#383]
plese help me T__T
I got Promblem i want to know how to Post data with Fuel (kotlin) to match Line Notify Request 

https://notify-bot.line.me/doc/en/
POST : https://notify-api.line.me/api/notify
![13](https://user-images.githubusercontent.com/35513325/42568186-7a498714-8536-11e8-9e53-b5cf90cb9aa7.PNG)
![14](https://user-images.githubusercontent.com/35513325/42568187-7a89cc5c-8536-11e8-9370-222e92826581.PNG)
![15](https://user-images.githubusercontent.com/35513325/42568189-7acc45d2-8536-11e8-8537-b6a37bcf55b5.PNG)
![12](https://user-images.githubusercontent.com/35513325/42568190-7b02d9bc-8536-11e8-993b-54c9cdb29a35.PNG)

**Comment by kittinunf** [comment]
I think you should try to take a look at how Fuel does post request. https://github.com/kittinunf/Fuel#post
