### ISSUE TITLE
Fuel Coroutines Failing on Android with NetworkOnMainThreadException after upgrade

### ISSUE THREAD

**Issue by avaitla** [kittinunf/Fuel#386]
Hello Team,

I have encountered issues trying to upgrade my fuel version in my Android App, and would like to see if this is related to the fuel/coroutines package or to my own incorrect usage of coroutines within android.

The app worked great but now breaks with an android.os.NetworkOnMainThreadException when I make the following changes:

    1. Fuel Version Bump: v1.13.0 -> v1.14.0
    2. Coroutines Version Bump: v0.22.5 -> v0.23.4
    3. Replace `awaitObject` with `awaitObjectResponse`

I've created a simple repository to reproduce the issue here: https://github.com/avaitla/coroutinesissue
It has two branches:

    good_v1.13.0 - uses fuel v1.13.0 and coroutines v0.22.5
    broken_v1.14.0 - uses fuel v1.14.0 and coroutines v0.23.4

See the diff that breaks things here:

	https://github.com/avaitla/coroutinesissue/commit/cba42a68498b217ce48dfdbc1abf7d279558d96f

The main activity class is here:

	https://github.com/avaitla/coroutinesissue/blob/good_v1.13.0/app/src/main/java/com/avaitla16/coroutinesissue/MainActivity.kt

I've attached a screen shot from the good_version branch:

<img width="393" alt="success_fuelv1 13 0_coroutinesv0 22 5" src="https://user-images.githubusercontent.com/841497/42729678-3fd1a212-87a5-11e8-920b-fee053bc9860.png">

Here is the screen shot from the bad_version branch:

<img width="400" alt="failure_fuelv1 14 0_coroutinesv0 23 4" src="https://user-images.githubusercontent.com/841497/42729679-440ae8b6-87a5-11e8-96d2-0356794778a8.png">

Thanks for your time!

**Comment by avaitla** [comment]
I have noticed that replacing the old code here:

    fun makeRequest() = launch(UI) {
        val result = getData()

        when (result) {
            is Result.Failure -> {
                val ex = result.getException()
                Toast.makeText(this@MainActivity, "Failure: $ex", Toast.LENGTH_LONG).show()
            }

            is Result.Success -> {
                val data = result.get()
                Toast.makeText(this@MainActivity, "Success: $data", Toast.LENGTH_LONG).show()
            }
        }
    }

With the following (delegating to the commonpool) allows the app to work:

    fun makeRequest() = launch(CommonPool) {
        val result = getData()

        launch(UI) {
            when (result) {
                is Result.Failure -> {
                    val ex = result.getException()
                    Toast.makeText(this@MainActivity, "Failure: $ex", Toast.LENGTH_LONG).show()
                }

                is Result.Success -> {
                    val data = result.get()
                    Toast.makeText(this@MainActivity, "Success: $data", Toast.LENGTH_LONG).show()
                }
            }
        }
    }

Is this the appropriate way to use coroutines / fuel api within an android app?

**Comment by markGilchrist** [comment]
@avaitla  thank you for taking the time to raise such a well written issue, I am looking at this now

**Comment by avaitla** [comment]
Thank you @markGilchrist. This change will make our async code much cleaner to write as the caller will not need to switch between two async pools.

**Comment by raharrison** [comment]
I don't think this is the way to go. Even though it might seem like a bit more code, explicitly defining the pool and then switching to the UI thread follows the overall coroutine philosophy - a.k.a concurrency is explicit

Point being that the library is now enforcing the usage of CommonPool to perform async operations, this isn't something that should be abstracted away as from a usage perspective the developer should know what pool is being utilised at all times - especially for blocking operations like this. In larger apps it's highly likely that a dedicated pool will be used, as blocking the CommonPool can have adverse impacts.

**Comment by markGilchrist** [comment]
@raharrison I hear what you say and I think that you have raised a very good point

would you think that it would be suitable to add default arguments to all the coroutine functions such that the consumer of the library can specify which pool the function call is made on?

or do you feel that everyone should consume the code as per you comment above.

I would be happy to update my pr with an extra argument for the scope?

**Comment by markGilchrist** [comment]
https://github.com/kittinunf/Fuel/pull/387

**Comment by markGilchrist** [comment]
#387  is now merged, let me know when you are happy to close this issue?

**Comment by avaitla** [comment]
Thanks Mark. Please close it.
