### ISSUE TITLE
Test cases pass incorrectly with Fuel Library (including assert(False))

### ISSUE THREAD

**Issue by avaitla** [kittinunf/Fuel#389]
I have created a very simple test case here where assertions raised in a fuel callback don't fail the running test with proper logs or exit code (full repo here: https://github.com/avaitla/coroutinesissue/blob/broken_tests/app/src/test/java/com/avaitla16/coroutinesissue/ExampleUnitTest.kt)

    package com.avaitla16.coroutinesissue

    import com.github.kittinunf.fuel.Fuel
    import com.github.kittinunf.fuel.core.DefaultEnvironment
    import com.github.kittinunf.fuel.core.FuelManager
    import org.junit.Test

    class ExampleUnitTest {
        init {
            // Required otherwise Fuel fails with 'Method getMainLooper in android.os.Looper not mocked'
            FuelManager.instance.callbackExecutor = DefaultEnvironment().callbackExecutor
            Fuel.testMode()
        }

        @Test
        fun addition_isCorrect() {
            Fuel.get("https://www.httpbin.org/uuid").responseString { _, _, msg ->
                println("Demonstrate Blocking by Sleeping...")
                Thread.sleep(5000)
                println("Woke from Sleeping...")

                assert(true)
                print("Assert True Passes")

                assert(false)
                print("Assert False Passes")
            }
        }
    }

The only dependency are (however the android dependency isn't needed to reproduce the problem):

    implementation "com.github.kittinunf.fuel:fuel:1.14.0" //for JVM
    implementation "com.github.kittinunf.fuel:fuel-android:1.14.0" //for JVM

Now when I run the test case I see the output with green output and exit code zero instead of red output and status code 1:

    Demonstrate Blocking by Sleeping...
    Woke from Sleeping...
    Assert True Passes
    Process finished with exit code 0

<img width="1081" alt="error_updates" src="https://user-images.githubusercontent.com/841497/42786297-4579c6aa-891b-11e8-9ae8-ba102364d3d4.png">

**Comment by avaitla** [comment]
To work around this, I am using setting a variable and waiting on a CountDownLatch to handle the callback results.

**Comment by markGilchrist** [comment]
@avaitla  I feel this is to do with the way you test has been written not the implementation of the library.

 If you invert the code as in assert(false) then the test does nothing

I am not sure that this is a Fuel issue

**Comment by avaitla** [comment]
Gotcha, yeah just wanted to see if there was a better way to test inside the callback. If not using a latch to wait on call back is fine. Thanks @markGilchrist
