### ISSUE TITLE
Upload list of files as single element in multipart body

### ISSUE THREAD

**Issue by C06A** [kittinunf/Fuel#390]
See the issue https://github.com/kittinunf/Fuel/issues/169, which seams try to get the same, but was closed before somebody give the solution.

I tried solution in that issue, but the resulting multipart body still contains separate part for each file. The name of the parts are "files1", "files2", etc.
What I need (and seams the originator of that topic) the multipart with single part named "files" and containing the list of files.

How can we do THAT?

**Comment by markGilchrist** [comment]
would it be possible for you to elaborate on this issue, if you can give me a clearer understanding of what you want I will make a branch and see if I can add the functionality you are after.

I am sorry to say I think I fully understand the problem

**Comment by SleeplessByte** [comment]
@markGilchrist Given a list of files named foo, instead of having one datapart per file (named foo1 foo2 foo3), they want one datapart in total named foo with all the files.
