### ISSUE TITLE
General http-method for a Request

### ISSUE THREAD

**Issue by monarezio** [kittinunf/Fuel#391]
I think it would be a nice feature to add the possibility to create a `Request` with an argument defining the http-method of the `Request`.

For example:
    
    "http://custom.com/url".http(Method.Post, listOf(/*Custom parameters*/))
    

I quickly checked the source code and seen that the `Request` class has a constructor, with the argument `method` already in it. Therefore I see no reason to **not** add such feature.

[Alamofire](https://github.com/Alamofire/Alamofire), networking framework for Swift, has this feature.

My sincerely apology, if this feature already exists, I was/am unable to find it in the documentation.

**Comment by markGilchrist** [comment]
like this in the sample app, MainActivity.kt lines 130, 136?
 
`Fuel.get("http://custom.com/url", listOf("foo" to "foo", "bar" to "bar")).....`
or 
`"http://custom.com/url".httpGet(listOf("foo" to "foo", "bar" to "bar"))`

**Comment by monarezio** [comment]
Please correct me if I am wrong, but that only calls the request with the get method? 

I thought that there would be a more generalised method, that would allow you to pass in an argument of type `Method`. The method would create the `Request` class with the correct `Method`.

Something like the private method in `Fuel.kt`. Just it would be public and maybe more name friendly (I hope you understand me)
    
    //request
    private fun request(method: Method, path: String, parameters: List<Pair<String, Any?>>? = null): Request = FuelManager.instance.request(method, path, parameters)
    

This feature would greatly help, people who are trying to create a wrapper around your library. Bigger projects require more API managers ect. 

I hope you understood my point and what I am trying to explain to you.

**Comment by markGilchrist** [comment]
FuelManager.instance.request(Method.GET,"")

**Comment by monarezio** [comment]
Oh, ok then, cheers!
