### ISSUE TITLE
Parameters should be Map<String, Any?>

### ISSUE THREAD

**Issue by monarezio** [kittinunf/Fuel#392]
In my opinion, the `parameter` argument in the `httpGet()`,`httpPost()` ect. should be of type `Map<String, Any?>`. 

Kotlin allows you, to convert `List<Pair>>` to `Map` like this:

    
    val myMap = parameters.toMap()
    

Why not use `Map` instead of `List<Pair>`?

**Comment by markGilchrist** [comment]
what would be the advantages of this instead of the current approach?

**Comment by monarezio** [comment]
I guess the main reason would be, that it's a collection built specially for associative array.

Another reason I can think of is, that `Map` has specially built in methods to make it easier for you to work with it. 

For example if you would like to search for an element by the 'key' in a list:

    val list = listOf(
            Pair("a", "Test"),
            Pair("b", "Test 2")
    )

    list.find { it.first == "a" } //Get value where key is 'a'

In a map it would look like this:

    val map = mapOf(
            Pair("a", "Test"),
            Pair("b", "Test 2")
    )

    map["a"] //Get value where key is 'a'

I am sure there are more reasons, which I can not think of at the moment!

**Comment by markGilchrist** [comment]
I the moment I can't see the advantage of the change. I think any searching logic implemented  by the consumer could be done in whatever format they chose but it is not the concern of Fuel as it is (IMO) not a requirement for the library but instead it sounds like one for the consumer.

I am happy to wait for the feedback from @kittinunf before closing or for you to think of some more reasons. shall we leave this open for a bit?

**Comment by monarezio** [comment]
Sure, tomorrow if I have some time to spare, I will post here more examples of the differences between `Map` and `List`.

Thank you!

**Comment by monarezio** [comment]
While, debugging my application, I found out another reason, why to implement this feature

Headers are currently of type `MutableMap`, while the behaviour of `MutableMap` is insufficient for the behavioural purposes of http headers. 

> Multiple headers with the same name is allowed in the [HTTP spec, section 4.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

As it is mentioned in [this issue](https://github.com/kittinunf/Fuel/issues/343)

------------

While headers can have more identical 'keys', I think http request parameters can not. 

------------

If I get time today, I will comment bellow more reasons to why to use `Map`/`MutableMap` instead of `List<Pair>`. But I think @Fibonacci- stated a good point.

**Comment by markGilchrist** [comment]
I think that the point he was raising is addressed in https://github.com/kittinunf/Fuel/pull/378

if we changed the syntax to map<String,Any> you are still able to do

```
val params = mapOf(
    "cookie" to "foo",
    "cookie" to "bar"
)
```
using map doesn't solve the problem, I will write a test to ensure that Fuel does not send multiple parameter keys

**Comment by markGilchrist** [comment]
Request.kt line 28
