### ISSUE TITLE
result.component1() returns null

### ISSUE THREAD

**Issue by CoolMind** [kittinunf/Fuel#398]
Hello!
I have a data class:
```
data class InfoResponse(
    val success: Int,
    val code: Int,
    val url: String,
    val errors: ErrorsResponse?) {

    data class ErrorsResponse(val common: List<String>?)
}
```
When a query returns an error JSON
```
{
  "success": 0,
  "code": 403,
  "url": "/info/",
  "errors": {
    "common": [
      "Login Required"
    ]
  }
}
```
in code
```
Api().getInfo(token)
            .responseObject<InfoResponse> { _, response, result ->
                if (response.statusCode == 200) {
                    if (result.component1()?.success == 1) {
                        ...
                    }
                }
            }
```
I get `result.component1() = null`, though `response` contains JSON. Other similar queries work right. `response.statusCode == 200` is right, as all queries return 200.

**UPDATE**

Probably a problem is here: `result` contains message: "java.lang.IllegalStateException: Gson().fromJson<T>(reade…: TypeToken<T>() {}.type) must not be null".

**Comment by CoolMind** [comment]
Also how to see a request (url, headers, etc)?

**Comment by markGilchrist** [comment]
if you no longer have the issue can we close this?

**Comment by CoolMind** [comment]
@markGilchrist, yes, thanks.
