### ISSUE TITLE
Follow redirections 

### ISSUE THREAD

**Issue by tbruyelle** [kittinunf/Fuel#40]
I recently used Fuel and received a 301 Moved permanently from the server with an other url in the Location header.

It would be nice if Fuel handles that kind of http codes and performs a second request automatically (or maybe when a specific parameter is enabled in `Manager.instance`).

**Comment by kittinunf** [comment]
Sorry about that. Agree @tbruyelle. I will implement this feature in the next coming releases.

**Comment by tbruyelle** [comment]
Hey no need to sorry :) Thanks in advance

**Comment by cbeust** [comment]
Just spent some time wondering why my downloads were not working until I realized Fuel doesn't follow redirections. That's a pretty big missing feature.

Any update on this?

**Comment by yoavst** [comment]
How do you want it to be implemented? Do you need to know that it was redirected, or do you just need the final data?

**Comment by cbeust** [comment]
Just the final data.

-- 
Cédric

**Comment by mplatvoet** [comment]
Note that other http libraries keep track of the previous redirects and/or keep track of the number of redirects. This all to prevent circular redirects or simply to many redirects.

**Comment by yoavst** [comment]
do they prevent only simple redirection?
`A -> B -> A -> B`
or more advanced like `A -> B -> C -> A -> B `?

**Comment by mplatvoet** [comment]
the latter, the more advanced option.

**Comment by yoavst** [comment]
#73 will support redirection. Detecting redirection loop will be added later.

**Comment by cbeust** [comment]
"Closed" as in... "fixed"? :)

**Comment by kittinunf** [comment]
@cbeust, sorry I didn't provide you much with the info. Yes, it is fixed. Simple redirection should be supported by now.
