### ISSUE TITLE
IDE setup / CONTIBUTING.md / CHANGELOG.md

### ISSUE THREAD

**Issue by SleeplessByte** [kittinunf/Fuel#409]
Hi there!

I'm trying to set up Fuel locally so I can actually contribute to this project, but not matter what I try, both in Android Studio and IntelliJ IDEA (Ultimate) I always end up with a lot of references not being resolved. Have you got this working?

I propose adding CONTRIBUTING.md which will automagically be picked up by GitHub and shows when making a PR. I am happy to supply a draft for this.

Secondly I think having a CHANGELOG.md with a list of changes will be helpful as well :)

**Comment by fnunezkanut** [comment]
are you getting errors like this https://imgur.com/QplZFBr ? I presume installing Android SDK would do the trick, **./gradlew clean build** fails for me on this

```
> Configure project :fuel-android 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fuel-android'.
```

**Comment by markGilchrist** [comment]
@SleeplessByte  if you need any help getting it running locally, please hit me up on slack

**Comment by SleeplessByte** [comment]
@markGilchrist that'd be great. Can you invite me on derk-jan@karrenbeld.info ? (email is public on other parts of the web already so whatevs 📦 )

**Comment by SleeplessByte** [comment]
@fnunezkanut gradle commands all work for me. It's simply intellisense failing.

**Comment by kittinunf** [comment]
@fnunezkanut I think in your case, you dont have SDK location setting up, you should setup in your `local.properties` file like

```
ndk.dir=foo/bar
sdk.dir=foo/bar
```

@SleeplessByte 
I just clone the fresh project in a new location and everything works after sync. I guess you synced the gradle already right? (sorry it sounds like a stupid question). For me personally, there are a lot of things red until I synced then it worked. I am not sure what I did differently.

**Comment by SleeplessByte** [comment]
Hey there! I was on holiday and just got back. This week i'll document what I've tried :)

**Comment by SleeplessByte** [comment]
@kittinunf cc @markGilchrist I don't know why but I just opened it up, merged upstream and it... just works. No settings changed whatsoever.
