### ISSUE TITLE
Fuel.download not blocking

### ISSUE THREAD

**Issue by mmuth** [kittinunf/Fuel#411]
Hi all,

I try to implement a download using Fuel.download using code, that is pretty close to the examples provided here on the readme.md

So basically i have a main method with a download call: 
```
fun main(args: Array<String>) {
    Fuel.download("http://my-server.com/api/v1/download", listOf(Pair("password", "mypw"))).destination { response, url ->
        File("${BASE_PATH}/${TARGET_FILE}")
    }.progress { readBytes, totalBytes ->
       // TODO some progress updates here...
    }.response { req, res, result ->
        if (res.statusCode == 200) {
            println("Download completed")
        }
    }
}
```
When I execute the main method, the programm immediately finishes with exit code 0. Seems like the download call is not blocking. Can I make it blocking somehow or is this just a Bug?

I also tried to call responseString(), but it seems that the response is completely loaded to the RAM (instead of streamed to my target file), which kills my app, as the download is 2GB big.

Thanks you!

**Comment by markGilchrist** [comment]
@mmuth I think that you program is exiting before the callback is called

have you tried adding a `Thread.sleep(12000)` ?

**Comment by mmuth** [comment]
Hi @markGilchrist ,

thanks for your answer. I did that and I noticed it's working with Thread.sleep. But that can't be the solution.
However, I got it work later on :-). I was just not knowing how to make the call in a synchroneous way, as the documentation doesn't point this out too obviously... and my Kotlin Knowledge is still at the beginning ;-).

I'd like to share my solution here, in case anyone ever struggles with the same problem. Don't use the lambda in the end, as it leads to the async style. Instead, assign the request to a val and call the response() method. Then it is blocking until it's finished. Like this:

```
fun main(args: Array<String>) {
    val (_, result, _) = Fuel.download("http://my-server.com/api/v1/download").destination { response, url ->
            File("${BASE_PATH}/${TARGET_FILE}")
        }.progress { readBytes, totalBytes ->            
            printImportProgress(readBytes)
        }.response()

        if (result.statusCode == 200) {
            println("Download completed")
        } else {
            // handle error...
        }
}
`

**Comment by kittinunf** [comment]
If you check the READMe.md, it already shows how to make the synchronous call though. Here specifically.

**Comment by mmuth** [comment]
Great and thanks a lot :) !
