### ISSUE TITLE
JSON data sent incorrectly to the server per POST

### ISSUE THREAD

**Issue by rip32700** [kittinunf/Fuel#412]
I am sending a JSON object per POST to my backend, but the string is sent incorrectly:

```
val data = JSONObject()
data.put("email", "blabla")
data.put("password", "bla")
 
// send the HTTP request
url
    .httpPost()
    .body(data.toString())
    .responseJson { _, _, result ->
               /* ... */
    }
```

What I retrieve on the server side is 
{ '{"email":"blabla","password":"bla"}': '' }

**Comment by markGilchrist** [comment]
you need to send the data as per the format 

``` kotlin 
url
    .httpPost()
    .body("email=blabla&password=bla")
    .responseJson { _, _, result ->
               /* ... */
    }
```

**Comment by SleeplessByte** [comment]
That should work, but it's better to use `'application/json'`.

http://www.ietf.org/rfc/rfc4627.txt

**Comment by rip32700** [comment]
solved it thank you, guys!

**Comment by markGilchrist** [comment]
I have added a function in a pr to tidy this up please comment and let me know if you see any avenue for improvement
https://github.com/kittinunf/Fuel/pull/418
