### ISSUE TITLE
Content-Type application/x-www-form-urlencoded by default  

### ISSUE THREAD

**Issue by mmuth** [kittinunf/Fuel#413]
Hi all!

I updated from 1.14.0 to 1.15.0 and had some issues with all my requests getting broken.
Before I was just doing very basic JSON PUT requests, like this
```
val (request, response, result) = "http://myserver.local/api/v1/test".httpPut()
                .header("Content-Type" to "application/json")
                .body("{"id":"test","somemorefields":"andvalues", ...")
                .response()
```

with the latest Update to 1.15, this doesn't work anymore. The Content-Type being sent is then "application/x-www-form-urlencoded; application/json" and my server rejects this.

Is this a nice default behaviour? I wouldn't expect a default header to be set and my explicitly defined headers sent on the second position only (which makes everything fail now). I guess this whole implementation changed with https://github.com/kittinunf/Fuel/pull/393...

Sidenote for anyone with the same problem: I figured out that the headers can be reset by wrapping them in a map 
```
... .header(mapOf("Content-Type" to "application/json"))...
```
Kind Regards
Matthias

**Comment by RingoMckraken** [comment]
Also just scratched my head for a good while today on this why our back end was sending 500's to the app.

**Comment by ftomassetti** [comment]
Definitely confusing

**Comment by markGilchrist** [comment]
@ftomassetti @RingoMckraken @mmuth I have just merged in a method that sets the header 

when released 
``` kotlin
"http://myserver.local/api/v1/test".httpPut()
                .header("Content-Type" to "application/json")
                .body("{"id":"test","somemorefields":"andvalues", ...")
                .response()
```

becomes

``` kotlin
"http://myserver.local/api/v1/test".httpPut()
                .jsonBody("{"id":"test","somemorefields":"andvalues", ...")
                .response()
```

**Comment by RingoMckraken** [comment]
Right on, I'll give it a spin, thanks!

**Comment by jackterranova** [comment]
Looks like `Request.jsonBody` is documented on the README.md, but this is not yet released correct?

**Comment by markGilchrist** [comment]
True
