### ISSUE TITLE
Fuel.download doesn't handle redirected url correctly

### ISSUE THREAD

**Issue by eprendre** [kittinunf/Fuel#416]
```kotlin
    Fuel.download("https://github.com/kittinunf/Fuel/releases/download/1.12.1/fuel-1.12.1.jar")
            .destination { response, url ->
                File("fuel.jar")
            }.progress { readBytes, totalBytes ->
                val progress = readBytes.toFloat() / totalBytes.toFloat()
                println(progress)
            }.response { req, res, result ->
            }
```

The `redirectResponseInterceptor` added to Fuel.download call a new request `next(request, manager.request(encoding).header(newHeaders).response().second)`. Thus `destination` and `progress` won't work as they are bound to the first request.

**Comment by toemat** [comment]
Also having this issue trying to download images that always redirect. It seems like `response.result.success -> it: ByteArray` also doesn't get the data, even though `res` seems to contain the final response including the data...

**Comment by SleeplessByte** [comment]
@toemat can you open another issue for that?

I'll try to fix both in one go but it helps to keep track of these.
