### ISSUE TITLE
No interface method invokeOnCompletion

### ISSUE THREAD

**Issue by SeleznevAM** [kittinunf/Fuel#420]
When I call `awaitResponseResult` method it throws a NoSuchMethodError.

 I am using coroutines version 0.24.0

``` kotlin
override suspend fun getData(uri: String): ByteArray {
    return uri.httpGet().awaitResponseResult()
}
```
![image](https://user-images.githubusercontent.com/18379688/44910256-2f167500-ad2b-11e8-9c1b-fd7759e4fd5f.png)

**Comment by markGilchrist** [comment]
@SeleznevAM 

`awaitResponseResult()` is deprecated, please can you make sure you are using the latest version of `fuel-coroutines` and modify you method to the below

``` kotlin
override suspend fun getData(uri: String): ByteArray {
    return uri.httpGet().awaitByteArrayResult()
}
```

please comment if this does not resolve your issue
