### ISSUE TITLE
Actually asynchronous coroutines

### ISSUE THREAD

**Issue by clarcharr** [kittinunf/Fuel#429]
Right now, the the functions offered by `fuel-coroutines` simply start a coroutine which blocks until the request is complete. Ideally, this should actually suspend the coroutine instead of blocking whenever possible.

**Comment by SleeplessByte** [comment]
Hi @clarcharr, from what I can tell is that the current blocked coroutines are released during blocking, but I'm probably wrong there as it makes total sense that only on certain blocking API calls it releases. 

Do you have any reference for me how to change it from blocking to suspending?

**Comment by iNoles** [comment]
@SleeplessByte that would be like removing get()?

**Comment by iNoles** [comment]
@SleeplessByte I have been looking for it. Only thing I think I can think of async {} return Deferred<Result<U, FuelError>>. get() should be removed because it is a blocking call.

**Comment by SleeplessByte** [comment]
cc @iNoles: is the pr #431 handling cancellation as well? We might want to add it / review it / open a second pr

**Comment by t-ae** [comment]
I tried my error above on master branch but it didn't happen.
On 1.15.0(and on Android) the code below doesn't cancel imemdiately.

```kotlin
fun testCancel() {
    runBlocking {
        val task = async {
            "https://github.com/kittinunf/Fuel"
                    .httpDownload()
                    .destination { a, b -> File.createTempFile("tmp", ".tmp") }
                    .progress { a, b -> println("$a, $b") }
                    .awaitByteArray()
        }
        try {
            task.cancel()
            println("cancel called")
            task.await()
            Assert.fail()
        } catch(e: CancellationException) {
            println(e)
        }
    }
}
```

So it may already be fixed. Sorry.

**Comment by SleeplessByte** [comment]
I believe this is now merged in? (cc @markGilchrist ). If not, please re-open.

**Comment by Legion2** [comment]
@t-ae I used your testcase but added a `delay(100)` before `task.cancel()`, so the download will start before the coroutine is canceled. The result: The download is not canceled and the file download is completed. This is very bad when downloading huge files (>50MB) which take very long and should be canceled.
<details>
  <summary>Test Logs</summary>

```
cancel called
596, -1
617, -1
1981, -1
3351, -1
4721, -1
6091, -1
7461, -1
8831, -1
10201, -1
11571, -1
12941, -1
14311, -1
15681, -1
17051, -1
18421, -1
19791, -1
21161, -1
22531, -1
23901, -1
25271, -1
26641, -1
28011, -1
29381, -1
30751, -1
32121, -1
33483, -1
34853, -1
36223, -1
37593, -1
38963, -1
40333, -1
41703, -1
43073, -1
44443, -1
45813, -1
47183, -1
48553, -1
49923, -1
51293, -1
52663, -1
54033, -1
55403, -1
56773, -1
58143, -1
59513, -1
60883, -1
62253, -1
63623, -1
64993, -1
65115, -1
66477, -1
67847, -1
69217, -1
70587, -1
71957, -1
73327, -1
74697, -1
76067, -1
77437, -1
78807, -1
80177, -1
81547, -1
82917, -1
84287, -1
85657, -1
87027, -1
88397, -1
89767, -1
91137, -1
92507, -1
93877, -1
95247, -1
96617, -1
97987, -1
99349, -1
100719, -1
102089, -1
103459, -1
104829, -1
106199, -1
107569, -1
108939, -1
110309, -1
111679, -1
113049, -1
...
```
</details>

**Comment by Legion2** [comment]
I think the canceling was removed by accident in this commit https://github.com/kittinunf/fuel/commit/ad3e014aee70d7a1fc14fa526f4cb8e3ddc04ffe#diff-e4e7f9c034fdee0e0a5786ff4be1dc4e22c643f6ac23824c20057d40d258a644L21

`continuation.invokeOnCancellation { cancel() }` canceled the request when the coroutine was canceled, but the commit refactored the code and removed this callback.
