### ISSUE TITLE
New Kotlinx Coroutines Version

### ISSUE THREAD

**Issue by iNoles** [kittinunf/Fuel#430]
I think it is a best to use this after next release versions because it may break some codes. 

https://github.com/Kotlin/kotlinx.coroutines/releases/tag/0.26.0

**Comment by SleeplessByte** [comment]
Maybe we can work on #429 when working on this. By semantic versioning, if the upgrade we require breaks current consumers it will be on 2.0.0.

**Comment by kittinunf** [comment]
I agree with @SleeplessByte I think we can take this opportunity to clear up the current APIs and provide the better ones.

**Comment by iNoles** [comment]
Closed by #438
