### ISSUE TITLE
License presentation in Android

### ISSUE THREAD

**Issue by t-ae** [kittinunf/fuel#437]
Hello. I'm using Fuel in my Android app.

For showing licenses, I use google's official `oss-licenses-plugin`.

[Including Open Source Notices](https://developers.google.com/android/guides/opensource)
> How licenses are determined
> The Gradle plugin scans the POM dependencies of the project at compile time. When a Maven POM exists for a direct dependency of the app, the plugin processes the <licenses> element and embeds the link and title of each license in an Android asset in the final app APK.

BTW Fuel doesn't appear in the generated list.
If you support this, Android developers can present licenses easily.

For example, another library I'm using writes it in gradle.
https://github.com/natario1/CameraView/blob/640ec2da0859b67115e3691d63aafb8fe19d6863/cameraview/build.gradle#L60-L93

It seems `Licenses` entry appears like below if it's configured correctly.
https://mvnrepository.com/artifact/com.otaliastudios/cameraview/1.5.1

Which is not shown in Fuel currently.
https://mvnrepository.com/artifact/com.github.kittinunf.fuel/fuel/1.15.0

**Comment by SleeplessByte** [comment]
I'll add it for ya

**Comment by SleeplessByte** [comment]
This *SHOULD* be fixed with the next release via 

> https://github.com/kittinunf/Fuel/blob/master/build.gradle.kts#L132

**Comment by SleeplessByte** [comment]
Ugh. Yeah you're right. @iNoles didn't you know how to fix this?

**Comment by iNoles** [comment]
I think I have some idea for this
