### ISSUE TITLE
Change Request Timeout

### ISSUE THREAD

**Issue by jjdestef3** [kittinunf/Fuel#44]
Hi,

Just wondering, how would you change the default request timeout on a per invocation basis?

Thanks

**Comment by yoavst** [comment]
This library should provide setter for 
https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt#L28

**Comment by kittinunf** [comment]
Thanks for pointing that out. Let's do this for next release.

**Comment by yoavst** [comment]
https://github.com/kittinunf/Fuel/commit/104358729adf77770a1da323ea850b281700a0da

Should fix this.

**Comment by dstd** [comment]
@yoavst do you have any ETA for next release with this fix? Thanks

**Comment by kittinunf** [comment]
I will push 0.71 tonight. Hang on tight.

**Comment by kittinunf** [comment]
Done! 0.71 is out.

**Comment by dstd** [comment]
Thank you!

**Comment by jjdestef3** [comment]
Hi,

Given the current calling semantics, how would you use this in a typical kotlin get call?

Thanks

**Comment by dstd** [comment]
@jjdestef3
```
"http://httpbin.org/get".httpGet().timeout(5000).responseString { request, response, result -> 
    ...
}
```

**Comment by yoavst** [comment]
@jjdestef3  https://github.com/kittinunf/Fuel/commit/7a35b6b485a48462bb8db70e2db1e211bed4284e
