### ISSUE TITLE
Add klint for coding style enforcement

### ISSUE THREAD

**Issue by SleeplessByte** [kittinunf/Fuel#442]
# Feature Request

## Description
Currently there is no coding style enforcement whatsoever but now that there is an [official standard]( https://kotlinlang.org/docs/reference/coding-conventions.html) we should try to adhere to it. This can be enforced and easily checked by adding a linter to both the codebase as well as the build process.

## Proposed Solution
- [ ] Add https://github.com/shyiko/ktlint by adding it to the Gradle configuration
- [ ] Add documentation to show how to enable it in Intellij (and thus Android Studio)
- [ ] Add klint to travis

**Comment by iNoles** [comment]
The Gradle check task depends on the test task which means test is executed before check is run.

https://github.com/jeremymailen/kotlinter-gradle is very interesting plugins for it because it support gradle kotlin scripts and Incremental build.
