### ISSUE TITLE
Extract common test functionality into project

### ISSUE THREAD

**Issue by SleeplessByte** [kittinunf/Fuel#447]
# Refactoring

## Description
With #444 we got the great addition of mocked request/responses for all tests in all projects. However, the solution is not very DRY and there is duplication across all projects, namely the mockhelper. We should extract mockhelper into a test project that can be included everywhere (and replace testCompile('mockserver' ) with that one).

This also allows us to define a list of test input and outputs (requests) in this common project that should pass in ALL projects. The idea here that regardless of the technology used (moshi, gson, ...) the result should be the same.

## Files to process
- [ ] `**/test/**/MockHelper.kts`

## Why this is necessary**
A change to `MockHelper.kts` currently requires shotgun surgery: the same change across many files, because they are duplicates.

**Comment by gowthamgts** [comment]
Ah come on @kittinunf, leave something for us. 😄

**Comment by SleeplessByte** [comment]
Sorry, that was me :p
