### ISSUE TITLE
addRequestInterceptor: types mismatch

### ISSUE THREAD

**Issue by xvs32x** [kittinunf/Fuel#453]
# Bug Report

## Description
Hi all. I want to connect my own interceptor in fuel instance. I'm doing it, copying pasting code from the docs, see fragment below:
```
val manager = FuelManager()
if (BUILD_DEBUG) {
    manager.addRequestInterceptor(cUrlLoggingRequestInterceptor())
}
val (request, response, result) = manager.request(Method.GET, "https://httpbin.org/get").response() //it will print curl -i -H "Accept-Encoding:compress;q=0.5, gzip;q=1.0" "https://httpbin.org/get"
```
But is not work, because type of  cUrlLoggingRequestInterceptor not match with argument type in addRequestInterceptor. Please, can you show me some example, if i'm wrong. 
Sorry for question, I'm a new in Java and Kotlin. Thanks for a beautiful lib.:)

## To Reproduce

```Kotlin
// Test case or sample that shows broken behaviour and expected behaviour
```

## Screenshots
http://joxi.ru/823vZ6PcJbNk4m <- IDE notice found here

### Development Machine
_Complete the following information if applicable_

 - OS: Windows 10
 - IDE: Android Studio
 - Fuel version: fuel-android:1.15.0
 - Kotlin version: 1.2.71

### Smartphone or Emulator
_Complete the following information if applicable_

**Comment by xvs32x** [comment]
@kittinunf Oops, big thanks, your save my life!

**Comment by kittinunf** [comment]
Shall we close this then?

**Comment by xvs32x** [comment]
Yes, and sorry for stupid issue
