### ISSUE TITLE
 How do I configure cookies like okhttp cookieJar?

### ISSUE THREAD

**Issue by GavinDon** [kittinunf/Fuel#458]
现在来看 fuel使用cookie 只能在header中添加 。不能统一配置管理吗？

(Google Translate: 
Now look at fuel using cookies can only be added in the header. Can't you unify configuration management?)

**Comment by GavinDon** [comment]
使用cookieManage管理的话也不能统一配置  。。应该在FuelManage中提供一个这样的方法

**Comment by GavinDon** [comment]
使用cookieManage管理的话也不能统一配置 。。是否应该在FuelManage中提供一个这样的方法呢

**Comment by SleeplessByte** [comment]
Possibly a duplicate of #263 or #105.

Yes @GavinDon, we accept PR's!

**Comment by SleeplessByte** [comment]
Let's continue in #263
