### ISSUE TITLE
Failed to resolve fuel-reactor 1.13.0 1.14.0 15.0

### ISSUE THREAD

**Issue by jganser** [kittinunf/Fuel#461]
# Bug Report

gradle -> jcenter erros...

**Comment by lucasvalenteds** [comment]
@jganser Could you be more specific about the error, please? An error message, error code or stack-trace may help.

The available versions of `fuel-reactor` is available at https://jcenter.bintray.com/com/github/kittinunf/fuel/fuel-reactor/.

**Comment by kittinunf** [comment]
or a newer version like 1.15.1 

I think we can close this unless there is more info?
