### ISSUE TITLE
Add ability to customize DownloadTaskReqeust FileOutputStream

### ISSUE THREAD

**Issue by charshep** [kittinunf/Fuel#463]
# Feature Request

## Description
I'd like to incorporate [RNCrytpor-Native](https://github.com/TGIO/RNCryptorNative) in conjunction with Fuel in order to encrypt downloaded files. Unencrypted data should never be written to storage, even temporarily, so I'd like to wrap/override the `FileOutputStream` that is used internally by `DownloadTaskRequest`.

## Proposed Solution
I'm not familiar enough yet with Fuel to propose an exact design but the ideas discussed in #225 seem like they would lend themselves to accommodating configuring streams used by Fuel.

## Alternatives I've considered
`ResponseDeserializable`, if I understand it correctly, isn't appropriate because it would only let me rewrite a downloaded file that has already been written to disk without encryption.

**Comment by charshep** [comment]
I'm starting to work on a fork of this. I'm having trouble including `rncryptor-native` however. In a separate application project I'm able to simply add:

    implementation 'com.github.tgio:rncryptor-native:0.0.9'

to my build.gradle and I can import it no problem. However, adding the same to `Fuel/fuel/build.gradle` while it does in fact pull down the library (I can see it in External Libraries in Project view) ,  `import` statements in code fail to properly import the file and the usual auto-import alt-return keyboard shortcut can't seem to find the library.

Anyone able to help me out with what I'm missing here? Sorry if this is obvious, still pretty new to Kotlin. Apologies also if there are more appropriate place to post this kind of question.

**Comment by SleeplessByte** [comment]
The IDE can definitely fuck this up.

What I've tried, if invalided and restart doesn't work, is actually
deleting the .idea folder and build again from gradle.

**Comment by iNoles** [comment]
It looks like that only work in Android.

**Comment by charshep** [comment]
Thanks @SleeplessByte

@iNoles Yep, realized that after a bit. Thanks. :P

**Comment by SleeplessByte** [comment]
I'm working on an implementation that allows for generic streams (#479), that should also cover this.
