### ISSUE TITLE
Improving Testing 

### ISSUE THREAD

**Issue by iNoles** [kittinunf/Fuel#468]
# Refactoring

## Description
According to Fuel.kt, blocking is always false by default. It may be true in outside of this project. Also, timeoutRead only uses once, so it is always be null.  All tests related projects use same timeout values. 

## Files to process
- [x] SameThreadExecutorService.kt
- [x] TestConfiguration.kt
- [x] Fuel.kt

## Why this is necessary**
I would remove SameThreadExecutorService and TestConfiguration. With mock web server, we may not need timeout values. It would help to improve Coverages. 

## Additional context
Add any other context or screenshots about the refactoring request here.

**Comment by SleeplessByte** [comment]
I would still like to test timeouts with the mock web server!

**Comment by iNoles** [comment]
@kittinunf What is your opinion of this?
