### ISSUE TITLE
Missing fuel-android version 1.15.1

### ISSUE THREAD

**Issue by monkeymc** [kittinunf/Fuel#475]
Cant find at https://jcenter.bintray.com/com/github/kittinunf/fuel/fuel-android/

**Comment by iNoles** [comment]
Also livedata too.

**Comment by kittinunf** [comment]
It looks like there is something wrong with publishing script ... I will check what's wrong ...

In the meantime, @monkeymc can you use previous version?

**Comment by kittinunf** [comment]
I fixed it, you should be able to find them there

https://jcenter.bintray.com/com/github/kittinunf/fuel/fuel-android/1.15.1/
and
https://jcenter.bintray.com/com/github/kittinunf/fuel/fuel-livedata/1.15.1/
