### ISSUE TITLE
Improve multipart features to support more than files

### ISSUE THREAD

**Issue by abelsromero** [kittinunf/Fuel#480]
# Feature Request

## Description
I am interacting with a CMS API that requires uploading a document alongside some JSON metadata.
I can easily do that with cURL as seen below, but the only solution found with Fuel seems a hack and requires storing the metadata in a temporal file.

```cUrl
curl "https://$api_hostname/v1/documents" \
-X POST \
-H 'Content-Type: multipart/form-data' \
-H "Authorization: Bearer $token" \
-H "Document-Store: $doc_store" \
-F metadata="{
    \"description\": \"Test document\",
    \"nested_array\": [{...}.{...}]
	};type=application/json" \
-F file=@file_path)
```

The only way I got this to work with Fuel is using the `httpUpload` like this:

```kotlin
    val url = "..."
    val (request, response, result) = url.httpUpload(
//            parameters = listOf("metadata" to """{"description":"test document from Kotlin"};type=application/json""")
    )
            .dataParts { request, url ->
                listOf(
                        DataPart(File("src/main/resources/rust-logo-blk.svg"), "file"),
                        DataPart(File("src/main/resources/doc.json"), "metadata", "application/json")
                )
            }
            .header("Authorization" to "Bearer $token")
            .header("Document-Store" to docStore)
            .responseString()

    println(request.cUrlString())
    if (response.statusCode == 201) {
        println(String(response.data))
    }
```

Using the commented line with `parameters` fails because Fuel sets the content type as `text\plain` and the service complains.

## Proposed Solution
As a quick approach, extend `DataPart` to support other things that are not files. That would fix the problem.

As a mid/long-term approach, to offer a more cleaner/simple solution. I'd propose to extend the httpPost method to support sending multipart data elements.
To enable multipart we could add a method to set the content-type, or a fluent method `multipart()`, or check if the user has set the header "Content-type" with `header()`.

```kotlin
    val (request, response, result) = url.httpPost(listOf(
            "metadata" to DataPart("""{"description":"test document from Kotlin"}""", "application/json"),
            "file" to DataPart(File("resources/rust-logo-blk.svg"))))
            .header("Content-Type" to "multipart/form-data")
            .header("Authorization" to "Bearer $token")
            .header("Document-Store" to docStore)
            .responseString()
```

## Alternatives I've considered
Extending httpUpload() is an option, but imho the more we divert from raw HTTP, the more confusing it becomes for users to adopt Fuel.

## Additional context
-

**Comment by SleeplessByte** [comment]
Very similar to #479 and overlaps. Let me close this and have that issue track ALL new features, as it already has more than 2 features to track.

**Comment by abelsromero** [comment]
> Very similar to #479 and overlaps. Let me close this and have that issue track ALL new features, as it already has more than 2 features to track.

Sorry, there was some issue with GitHub and issues did not appear.
