### ISSUE TITLE
Add support for Stetho Android debug bridge

### ISSUE THREAD

**Issue by igorwojda** [kittinunf/fuel#493]
# Feature Request
Add Support for Stetho, so we can easily review all requests made by the Android application
http://facebook.github.io/stetho/

## Description
Currently reviewing underlying requests is quite hard (no support for Stetho). Besides that, this is very popular tools, so it's a shame that switching from Retrofit devs need to make the sacrifice.

## Proposed Solution
Here is some old implementation that I believe is a good place to start
https://github.com/Gira-X/fuel-stetho-client
however, it's a bit outdated, so it is not compatible with the newest version of Fuel

## Additional context
_Edit by @SleeplessByte_

From the documentation, we can see there are OkHttp interceptors available, so it will be easy to trivial to implement this for us:
> **Enable Network Inspection**
> If you are using the popular OkHttp library at the 2.2.x+ or 3.x release, you can use the Interceptors system to automatically hook into your existing stack. This is currently the simplest and most straightforward way to enable network inspection.
>
> **For OkHttp 2.x**
> ```Java
> OkHttpClient client = new OkHttpClient();
> client.networkInterceptors().add(new StethoInterceptor());
> ```
>
> **For OkHttp 3.x**
> ```Java
> new OkHttpClient.Builder()
>     .addNetworkInterceptor(new StethoInterceptor())
>     .build();
> ```
> 
> As interceptors can modify the request and response, add the Stetho interceptor after all others to get an accurate view of the network traffic.
>
> If you are using `HttpURLConnection`, you can use `StethoURLConnectionManager` to assist with integration though you should be aware that there are some caveats with this approach. In particular, you must explicitly add `Accept-Encoding: gzip` to the request headers and manually handle compressed responses in order for Stetho to report compressed payload sizes.
>
> See the stetho-sample project for more details.

**Comment by iNoles** [comment]
Fuel uses HttpURLConnection.

**Comment by SleeplessByte** [comment]
Yes, but that doesn't matter

**Comment by iNoles** [comment]
This issue should be closed for #523
