### ISSUE TITLE
Add default value for the failure param in the result.fold

### ISSUE THREAD

**Issue by igorwojda** [kittinunf/Fuel#494]
## Description
`result.fold` should have a default value for `failure` parameter. Since `return` statement is not allowed in `success` and `failure` blocks now we need to define a nullable variable `albums` to store it.

```
    private suspend fun httpGetCoroutine(): List<AlbumNetworkModel> {
        var albums: List<AlbumNetworkModel>? = null
        
        Fuel.get("/albums").responseObject<List<AlbumNetworkModel>> { _, _, result ->
            result.fold(
                success = {
                    albums = it
                },
                failure = {
                    albums = listOf()
                })
        }
        
        return albums ?: listOf()
    }
```

## Proposed Solution
However, with the default value for `failure` parameter, we could  use the library in a more expressive way by assigning a default value to our `albums` variable 

```
    private suspend fun httpGetCoroutine(): List<AlbumNetworkModel> {
        var albums: List<AlbumNetworkModel> = listOf()
        
        Fuel.get("/albums").responseObject<List<AlbumNetworkModel>> { _, _, result ->
            result.fold(
                success = {
                    albums = it
                })
        }
       
        return albums
    }
```

**Comment by SleeplessByte** [comment]
- You are allowed to write returns, you do need to label them. However, returning from a handler makes no sense, because the expected return value is Unit:

    ```kotlin
    Fuel.get("/albums").responseString handler@{ _, _, result ->
      // do something with result
      return@handler
    }
    ```
- You don't need a nullable variable?
    ```kotlin
    var albums: List<AlbumNetworkModel>
    Fuel.get("/albums").responseObject<List<AlbumNetworkModel>> { _, _, result ->
      result.fold(success = { albums = it }, failure = { albums = listOf() })
    }
    ```

**Comment by igorwojda** [comment]
I tried you approach but IDE displays an error
![image](https://user-images.githubusercontent.com/530122/47896128-d6b33f00-de63-11e8-957b-13ae24466294.png)


Ok so to be clear I am doing it in the context of coroutines and as far I see I need to use `awaitResponseObject` instead of `responseObject` (otherwise result is returned after function returns). Also, this is the JSON, so I want it to be parsed to an object.

Anyway, this is the syntax that I have currently and I wonder if it can be simplified?
```
override suspend fun getAlbumList(): List<AlbumDomainModel> {
        val (_, _, result) = Fuel.get("/albums").awaitObjectResponse<List<AlbumNetworkModel>>(
            gsonDeserializerOf()
        )

        var albums: List<AlbumNetworkModel>? = null

        result.fold(
            success = {
                albums = it
            },
            failure = {
                albums = listOf()
            })

        return albums?.map { it.toDomainModel() } ?: listOf()
    }
```

**Comment by SleeplessByte** [comment]
Your initial example doesn't work because there you used an async handler but try to return synchronously (and I think that is what you meant in your response just now).

In your second example, `result.fold` should give back the album, because kotlin doesn't know WHEN the fold functions are executed:

```kotlin
val (_, _, result) = Fuel.get("/albums")
  .awaitObjectResponse<List<AlbumNetworkModel>>(gsonDeserializerOf())

return result.fold(success = { it }, failure = { listOf() })
```

If you look at the type definition of `fold`, you can see that both `success` and `failure` both must return the same type `X` and that it returns an instance of `X`. 
Under the hood, what it does, is reduce the `Result` value to `X` by calling the function under `success` if the result was `Result.Success`, and calling `failure` if it was `Result.Failure`.

**Comment by SleeplessByte** [comment]
@igorwojda I hope you got this resolved, if not us know and we can re-open. If you're looking for a more generic way of handling this, you can define an extension, something along the lines of:
```kotlin
fun <T> Result<T, FuelError>.getOrDefault(default: () -> T) = fold(success = { it }, failure = { default() })

// ...
val albums = result.getOrDefault({ listOf() })
```

**Comment by igorwojda** [comment]
I had some time off... So`getOrElse` did the trick for non-nullable types.
```
override suspend fun getAlbumList(): List<AlbumDomainModel> {
        val (_, _, result) = Fuel.get("/albums").awaitObjectResponse<List<AlbumNetworkModel>>(gsonDeserializerOf())

        var albums = result.getOrElse(listOf())
        return albums.map { it.toDomainModel() }
    }
```
However, I am still not sure how to simplify response that may not contain data (try to get object with non-existing id). `getOrElse` method does not allow to return null values, so either I am missing something or we need `getOrNull` method? 🤔 
```
    override suspend fun getAlbum(id: Int): AlbumDomainModel? {
        val (_, _, result) = Fuel.get("/albums/$id").awaitObjectResponse<AlbumNetworkModel>(gsonDeserializerOf())

        var album: AlbumNetworkModel? = null
        result.fold(success = { album = it }, failure = {})

        return album?.toDomainModel()
    }

```
