### ISSUE TITLE
response length != content length

### ISSUE THREAD

**Issue by NikkyAI** [kittinunf/Fuel#498]
# Bug Report

## Description
`GET` request to `http://files.minecraftforge.net/maven/net/minecraftforge/forge/json`
only return a string containing the first ~8k bytes, the content length is reported as ``

## To Reproduce

```Kotlin
val (_, response, result) = "http://files.minecraftforge.net/maven/net/minecraftforge/forge/json".httpGet()
    .responseString()

when(result) {
    is Result.Success -> {
        println(response.contentLength)
        println(result.value.toByteArray().size)
        assertEquals(response.contentLength, result.value.toByteArray().size)
    }
    is Result.Failure -> fail(result.error.message)
}
```

## Expected behavior
receiving the complete response content or
return a reasonable error message

### Development Machine
_Complete the following information if applicable_

 - Fuel version: master
 - Kotlin version: 1.3.0

## Additional context
this also causes errors with `fuel-kotlinx-serialization` and causes JsonParseExceptions randomly

**Comment by SleeplessByte** [comment]
I expect http://files.minecraftforge.net to be at fault here.

**Comment by iNoles** [comment]
Expected for Gzip.

**Comment by NikkyAI** [comment]
there is no gzip involved, just a unreliable server
and Fuel does not catch when the connection was prematurely interrupted
even though in this case it could because Content-Length exists

**Comment by NikkyAI** [comment]
since we figured out it was the server being unreliable.. this is now more a bug about Fuel not catching that unreliability, should i open a new bug or rename this one ?

**Comment by SleeplessByte** [comment]
You can't really catch this. Content-Length is, although implemented as
such, not authorities when it comes to the RFC.

**Comment by iNoles** [comment]
Don't depend on the Content-Length at all because it is always unreliable.
