### ISSUE TITLE
[fuel-core] Overwrite header in case of Content-Type: multipart/form-data

### ISSUE THREAD

**Issue by PeterSkopal** [kittinunf/Fuel#513]
# Feature Request

## Description
This feature solves a problem I've had when constructing a Multipart/form-data request.

If one sets the Content-Type header to multipart/form-data manually (done in the snippet below) this request wont work properly, since the boundry value in the header, pointing out the file, is missing.

If the manually set content-type is removed, the request works fine.

```
Fuel.upload(path = baseUrl, method = Method.POST)
                .header(mutableMapOf(
                    "apikey" to key,
                    "Accept" to "application/json",
                    "Cache-Control" to "no-cache"
                    "Content-Type" to "multipart/form-data"
                ))
                .dataParts { _, _ -> listOf(DataPart(file, "file", "image/jpeg")) }
                .responseJson { _, _, result ->
                    result.fold(
                            success = { data -> cb(data.content) },
                            failure = { error ->
                                println("An error of type ${error.exception} happened: ${error.message}")
                                cb("")
                            }
                    )
                }
```

## Proposed Solution
Fuel should in my opinion in the case of such a specific request, *overwrite* the header even though a user beforehand set it manually, since the request otherwise wont work at all.

**Comment by SleeplessByte** [comment]
@PeterSkopal completely agreed and is actually fixed down the line. Will be part of the 2.0 release!
