### ISSUE TITLE
Fuel Request Body(upload files) shoud be separated just like client, or there will be no client for replacing

### ISSUE THREAD

**Issue by dpmaycry** [kittinunf/Fuel#528]
I am recently try to replace httpclient by okhttpclient,than I found the requestbody(I mean the uploaded files(blobs) part) cannot be accessed from Request which means I cannot change Request to OKhttpRequest or any other kinds of custom request. Hope for your reply.

**Comment by SleeplessByte** [comment]
You should only need to use the `interface Body` and then using

```kotlin
request.body().writeTo(outputStream: OutputStream)
```

Which should not be internal / private.

What does your implementation look like?

**Comment by dpmaycry** [comment]
Thank u 4 reply but I really got confused.
`request.body().writeTo(outputStream: OutputStream)`is from OKRequest? If so,this should be `request.body().writeTo(sink: BufferedSink)`，
I am now try to use sink.outputStream to write the body in it,wait and see

**Comment by iNoles** [comment]
interesting implementation to get Fuel to works with OKHttp.

**Comment by dpmaycry** [comment]
> You should only need to use the `interface Body` and then using
> 
> ```kotlin
> request.body().writeTo(outputStream: OutputStream)
> ```
> 
> Which should not be internal / private.
> 
> What does your implementation look like?

Finally solved the upload part of using okhttp as fuel's client(other kinds of request is already done). Try to complete my work and make it open sourced soon.(or should I make a pull request to fuel).
It may still not prefect, hope everyone to make it better together.
