### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property sourceCallback has not been initialized

### ISSUE THREAD

**Issue by CoolMind** [kittinunf/Fuel#529]
# Bug Report

## Description

Call to API throws exception `kotlin.UninitializedPropertyAccessException: lateinit property sourceCallback has not been initialized` when uploading a file.

## To Reproduce

1. Open an image from the gallery and create a temporary file.
2. Upload it to a server.
```Kotlin
            GlobalScope.launch(Dispatchers.IO) {
                val file = getTempFile(uri)
                val uploadTask = GlobalScope.async {
                    url = uploadImage(token, file)
                }
                uploadTask.await()
            }

    private suspend fun uploadImage(token: String, file: File): String? {
        val result = InteractorImpl().updatePhoto(token, file)
        result.fold({ response ->
                val data = response.data
                url = data.file_url
        }, { fuelError -> fuelError.message })
        return url
    }

    override suspend fun updatePhoto(token: String, file: File): Result<PhotoResponse, FuelError> =
        api.savePhoto(token, file).awaitObjectResponse(
            PhotoResponse.Deserializer()).third

    override fun savePhoto(token: String, file: File): Request =
        "save-photo/".httpUpload(Method.POST, listOf("token" to token, "file" to file))
```

### Development Machine
 - OS: [Windows 10]
 - IDE: [Android Studio]
 - Fuel version: [1.16.0]
 - Kotlin version: [1.3.0]

### Smartphone or Emulator

 - OS: [Android 5.0.1]

**Comment by SleeplessByte** [comment]
You have not added a file / source to your upload:

```kotlin
"save-photo/".httpUpload(Method.POST, listOf("token" to token)).source { file }
```

**Comment by CoolMind** [comment]
@SleeplessByte, thanks! Oh, how can I didn't notice?

**Comment by CoolMind** [comment]
@SleeplessByte, can you help me?

If I write:
```
        "save-photo/"
            .httpUpload(Method.POST, listOf("token" to token))
            .source { request, url -> file }
```
it turns out, that a file is not transmitted to a server, because it returns an corresponding error.

What ha I missed?

**Comment by CoolMind** [comment]
Probably https://github.com/kittinunf/Fuel/issues/479 can help. I will update soon.

**Comment by SleeplessByte** [comment]
@CoolMind sorry I can't get from your comments if the file is actually not transmitted or if YOUR use-case doesn't work. A ticket with "it doesn't work" doesn't help anyone.

As per the documentation, which is incomplete I agree, `.upload` requests are `application/form-multipart`, which always require `DataPart` at the moment. We actually use `upload` to upload the binaries to bintray/maven so that is not broken.

**Comment by CoolMind** [comment]
@SleeplessByte, you are right, I wrote not clearly. The server didn't receive the file and wrote an error with a message that file wasn't attached. I didn't touch an interactor and changed an API request (using `dataParts`).
Thank you, I understood, that `application/form-multipart` requests require `DataPart`.
