### ISSUE TITLE
java.lang.ClassCastException: com.google.gson.JsonSyntaxException cannot be cast to com.github.kittinunf.fuel.core.FuelError

### ISSUE THREAD

**Issue by CoolMind** [kittinunf/Fuel#531]
Suppose you have a JSON like
```
{
  "success": 1,
  "errors": [],
  "update_time": 1542190271,
}
```
And a parsing class like
```
data class YourResponse(
    val success: Int,
    val update_time: Int,
    val errors: ErrorsResponse?
) {
    data class ErrorsResponse(
        val data: List<String>?
    )

    class Deserializer : ResponseDeserializable<YourResponse> {
        override fun deserialize(content: String): YourResponse? =
            Gson().fromJson(content, YourResponse::class.java)
    }
}
```
If you parse this JSON in interactor like
`api.getJson().awaitObjectResponse(YourResponse.Deserializer()).third`,

you will receive `java.lang.ClassCastException: com.google.gson.JsonSyntaxException cannot be cast to com.github.kittinunf.fuel.core.FuelError`, 

while a real exception is `com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 24 path $.errors`.

It wastes much time to understand in a case of long JSON.

**Comment by SleeplessByte** [comment]
Are you on 1.16.0?

**Comment by CoolMind** [comment]
@SleeplessByte yes. Maybe I wrote too short, and some more information has been lost.

**Comment by SleeplessByte** [comment]
#500 #515

**Comment by CoolMind** [comment]
For those who will get this exception, you can search an error this way.

Open your interactor, find `Deserializer` there. Then open response structure (in the example above it is `data class YourResponse`). In deserialize method temporarily replace `content` variable with your JSON response string. You can get this JSON with Postman or any other application.

**Comment by CoolMind** [comment]
Strange, but last hint didn't help me again. So, I got a crash, replaced a `content` with JSON, then removed some lines and compiled, until found a wrong line in JSON.
