### ISSUE TITLE
No easy way to add parameters to query for POST

### ISSUE THREAD

**Issue by dalewking** [kittinunf/Fuel#546]
# Feature Request

## Description
Need to be able to add parameters to the URL of a POST request that has a JSON body. The only way to do it is for me to encode the query into the path string.

## Proposed Solution
A way to have parameters for a POST to put the parameters into the URL and not assume that parameters automatically means form data where the body contains the query.

## Alternatives I've considered
Going to the extra work to build query string into the path string..

## Additional context
I don't control the API I am talking to and barely even have any documentation so I cannot investigate alternatives to using parameters in the URL for this API.

**Comment by SleeplessByte** [comment]
👍 yes we need this

**Comment by dalewking** [comment]
The workaround I am using now is to do:

    "https//baseurl.com"
        .httpGet(urlParams)
        .path
        .httpPost(Collections.emptyList())
        .jsonBody(json)
        ...
