### ISSUE TITLE
Support Paging Library with DataSource

### ISSUE THREAD

**Issue by HarryTylenol** [kittinunf/fuel#547]
# Feature Request

## Description
LiveData with Fuel is awesome integration.
I think it will be also great with Paging Library for api pagination. (DataSource, PagedList)

## Proposed Solution

```kotlin
data class User(val key : String)
// ...

val pageSize = 20

val staticParams = listOf("limit" to pageSize)
val request = "https://...".httpGet(staticParams)

val onLastItemLoaded = { last : User -> listOf(*staticParams, "next" to user.key) }
val config = PagedList.Config.Builder().setPageSize(pageSize).build()

val source = request.dataSource<String, User>(dynamicParams : onLastItemLoaded)

val pagedList = source.toLiveData(config)

// or

val pagedList = request.livePagedList<String, User>(config, dynamicParams : onLastItemLoaded)

```
## Alternatives I've considered
I have no idea.
I think it can't append query parameters dynamically.

## Additional context
Thanks.

**Comment by SleeplessByte** [comment]
Hi there,

Can you link to DataSourxr and PagedList and the Paging library?

**Comment by HarryTylenol** [comment]
https://developer.android.com/topic/libraries/architecture/paging/

here it is. thanks!

**Comment by kittinunf** [comment]
But out of the top of my head, I don't think it fits well into the Fuel repo though. I think it is more like a child repo where it should have someone who really commits to this to maintain it. I would rather leave Fuel (even the extension) as it is unless we have something really ubiquitous.

**Comment by HarryTylenol** [comment]
> But out of the top of my head, I don't think it fits well into the Fuel repo though. I think it is more like a child repo where it should have someone who really commits to this to maintain it. I would rather leave Fuel (even the extension) as it is unless we have something really ubiquitous.

Ok thanks. I will share gist when my extensions are stable. Thanks! 👍

**Comment by kittinunf** [comment]
@HarryTylenol and let me know when you have something stable and ready to share. I am happy to provide a link from the main repo to your repo or gist for the sake of more visibility. Thanks! 

I will close this, but feel free to continue the discussion if you have something.
