### ISSUE TITLE
Can we post hashMapOf?

### ISSUE THREAD

**Issue by mbalex99** [kittinunf/Fuel#56]
What's the recommended way to post a hashMapOf literal.

Like so 

```kotlin


val payload = hashMapOf("username" to username, "password" to password)

Fuel.post(url).body(payload)

```

But it only seems to take a byte array.

**Comment by kittinunf** [comment]
If your server can accept body in format of `foo1=bar1&foo2=bar2`, you could send through param of POST, ie. `Fuel.post(url, listOf("foo1" to "bar1", "foo2" to "bar2")`. 

 Otherwise, you will need a JSON serializer to convert your `HashMap` into `String`, notable libraries are GSON, Jackson.

**Comment by yoavst** [comment]
closing this as you can use those two options:
`listOf("foo1" to "bar1", "foo2" to "bar2")`
or if you receive map:
`map.toList()`
