### ISSUE TITLE
OutOfMemoryError when uploading file

### ISSUE THREAD

**Issue by franciscoaguirre** [kittinunf/fuel#564]
Hi everyone!

I am trying to upload a video in android using Fuel.
Everything works fine for small videos but for large ones I get an OutOfMemoryError.
The upload appears to happen until a certain point (seen in the progress bar), then the error is thrown and it stops.
I saw a similar issue related to downloading files and tried to fix the error based on it but unfortunately couldn't.

**Code:**
```kotlin
Fuel.upload("/videos")
        .source { request, url -> videoFile }
        .name { "video" }
        .progress { readBytes, totalBytes ->
            if (totalBytes.toFloat() != 0f) {
                val progress = readBytes.toFloat() / totalBytes.toFloat() * 100
                runOnUiThread { progressBar.progress = progress.toInt() }
            }
        }
        .responseJson { request, response, result ->
            result.fold(
                success = { json -> "Done!" },
                failure = { error -> Log.e("Failure", error.toString()) }
            )
        }
```

Any help would be gladly appreciated!

**Comment by SleeplessByte** [comment]
Hi there,

This should have been fixed, but maybe it's not in the latest release! It's not supposed to retain the file in memory, but there used to be an error with progress + large files. See if the error goes away if you remove the `.progress` function. If that solves it, you can use that until we release 2.0.0.

**Comment by SleeplessByte** [comment]
My guess it's then how sources are handled in the old code.

https://github.com/kittinunf/Fuel/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Fuel+2.0%22 only a few more issues left!

**Comment by kittinunf** [comment]
Fuel 2.0 has been released though. @franciscoaguirre Can you see whether this issue can be closed? THanks!

**Comment by franciscoaguirre** [comment]
I checked and it works now! Thanks! Closing the issue

**Comment by SleeplessByte** [comment]
Thank you for taking the time to check this @franciscoaguirre
