### ISSUE TITLE
Can upload a file with params ?

### ISSUE THREAD

**Issue by h2oiswater** [kittinunf/Fuel#57]
Dear kittinunf:
    I want to upload a file with some params,such as user_id.
    I used like these, but the server can't get user_id.

```
    url.httpUpload(Method.POST,params)
            .source {
                request, url ->
                return@source file
            }
            .responseJson {
                request, response, result ->

    }
```

**Comment by h2oiswater** [comment]
I found UploadTaskRequest' body only add fileParam

![qq 20160302220255](https://cloud.githubusercontent.com/assets/5397807/13462478/92055bbe-e0c2-11e5-88db-70a4d8ca1d2c.png)

**Comment by yoavst** [comment]
Does `UPLOAD` works with post?
I mean - when you post a file, it should be the body, shouldn't it?

**Comment by h2oiswater** [comment]
yeah
the server got file but not got user_id.

**Comment by yoavst** [comment]
But that make sense. Is it a public api or your api?

**Comment by h2oiswater** [comment]
I successed by okHttp

`override fun doInBackground(vararg sb: Unit): String? {

            val MEDIA_TYPE_PNG = MediaType.parse("image/jpg")
            val client = OkHttpClient()
            var builder = MultipartBody.Builder()


            builder.setType(MultipartBody.FORM)
            builder.addFormDataPart("attach","photo", RequestBody.create(MEDIA_TYPE_PNG, file))

            for( p in params ){
                builder.addFormDataPart(p.key, p.value)
            }

            builder.setType(MediaType.parse("multipart/form-data"))

            val requestBody = builder.build()

            val request = Request.Builder()
                    .url(url)
                    .post(requestBody)
                    .build()

            val response = client.newCall(request).execute()
            if (!response.isSuccessful) {
                return ""
            }

            return response.body().string()
        }`

**Comment by kittinunf** [comment]
Yeah, this sound like a bug to me. We should be able to support this use case.

**Comment by h2oiswater** [comment]
(づ￣ 3￣)づ
fighting!

**Comment by kittinunf** [comment]
Btw, @h2oiswatet would you love to submit PR to solve this?

**Comment by h2oiswater** [comment]
@kittinunf PR means Preview Edition?

**Comment by glureau** [comment]
@h2oiswater means Pull Request.
If you know how to fix this issue, you can clone the repository, update on your side and create a PR, and hen kittinunf will be able to merge your changes in this repository.

**Comment by kittinunf** [comment]
Resolve with #129 

using `name { "<filename>" }` to specify file name in UploadTask
