### ISSUE TITLE
Latest version does not work on Android

### ISSUE THREAD

**Issue by HarryWindsor** [kittinunf/fuel#570]
# Bug Report

## Description
App crashes when I am trying to get data.

## To Reproduce
```Kotlin
package com.example.app

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import com.github.kittinunf.fuel.httpGet
import com.github.kittinunf.result.Result

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        "https://jsonplaceholder.typicode.com/todos/".httpGet().responseString { request, response, result ->
            when (result) {
                is Result.Success -> {
                    println("Result: ${result.get()}")
                }
                is Result.Failure -> {
                    println("Failure")
                }
            }
        }
    }
}
```

### Development Machine
_Complete the following information if applicable_

 - OS: [Windows 10]
 - IDE: [Android Studio]
 - Fuel version: [1.16.0]
 - Kotlin version: [1.2.71]

### Smartphone or Emulator
Emulator

**Comment by iNoles** [comment]
Network on Main Thread?

**Comment by SleeplessByte** [comment]
Hi there.

From logcat, can you tell us what the error is?

Which version are you on? 1.x? Or master?

**Comment by CoolMind** [comment]
Tried this code in a new project, kotlin_version = '1.3.11', device. No errors without Internet permission, downloaded JSON with Internet permission.

**Comment by CoolMind** [comment]
@iNoles, it is not in main thread, Fuel sends requests in worker thread itself.

**Comment by iNoles** [comment]
@CoolMind Android handles it differently than on Desktop.

**Comment by CoolMind** [comment]
@iNoles, do you mean that on emulator we have another behaviour?

**Comment by iNoles** [comment]
Do you don't see those errors on the logcat window without the Internet Permissions or WiFi connected?

**Comment by CoolMind** [comment]
@iNoles, I didn't see any errors in LogCat, a program didn't crash. I think, the author catched an error in another place.

**Comment by SleeplessByte** [comment]
@HarryWindsor we really need more information like the actual error, crash log or something else. 

"It doesn't work" is not something we can solve.

**Comment by SleeplessByte** [comment]
@CoolMind I know; I'm not thát harsch ;) I understand why he does so. Running OSS is exhausting and issues like these are more common than well detailed ones. That said, I'll always give people the chance to amend their question. If @HarryWindsor doesn't reply within the month, I'll close it as `wontfix` until there is more information.

**Comment by kittinunf** [comment]
I guess let's close this as it looks stale at the moment.
