### ISSUE TITLE
Put the latest version in the README

### ISSUE THREAD

**Issue by jmeyers91** [kittinunf/Fuel#572]
# Feature Request

## Description

I'm fairly new to Kotlin and Android development, so maybe this is a stupid issue, but it's frustrating that I want to use this library, but the installation instructions include `<package>:<latest-version>`, so I have to figure out where the actual versions are hidden. After about 5 minutes of navigating around the repo and documentation site, I've found the required Kotlin version, the required Coroutine version, and the latest legacy version, but I'm still clueless about what the current `2.x.y` version is.

I tried `implementation 'com.github.kittinunf.fuel:fuel:2.0.0'`, but apparently there is no version `2.0.0`. I also checked the releases page, but it lacks any `2.x.y` releases.

## Proposed Solution

Put the latest version in the install instructions or somewhere else in the README.

**Comment by jmeyers91** [comment]
Ah that makes sense. I had never heard of jitpack before. But it looks like jitpack only has versions up to `1.16.0` as well:

https://jitpack.io/#kittinunf/fuel

**Comment by SleeplessByte** [comment]
On jitpack, browse to branches, select master and I recommend using the last commit and NOT snapshot, so you get a stable build.

The first time your build might timeout, but should work the second and thereafter.
