### ISSUE TITLE
[ASK] example file upload & post data with fuel

### ISSUE THREAD

**Issue by codenoid** [kittinunf/fuel#576]
when i only define what keys and values for post data & path to file for file upload

**Comment by CoolMind** [comment]
@codenoid, what do you mean? There are some examples in issues. See https://github.com/kittinunf/fuel/issues/479 and https://github.com/kittinunf/fuel/issues/529.

**Comment by SleeplessByte** [comment]
Additionally, check out [upload in `README.md`](https://github.com/kittinunf/fuel/tree/master/fuel#using-multipartform-data-uploadrequest), and the [UploadRequestTests](
https://github.com/kittinunf/fuel/blob/master/fuel/src/test/kotlin/com/github/kittinunf/fuel/core/requests/UploadRequestTest.kt).

**Comment by codenoid** [comment]
@CoolMind is there any example of `HashMap<String, String>()` var usage for form data with file upload ?

**Comment by codenoid** [comment]
```
        var client = AsyncHttpClient();
        var params = RequestParams();
        params.put("file", File("/storage/emulated/0/Telegram/Telegram Images/852237039_126976.jpg"));
        params.put("id", "21")
        client.setBasicAuth("username","password");
        client.post(this, "http://5.5.5.68:2018/api/file-upload", params, object: JsonHttpResponseHandler(){
            override fun onSuccess(statusCode: Int, headers: Array<Header>, response: JSONObject) {
                super.onStart()
            }
        });
```

superb easy

**Comment by CoolMind** [comment]
@codenoid, :)
It is AsyncHttpClient, not Fuel. :) Of course, it works, but I am not sure it will work in coroutines or RxJava.

**Comment by codenoid** [comment]
yes sir @CoolMind , from the example, it's easier to work with AsyncHttpClient

**Comment by CoolMind** [comment]
@codenoid, ah, understood. Probably it's easier, also you can try Retrofit. I was not right, AsyncHttpClient is compatible with RxJava. Good luck!
