### ISSUE TITLE
Could not work on web

### ISSUE THREAD

**Issue by lmylr** [kittinunf/fuel#579]
Error:(10, 2) Kotlin: Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

**Comment by kittinunf** [comment]
@lmylr Can you possibly give us more infor on this? Can you also try the latest version?

**Comment by kittinunf** [comment]
I guess we can close this. Please feel free to re-open this anytime, if you have more info to support your issue. Thanks!
