### ISSUE TITLE
Is it possible to get PHPSESSID ?

### ISSUE THREAD

**Issue by dvlwj** [kittinunf/fuel#580]
Hello guys,

I got a project where i need to do a captcha request, where i need to get PHPSESSID from the API and store it to the cookie.  
  
Is it possible? thanks.

**Comment by NikkyAI** [comment]
cookies are just fancy http headers:
add a header; `Cookie` as described here: https://stackoverflow.com/a/3467146/9006779

maybe we should add some helper methods for that

**Comment by dvlwj** [comment]
@NikkyAI Sorry for late respond. I see, i got it now.  
Thanks.
