### ISSUE TITLE
serialization does not work on 2.0.0

### ISSUE THREAD

**Issue by NikkyAI** [kittinunf/fuel#582]
# Bug Report

## Description
the kotlinx-serilaization dependency was not updated
and who knows why you cannot mix 0.9.1 and 0.10.0 of serialization because

## To Reproduce
depend on both `rg.jetbrains.kotlinx:kotlinx-serialization-runtime:0.10.0`
and Fuel 2.0.0

building will throw a error like this:

`Cannot access class 'kotlinx.serialization.json.JSON'. Check your module classpath for missing or conflicting dependencies`

run `./gradlew dependencies`
fuel:fuel:2.0.0 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.9.1 -> 0.10.0 (*)
```

## Expected behavior
using the correct dependency and avoiding missing classes

**Comment by SleeplessByte** [comment]
Try it with transitive dependencies off! (On the fuel module).

If that works let's add it to the readme

**Comment by NikkyAI** [comment]
the problem is not the dependency but that the serialization library has a `typealias Json = JSON` and that now points to a nonexistant class

**Comment by SleeplessByte** [comment]
Ah. Can we remove that?

**Comment by NikkyAI** [comment]
well updating serilization fixes it.. see referenced PR

kotlinx-serialization 0.10.0 is the companion release to kotlin 1.3.20 anyway

**Comment by SleeplessByte** [comment]
Perfect. Let's merge it asap. I'll approve it when I get home and ping
kittinunf
