### ISSUE TITLE
Response.statusCode returns -1

### ISSUE THREAD

**Issue by angelrc96** [kittinunf/fuel#586]
# Bug Report

## Description
I'm not sure if this could be considered a bug, but what happens to me is that sometimes when I send a post request then the response statusCode is -1. This value is only returned when the post request is not sent to the destination.

What does this -1 value mean? Because it is not a http response code.

This is my method:
```Kotlin
internal fun sendHttpPostRequest(TAG: String, endpoint: String): Promise<Long, Exception> {
        LogManager.info(TAG,"sendHttpPostRequest()")

        var statusCode: Int
        val def = deferred<Long, Exception>()

        try{
            Fuel.post(endpoint).response { request, response, _ ->
                LogManager.info(TAG, "Endpoint msg sent: ${request.url}")
                statusCode = response.statusCode

                if(statusCode == 200) {
                    LogManager.info(TAG, "Response: $statusCode - OK")
                    val data = String(response.data)
                    LogManager.info(TAG, "Response message: $data")
                }else{
                    LogManager.info(TAG, "Something wrong happened sending message. Response: $statusCode")
                }
                def.resolve(statusCode.toLong())
            }
        }catch (exception: Exception){
            LogManager.info(TAG, "Exception thrown! ${exception.stackTrace}")
            def.reject(exception)
        }

        return def.promise
    }
```

### Development Machine
_Complete the following information if applicable_

 - OS: [Windows 10]
 - IDE: [Android Studio]
 - Fuel version: [fuel-android:1.15.0]
 - Kotlin version: [1.2.61]

### Smartphone or Emulator
_Complete the following information if applicable_

 - Device: [Huawei Watch 2]
 - OS: [Android 8.0.0 and Wear OS 2.0]

**Comment by iNoles** [comment]
Is this is for JavaScript?

**Comment by angelrc96** [comment]
> Is this is for JavaScript?

No, it is not. It is Kotlin. I needed to use Promises for other purpose

**Comment by SleeplessByte** [comment]
You already answered your own question:

> This value is only returned when the post request is not sent to the destination.

The status code -1 is used if it didn't even make it to the network layer!

**Comment by angelrc96** [comment]
Got it. So it's like a default value that is returned when something went wrong sending the request. I was doing some tests and I found out that it's due to Android Doze mode. Because sometimes network requests are delayed and once the task gets back the CPU, it doesn't have network connection or something like that

**Comment by SleeplessByte** [comment]
You can probably actually capture this:
```kotlin
Fuel.post(endpoint)
  .response { request, response, result ->
      val (bytes, error) = result
      if (error != null) {
        // here you have a wrapped error in FuelError that will tell you why the request failed. 
      }
  }

// Alternative way
Fuel.post(endpoint)
  .response { request, response, result ->
    when (result) {
      is Result.Failure -> {
        val ex = result.getException()
      }
      is Result.Success -> {
        val data = result.get()
      }
  }
``` 

Check [here](https://github.com/kittinunf/Result) how you can use our result. **Note**: you need to manually import this or it will use kotlin's built in result.
