### ISSUE TITLE
Forbidden status at reqres.in

### ISSUE THREAD

**Issue by demisgomes** [kittinunf/fuel#587]
# Bug Report

## Description
When i make a single HTTP request to Req | Res API (https://reqres.in/), the request is forbidden.

## To Reproduce
val second=Fuel.get("https://reqres.in/api/users?page=2").response().second
println(second)

second will return an HTML page which says:

Please enable cookies.
Error 1010 Ray ID: <id>• <datetime> UTC
Access denied
What happened?
The owner of this website (reqres.in) has banned your access based on your browser's signature (<id>-ua21).

Cloudflare Ray ID: <id> • Your IP: <ip> • Performance & security by Cloudflare
```

IntelliJ 2018.3.1
Windows 10

Errors both in 1.15 and 2.0 fuel versions

**Comment by SleeplessByte** [comment]
This is an issue with [`reges.in`](https://github.com/benhowdle89/reqres). You probably need to manually set a `User-Agent` to something they allow.
