### ISSUE TITLE
Manager

### ISSUE THREAD

**Issue by glureau** [kittinunf/Fuel#59]
Hi guys!
First of all, well done for this very convenient library! Really cool to use :)
But I'm not super fan of the Manager, I don't like the static but it's super convenient here so ok, but the name...
Is it possible to rename it FuelManager or something like this?

**Comment by kittinunf** [comment]
That's right. `Manager` is a static wrapper to use `Fuel` conveniently. Yeah, come to think about it plain `Manager` might be a bit too generic. I think `FuelManager` is a good alternative.

**Comment by yoavst** [comment]
Opening this as it seemed to be reverted.
