### ISSUE TITLE
[ASK] Is it possible to post data and file upload with Fuel like OkHttp ?

### ISSUE THREAD

**Issue by Jirayu4R7** [kittinunf/fuel#594]
![image](https://user-images.githubusercontent.com/12969885/52397669-df618400-2ae8-11e9-9b4f-23343e389aa3.png)

![image](https://user-images.githubusercontent.com/12969885/52397712-04ee8d80-2ae9-11e9-9314-7909b872714d.png)

**Comment by kittinunf** [comment]
Have you checked our documentation? https://fuel.gitbook.io/documentation/core/fuel#using-multipart-form-data-uploadrequest. More specifically, 

``` kotlin
Fuel.upload("/post")
    .add(
        FileDataPart(File("myfile.json"), name = "files[]", filename="contents.json"))
    )
   .response { result ->
   }
```

**Comment by kittinunf** [comment]
I guess I will close this issue.

**Comment by Jirayu4R7** [comment]
Thank you so much.
