### ISSUE TITLE
can't load via gradle

### ISSUE THREAD

**Issue by amiracam** [kittinunf/fuel#598]
# Bug Report
Can't check out Fuel
## Description
added to build.gradle after confirming it existed in maven repo
compile group: 'com.github.kittinunf.fuel', name: 'fuel', version: '2.0.1'
## To Reproduce
just add to build gradle and run build

Stack:

> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.kittinunf.fuel:fuel:2.0.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/kittinunf/fuel/fuel/2.0.1/fuel-2.0.1.pom
       - https://repo.maven.apache.org/maven2/com/github/kittinunf/fuel/fuel/2.0.1/fuel-2.0.1.jar
     Required by:
         project :

**Comment by iNoles** [comment]
looks like you have just mavenCentral(). You need to add jcenter() too.

**Comment by kittinunf** [comment]
Can we have some feedback on this?

**Comment by carlos-mg89** [comment]
@amiracam are you using Kotlin 1.3.20 or higher?

In my case, changing the `build.gradle` with this fixed the matter:

```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.20'
}
```

**Comment by kittinunf** [comment]
It looks stale to me. Let's close then. But please feel free to re-open if you have any other development on the matter.
