### ISSUE TITLE
[Question] Why header value always array of string instead of normal string ?

### ISSUE THREAD

**Issue by davidasync** [kittinunf/fuel#599]
Is there any way to send header value as normal string instead of array of string ?

for example  `{Origin=abc, Content-Type=application/json`instead of`{Origin=[abc], Content-Type=[application/json]`

**Comment by SleeplessByte** [comment]
It will always _send_ the headers as a string, but when printing them it shows the internal representation. Headers are collapsed into a single value (if possible) when they enter the HttpUrlConnection.

The reason it's always an array is that most headers actually allow multiple values.
