### ISSUE TITLE
Base64 decoding is wrong

### ISSUE THREAD

**Issue by dineshvg** [kittinunf/fuel#607]
# Bug Report

## Description
The base64 decoding done by this library provides incomoplete results. 

## To Reproduce

1. Use this example base64 encoded string: 
H4sIANsUgVwA_w3MMQ7CMAwF0Lt4ZojbELtsfLu5RxV5AlGJZEPcPR3f8n50tBa9j_MVH3oQK_JSVTZniMqTDdWMNWXBtl5ePTkWFEfZRYrpntizZ_HquINu1OMdbZzfaxvRB_0nLxS6rmQAAAA
Use CyberChef to test: https://gchq.github.io/CyberChef/

```Kotlin
// Provides partial result 
val encodedByteArray = base64String.decodeBase64()
val decodedString = encodedByteArray.inputStream()).reader().readText()

// this provides unreadable results
val encodedByteArray = base64String.decodeBase64ToString()

```

## Expected behavior
{"accesstoken":"18B42F879D1B787A1CBFCC18047B937A13D0DB2B6DB6E776C8E01D4D47DFDB5B","selector":"test"}", but the selector is always null
If we use Java 8 base64 decoder the correct results are obtained.

## Additional context
The idea was to use a complete Java8 independant solution, and that is why Fuel was tried.

**Comment by SleeplessByte** [comment]
I think your encoded value is incorrect.

https://www.base64decode.org/
```
\sCt.6..Q^@bYGw-c1QITٞ#*L7V0՗yxXQe+{b͑긃nmkI.
```

**Comment by dineshvg** [comment]
![screenshot 2019-03-07 at 14 11 00](https://user-images.githubusercontent.com/9593739/53959127-14aac300-40e3-11e9-8faf-7334396d99b3.png)

Use cyberChef and check it

**Comment by SleeplessByte** [comment]
I don't care about cyberchef.

Your input string fails with ALL general implementations:

```javascript
window.atob("H4sIANsUgVwA_w3MMQ7CMAwF0Lt4ZojbELtsfLu5RxV5AlGJZEPcPR3f8n50tBa9j_MVH3oQK_JSVTZniMqTDdWMNWXBtl5ePTkWFEfZRYrpntizZ_HquINu1OMdbZzfaxvRB_0nLxS6rmQAAAA")
// Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```

The correctly encoded string is (according to `window.btoa`):
```
"eyJhY2Nlc3N0b2tlbiI6IjE4QjQyRjg3OUQxQjc4N0ExQ0JGQ0MxODA0N0I5MzdBMTNEMERCMkI2REI2RTc3NkM4RTAxRDRENDdERkRCNUIiLCJzZWxlY3RvciI6InRlc3QifQ=="
```

Your Cyberchef tool says the same:

![image](https://user-images.githubusercontent.com/1964376/53959389-cf3ac580-40e3-11e9-9fb7-c7a3f623b0b7.png)


The problem is that you are expectin gzip to unzip AFTER it decodes the string. That's not how headers work.

**Comment by SleeplessByte** [comment]
In short: this has nothing to do with fuel or the base64 encoding. You are decoding a base64 encoded gzipped string. If you unencode it but don't ungzip it, of course the result is going to be something else.
