### ISSUE TITLE
Could you write a copy in Chinese .Md file?

### ISSUE THREAD

**Issue by 1432886945** [kittinunf/fuel#608]
# Bug Report

## To Reproduce

```Kotlin
// Test case or sample that shows broken behaviour and expected behaviour
```

### Development Machine
_Complete the following information if applicable_

 - OS: [e.g. Windows 10]
 - IDE: [e.g. Android Studio, IntelliJ, Eclipse]
 - Fuel version: [e.g. 1.15.0]
 - Kotlin version: [e.g. 1.2.51]

### Smartphone or Emulator
_Complete the following information if applicable_

**Comment by kittinunf** [comment]
We would love to but afaik, we don't know Chinese well enough to do that .... , I would be happy to merge the PR if you can help us 🇨🇳

**Comment by kittinunf** [comment]
I will close this issue but feel free to reopen if you have more development.
