### ISSUE TITLE
Custom Moshi Instance

### ISSUE THREAD

**Issue by ProjectZed** [kittinunf/fuel#609]
# Feature Request

## Description
My network requests utilize the following function: `.rxResponseObject(deserializable = moshiDeserializerOf(clazz = responseType))`. However, not all of my Moshi JsonAdapters are created via CodeGen. I have a custom JsonAdapter for DateTime types (specifically Instant). The response fails to be parsed with `JsonDataException: Expected BEGIN_OBJECT but was STRING at ...`. The reason being, my custom adapter is contained in a Moshi instance I have internally however, `moshiDeserializerOf` creates it's own instance of Moshi which doesn't have my custom adapter added.

## Proposed Solution
A simple change to the `moshiDeserializerOf` function as such:
```
fun <T : Any> moshiDeserializerOf(clazz: Class<T>, moshi: Moshi? = null) = object : ResponseDeserializable<T> {
    override fun deserialize(content: String): T? = (moshi ?: Moshi.Builder()
                .build())
                .adapter(clazz)
                .fromJson(content)
}
```
## Alternatives I've considered
Since `responseType` is an input provided to the interface I have with Fuel, I can conditionally route response parsing to my own Moshi instance if it is for Instant types, other proceed with the standard deserializer. This solution does not scale very well and is counter to Moshi's self management of JsonAdapters via CodeGen

**Comment by iNoles** [comment]
There is already ``` moshiDeserializerOf(adapter: JsonAdapter<T>)``` that you can uses

**Comment by ProjectZed** [comment]
`.rxResponseObject(deserializable = moshiDeserializerOf(adapter = moshi.adapter<R>(responseType)))` would have been a beautiful solution. However `moshiDeserializerOf` is an inline reified function which doesn't work with the generic interface I have (at least not to my knowledge).

```
interface INetworkService {

    fun <R : Any> get(endpoint: String, parameter: Map<String, Any?>? = null, responseType: Class<R>): Single<R>

}
```

**Comment by kittinunf** [comment]
I think it looks like a good solution! Would you mind open a PR for this?
