### ISSUE TITLE
Problem to sign release apk since android studio & build tools - 3.3.2

### ISSUE THREAD

**Issue by xdma** [kittinunf/fuel#611]
# Bug Report

## Description
Problem to sign release apk with json library "com.github.kittinunf.fuel:fuel-json:2.0.1", see the detailed error below.

## To Reproduce
try to sign apk with last android studio & build tools 3.3.2 + "com.github.kittinunf.fuel:fuel-json:2.0.1" library.

## Build error:
Error: json defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]

   Explanation for issues of type "DuplicatePlatformClasses":
   There are a number of libraries that duplicate not just functionality of
   the Android platform but using the exact same class names as the ones
   provided in Android -- for example the apache http classes. This can lead
   to unexpected crashes.

   To solve this, you need to either find a newer version of the library which
   no longer has this problem, or to repackage the library (and all of its
   dependencies) using something like the jarjar tool, or finally, rewriting
   the code to use different APIs (for example, for http code, consider using
   HttpUrlConnection or a library like okhttp).

1 errors, 0 warnings

FAILURE: Build failed with an exception.

### Development Machine
 - OS: [e.g. Windows 10]
 - IDE: [Android Studio]
 - Fuel version: [e.g. 2.0.1]
 - Kotlin version: [e.g. 1.3.21]

### Smartphone or Emulator
 - Device: [Samsung s8, LG G6]
 - OS: [8]

**Comment by iNoles** [comment]
Workaround would be like 
```
configurations {
    all {
        exclude group: 'org.json', module: 'json'
    }
}
```
in Android projects.

**Comment by L4grange** [comment]
Thanks @iNoles ! Is the workaround safe for a production release?

**Comment by iNoles** [comment]
You may not needed it anymore. You can always check.

**Comment by L4grange** [comment]
I had the issue on a build today and with your workaround I've managed to complete the build. So far no issues with my testing! Thank you!

**Comment by kittinunf** [comment]
Let's close this then 👍
