### ISSUE TITLE
A connection to URL was leaked. Did you forget to close a response

### ISSUE THREAD

**Issue by easazade** [kittinunf/fuel#620]
## Problem
this is the warning i get in my logcat
`A connection to http://turkishads.com/ was leaked. Did you forget to close a response `

## My Code 

````kotlin
val (_, response, result) = "insertpost".httpUpload(parameters = params)
      .add(*dataParts.toTypedArray())
      .responseString()
````
i think this error only happens when the request is not successful
in libraries like `okhttpclient` we are always needed to make sure responseBody
is closed which is done like this 
 ````kotlin
 body.close()
 ````
how can i do the same with fuel 
or is there any other solution to resolve this warning

**Comment by SleeplessByte** [comment]
Hi there!

In case of an error you need to "read" the error response to fix this warning. The error message will have a body. Once it's read once, this warning goes away.

**Comment by easazade** [comment]
so this is the code i'm using :
````kotlin
fuelError.response.body().asString("")
````

**Comment by SleeplessByte** [comment]
That seems ok -- still have an error with that?
