### ISSUE TITLE
Error on get() method

### ISSUE THREAD

**Issue by lionlollipop** [kittinunf/fuel#627]
The same codes were working fine until the update from version 1.9.0 to 2.0.1.
Error showing at the get method and I am not sure how to solve it.

```
String quotesURL = "https://api.forismatic.com/api/1.0/" + "?method=getQuote&format=text&lang=en";

         Fuel.get(quotesURL).responseString(new Handler<String>() {
                    @Override
                     public void success(String quote) {
                             nameList.add(quote);
...
```
![image](https://user-images.githubusercontent.com/49994672/56758755-f8b1cc80-67c9-11e9-8470-3aa058fea307.png)
Errors:
![image](https://user-images.githubusercontent.com/49994672/56758781-08311580-67ca-11e9-95b4-81c2a04b461e.png)

 - OS: Windows 10
 - IDE: Android Studio
 - Fuel version: 2.0.1

Please help :(

**Comment by kenrube** [comment]
Try `Fuel.get(quotesUrl, null)`. Second argument is for parameters. When you call this method from Kotlin you can omit second parameter (it is null by default) but you use Java, so must declare null explicitly.

Another (better) solution is to add annotation @JvmOverloads to method `get`. I think so

**Comment by lionlollipop** [comment]
Thank you! You are my savior!

It works after I put null as the second parameter and use Fuel instance!

```Fuel.INSTANCE.get(quotesURL, null).responseString(new Handler<String>() { ... ```

**Comment by SleeplessByte** [comment]
> Another (better) solution is to add annotation @JvmOverloads to method get. I think so

We've removed all Interopt like that and support only Kotlin as a first-class citizen.
