### ISSUE TITLE
README should explicitly mention Result dependency

### ISSUE THREAD

**Issue by mikelangdon** [kittinunf/Fuel#64]
This might be my fault for not building with Gradle, but I spent too much time puzzling over why the basic examples would not build for me.

My suggestion is to reference [Result](https://github.com/kittinunf/Result) prominently in the README as a dependency.

**Comment by kittinunf** [comment]
Oh. I am truly sorry to hear that. Yeah, you are right. `Result` is the tiny library to hadle success/failure operation. I will fix that tonight. Or even better if you could PR to fix that for me. Anyhow, thanks for reporting this.

**Comment by kittinunf** [comment]
I have addressed your issue. :+1: for letting me know of this.
