### ISSUE TITLE
Google/Jcenter/Maven Dependencies broken

### ISSUE THREAD

**Issue by Clemon-R** [kittinunf/fuel#644]
# Bug Report

## Description
The dependencies is not working on gradle

## To Reproduce
All need to add the dependencies in your build.gradle

You can check here : https://jcenter.bintray.com/com/github/kittinunf/fuel/fuel/2.2.0/fuel-2.2.0.pom
Or here : https://repo.maven.apache.org/maven2/com/github/kittinunf/fuel/fuel/2.2.0/fuel-2.2.0.pom
Or again here : https://dl.google.com/dl/android/maven2/com/github/kittinunf/fuel/fuel/2.2.0/fuel-2.2.0.pom

## Expected behavior
That the dependencies is installed in my project

## Environment
Ubuntu with Intellij

### Development Machine
_Complete the following information if applicable_

 - OS: Ubuntu
 - IDE: Intellij
 - Fuel version: 2.1.0 and 2.2.0
 - Kotlin version: 1.3.31

**Comment by SleeplessByte** [comment]
2.2.0 is not released. The rest seems to be working just fine:

https://dl.bintray.com/kittinunf/maven/com/github/kittinunf/fuel/fuel/2.1.0/
https://bintray.com/kittinunf/maven/Fuel-Android/2.1.0
https://mvnrepository.com/artifact/com.github.kittinunf.fuel/fuel/2.1.0

**Comment by Clemon-R** [comment]
Thank, but i don't know why until from 10 minutes, all the repos on 2.1.0 were 404 not found.

**Comment by SleeplessByte** [comment]
I don't think we're on the ones you posted :)
