### ISSUE TITLE
Corountines-Based Fuel

### ISSUE THREAD

**Issue by iNoles** [kittinunf/fuel#646]
This going to be a huge rewrite. I definitely going to need help for it. 

- [x] Port Fuel HTTP Client to Corountines-based
- [ ] Platform Configurations 
- [ ] Maybe Multiplatforms Support

Is there is anything else to be added?

**Comment by iNoles** [comment]
It is now tracked on the coroutines branch.

I need somebody to help with the response-related functions. 
https://github.com/Kotlin/kotlinx-io is very useful for multiplatform IO library such as ByteArray and InputStream on JVM side, and JS sides as well.

**Comment by kittinunf** [comment]
I think this might be a good idea to kick off Fuel 3.x and it might require a major rewrite while maintaining the version 2. What do you think?

**Comment by iNoles** [comment]
Heh, slowly doing testing now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SleeplessByte** [comment]
Yes, version 3!

**Comment by iNoles** [comment]
Moved to  #760
