### ISSUE TITLE
how to set used HTTP version ?

### ISSUE THREAD

**Issue by yannou38** [kittinunf/fuel#647]
Hello,

I'm looking at how i can select which protocol to use with fuel, to no avail for now.

Could someone nudge me in the right direction ?

Thanks in advance,
Yann

**Comment by kittinunf** [comment]
Could you show us what have you tried? I guess you just passing the "http" url, right?

**Comment by yannou38** [comment]
Sorry, my issue wasn't due to this problem actually and I forgot to close it.

My problem was sending a get request with a body. That caused kotlin to not send the body and the receiving end would crash
