### ISSUE TITLE
Expose package fuel-test

### ISSUE THREAD

**Issue by Parvathymenon25** [kittinunf/fuel#648]
# Feature Request
Expose package fuel-test

## Description
Capability to reuse the Mockhelper created in the fuel-test package

## Proposed Solution
Produce fuel-test artifact.

**Comment by kittinunf** [comment]
I believe it is relatively simple to roll your own for that use-case. I don't think we are gonna publish that for public use. 🙏 

I will close this down, as solved for "won't fix" but please let me know if you wanna discuss further.

**Comment by SleeplessByte** [comment]
@Parvathymenon25 since this is licensed as MIT, you can just copy MockHelper from  `fuel-test`.
