### ISSUE TITLE
How many `FuelManager.instance` per context?

### ISSUE THREAD

**Issue by leo7** [kittinunf/fuel#649]
### The issue is
I want to use this lib to handle multiple http requests to different base urls, like `Fuel.post(url)` asynchronously in coroutines. Is this thread/coroutine safe and efficient? Will coroutines share the same `FuelManager`?

**Comment by SleeplessByte** [comment]
Don't use the global `.instance`. Instead, create a `new FuelManager()`.

**Comment by leo7** [comment]
Got you, thanks @SleeplessByte
