### ISSUE TITLE
`cancel()` doesn't cancel the underlying HTTP request.

### ISSUE THREAD

**Issue by yoavst** [kittinunf/Fuel#65]
the `HttpUrlConnection` or `HttpClient` should be closed also.

> My request is a Comet – after request is sent the server keeps it for 30 seconds and either respond with array of events if these events has occured, or respond with empty array if there was no events.
> So my case is this:
> 1. request sent
> 2. in 2-5 seconds I perform a cancellation
> 3. nothing is cancelling (according to the mitmproxy) and after the timeout the success handler is calling

**Comment by carmas123** [comment]
@yoavst this is very hard to be done...because there is no reference with physical connection (to shutdown)

**Comment by yoavst** [comment]
I did take a look on this case. It seems very complicated to implement it, but I think this is the right thing to do.

**Comment by carmas123** [comment]
Oh yes...this is very important...
As soon as I have some time I make a fork and inspect how we can do that.

**Comment by yoavst** [comment]
Probably will not be fixed:
```
/As per Android documentation, a connection that is not explicitly disconnected
//will be pooled and reused!  So, don't close it as we need inputStream later!
//connection.disconnect()
```

**Comment by RowanG1** [comment]
The features in Fuel readme page says that cancel is included as function?

**Comment by SleeplessByte** [comment]
That is correct, on async requests. It will correctly stop your callbacks and/or deserializers from receiving the data and saving processing time.

**Comment by RowanG1** [comment]
Okay, so the request can be cancelled if the request has not started yet- you define async request as a delay between request creation, and request execution. The library is so easy to use, but being unable to cancel the callbacks after request start is a fatal flaw.

**Comment by SleeplessByte** [comment]
No? You can cancel in-flight requests.

**Comment by RowanG1** [comment]
See original issue above: "nothing is cancelling (according to the mitmproxy) and after the timeout the success handler is calling"
I have the same problem. I keep a reference in class for the request. I cancel the request, but the success handler is still called after cancellation.

**Comment by SleeplessByte** [comment]
That might be a bug. A _lot_ has changed since the original issue. Would you be so kind to open a new one with a reproducible example?

**Comment by RowanG1** [comment]
I have the time to log a new issue, but not for example code.
