### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by Cortlandd** [kittinunf/fuel#652]
The documentation discusses adding multipart/form-data. But what about adding a request that takes multiple files (not 1 big file in separate parts) as input. See html example below. I've been trying to do this in fuel but simply get bad request.

```html
<form action="/post">
  <input type="file" name="image1">
  <input type="file" name="image2">
  <input type="submit" value="Submit">
</form> 
```

**Comment by SleeplessByte** [comment]
Multiple files is the same as adding multiple parts with _different names_. Using multiple parts _with the same name_ will merge them into 1 file at the end.

**Comment by Cortlandd** [comment]
Then here, why does my server return 400 bad request? I'm passing 2 files with the specified input name. Same thing in postman and it works. Where am I going wrong?

```kotlin
fun imageUpload(image1: File, image2: File) {

        Fuel.upload("/path", method = Method.GET)
                .add(
                    FileDataPart(image1, name = "image1"),
                    FileDataPart(image2, name = "image2")
                )
                .response { result -> 
                    println(result)
                }

    }
```

**Comment by Cortlandd** [comment]
To give more context. My backend is written in python/flask. the code below is essentially a request which expects image1 and image2 to be file inputs with the names image1 and image2.

```python
@app.route('/path')
def makeup_transfer():

    image1 = request.files['image1']
    image2 = request.files['image2']

```

**Comment by SleeplessByte** [comment]
That's a good question and I don't have a perfect answer :O.

I think it would be good to compare what it sends / receives in the fuel case and in the postman case. Would you be able to get those 2 datapoints?

**Comment by Cortlandd** [comment]
`I think it would be good to compare what it sends / receives in the fuel case.`
Where exactly? The request header or...?

Also note the files I was sending was created through File.createTempFile().

**Comment by Cortlandd** [comment]
Figured it out.

```kotlin
doAsync {
              Fuel.upload("/post").add(
                      FileDataPart(n!!, "image1_file", "image1.png", "image/png"),
                      FileDataPart(m!!, "image2_file", "image2.png", "image/png")
              ).responseObject(RequestResponse.Deserializer()) { result ->
                  when (result) {
                      is Result.Success -> {
                          println("Success")
                      }

                      is Result.Failure -> {
                          println("Failed")
                      }
                  }
              }
          }
```
