### ISSUE TITLE
Request's parameter field in RequestInterceptor is empty

### ISSUE THREAD

**Issue by leonhsu1** [kittinunf/fuel#655]
When intercepting the request, the parameter field is empty. I'm guessing that before the request interceptor intercepts the request, Fuel already takes the parameter field and puts it in the URL path.

This makes it difficult to extract the query parameters because now I have to go to the URL parameter, take the string of the query param and break it down to a map<String, String>.

```
   override fun invoke(next: RequestTransformer): RequestTransformer = { request ->
        logger.info("${request.parameters}") // Is empty

       logger.info("${request.url.query}") // prints out the query params
       next(request)
   }
```

Can it be changed so that the query parameters remain in the parameters field and after we have intercepted the request, Fuel can construct the URL?

**Comment by SleeplessByte** [comment]
> When intercepting the request, the parameter field is empty. I'm guessing that before the request interceptor intercepts the request, Fuel already takes the parameter field and puts it in the URL path.

There is an interceptor that takes care of encoding parameters into the url:
https://github.com/kittinunf/fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/ParameterEncoder.kt

And then unsets the parameters:
https://github.com/kittinunf/fuel/blob/7b56b22799905ea3c4b7b26addd84dc978983247/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/ParameterEncoder.kt#L33-L39

It is added by default via the `FuelManager`:

https://github.com/kittinunf/fuel/blob/e85be1a72aef0e5ee138b6482074ce192c340b90/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt#L66-L67

The easiest way to accomplish your goal is to _prepend_ your interceptor to this one. There is **no** convenience method to do that, so you'll have to call:

```kotlin
val manager = new FuelManager() // or FuelManager.instance

manager.removeAllRequestInterceptors()
              .addRequestInterceptor(YourInterceptor)
              .addRequestInterceptor(ParameterEncoder)
```

**Comment by leonhsu1** [comment]
Thanks! Worked great for me.
