### ISSUE TITLE
Set the proxy for each requests

### ISSUE THREAD

**Issue by GitPotTime** [kittinunf/fuel#656]
# Feature Request

## Description
I work a lot with proxies and multiple threads. Currently, the only to use proxies is to set the proxy using `FuelManager.instance.proxy` but this is not for multiple proxies and multiple threads.

## Proposed Solution
The best way is to set the proxy for each requests. 
## Alternatives I've considered
Like this: "https://google.com".sendGet().setProxy("AProxy")`

**Comment by SleeplessByte** [comment]
```kotlin
new FuelManager()
  .also { |it| it.proxy = ... }
  .get("https://google.com")
  .responseXXX
```
Something like this?

**Comment by GitPotTime** [comment]
Yes exactly
