### ISSUE TITLE
Only getting ??? for UTF-8 text

### ISSUE THREAD

**Issue by MitjaHenner** [kittinunf/fuel#658]
Im using Android with Kotlin and fuelAndroid/Gson/Coroutines.

httpPost response gives me:
???
instead of
ไทย

Thats what the InputStreamReader gives me so its not a Gson problem.
The InputStreamReader says ist UTF-8.

I tested the server with ARC where the response was fine.

In the FuelManager baseHeaders I set "Content-Type" to "application/json; charset=utf-8"

**Comment by iNoles** [comment]
According to the specs, default encoding of application/json is UTF-8. What is ARC?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MitjaHenner** [comment]
Sorry, Advanced REST client, a tool like postman.

**Comment by kittinunf** [comment]
Hmm, I use this regularly when interacting with lots of Japanese characters and it works perfectly fine. I believe it should be the same with Thai character.

Could you please help us by posting some snippet of code to demonstrate the problem? If the API is accessible, then it would be awesome!

**Comment by MitjaHenner** [comment]
I used the same API in another project, where its still working fine.
So I removed coroutines and switched back to the same version: 2.0.1.
Still not working, if im not missing something its the exact same code now.
Is there something else that could have changed this?

**Comment by MitjaHenner** [comment]
Sorry, 100% my bad. Was a server issue after all.
