### ISSUE TITLE
HTTPS certificate not validated by default

### ISSUE THREAD

**Issue by jurgisp** [kittinunf/Fuel#66]
By default socketFactory and hostnameVerifier are null, which makes HTTPS connections pointless and is a huge security risk. This should be the default:

```
Manager.instance.socketFactory = javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory()
Manager.instance.hostnameVerifier = javax.net.ssl.HttpsURLConnection.getDefaultHostnameVerifier()
```

**Comment by kittinunf** [comment]
Yeah, thanks for pointing this out @jurgisp. At that time i naively pushed this to be client's responsibility. I agree that using default is a safer choice. Would you mind open to PR to fix this? I am more than happy to merge it in.

**Comment by jurgisp** [comment]
Thanks for quick response. Unfortunately I'm not familiar with the source code enough to know the best place to put the default initialization. From the client perspective I just execute these two lines when the app starts.

**Comment by kittinunf** [comment]
Fair enough. No problem. I will squeeze this in the next release. I will
leave this open as a reminder and close this when it is done.

Thanks for using `Fuel`.
