### ISSUE TITLE
Java URLConnection provides no fail-safe timeout on reads

### ISSUE THREAD

**Issue by 1951FDG** [kittinunf/fuel#660]
Hi,

I'm in need of some advice, after some testing, I finally discovered a bug, where a fuel request would not timeout according to the timeout() or timeoutRead() set.

It happens to be so, Java URLConnection provides no fail-safe timeout on reads. I stumbled upon a couple of articles on how to tackle this:

http://thushw.blogspot.com/2010/10/java-urlconnection-provides-no-fail.html
http://leakfromjavaheap.blogspot.com/2013/12/are-connecttimeout-and-readtimeout.html
https://git.axented.com/billowdood/onesignal-android-sdk/commit/bc9cc32d75883e10cef54bd348e7e05437e2097e

My questions are:

Is there a built-in way in Fuel to tackle this?
If not, can someone provide me with a Kotlin-isque example on how to achieve this?

Any help on this matter is much appreciated :)

My current code is setup like this:

```
val timeout = 500
val timeoutRead = 500
// An extension over string (support GET, PUT, POST, DELETE with httpGet(), httpPut(), httpPost(), httpDelete())
val (_, _, result) = server.httpGet().timeout(timeout).timeoutRead(timeoutRead).responseJson()
when (result) {
    is Result.Failure -> {
    }
    is Result.Success -> {
    }
}
```

This, https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/556, may also be related to this issue

This, https://stackoverflow.com/questions/45280663/httpurlconnection-timeout-seems-to-be-ignored, may also be of info

**Comment by SleeplessByte** [comment]
The problem is that we can't distinguish a hung-server from a slow-server form a legitimate long-polling server. There is no _real_ way to catch this. You may manually cancel the call using `Fuel`, as per the articles you've linked.

Note that this is the case for _any_ library on top of `URLConnection`.
