### ISSUE TITLE
[fuel-jackson] Add Request.body(any: Any) extension method

### ISSUE THREAD

**Issue by david-wg2** [kittinunf/fuel#662]
I'd like to be able to make requests like this: 

```kotlin
 val (request, response, result) = Fuel.post(url)
            .body(MyCustomRequestBodyObject(...)) // here
            .responseObject<MyCustomResponseBodyObject>()
```

Currently I have an extension method in my project which allows this: 

```kotlin
fun Request.body(any: Any) = body(mapper...)
```

Would be nice if this was a part of the `fuel-jackson` module.

**Comment by SleeplessByte** [comment]
I don't think I quite understand what you're asking for 😅. I personally think it's great to add project-based extension methods in your project!

**Comment by tipsy** [comment]
> I don't think I quite understand what you're asking for 😅. I personally think it's great to add project-based extension methods in your project!

The `kotlin-jackson` module adds `responseObject()` as an extension-function, so you can easily convert a HTTP response body to a Kotlin object.

I'm proposing adding another extension-function, `body()`, so you can easily convert a Kotlin object to a request body.

**Comment by SleeplessByte** [comment]
Got it. Can you post the extension method _in full_ that you currently use? I think we can add this to all the libraries, if applicable!

**Comment by tipsy** [comment]
I can do that tomorrow. It's just the standard serialization call though, nothing out of the ordinary.

It will work fine with all libraries.

**Comment by tipsy** [comment]
```kotlin
fun Request.body(any: Any) = body(defaultMapper.writeValueAsString(any)) 
```

**Comment by tipsy** [comment]
That'd be great.

**Comment by benjefferies** [comment]
I'm switching from fuel-gson to fuel-jackson and this is a missing feature where gson has a `jsonBody` extension

**Comment by SleeplessByte** [comment]
@benjefferies yes, I feel like adding `jsonBody` or `body` everywhere is cewl :)

**Comment by kittinunf** [comment]
@tipsy are you happy to throw a quick PR? I would love to see it added ❤️

**Comment by tipsy** [comment]
I tried to clone the project and run it locally, but got an `SDK location not found.` error. I have some other stuff I have to deal with today, so I can't really spend too much on this.

**Comment by iNoles** [comment]
> I tried to clone the project and run it locally, but got an `SDK location not found.` error. I have some other stuff I have to deal with today, so I can't really spend too much on this.

Ah it is looking to Android SDK path.

**Comment by tipsy** [comment]
> Ah it is looking to Android SDK path.

Why? How is this project related to Android?

**Comment by SleeplessByte** [comment]
> > Ah it is looking to Android SDK path.
> 
> Why? How is this project related to Android?

`fuel-android` is

**Comment by tipsy** [comment]
> fuel-android is

I see. Is Android Studio required to run the project?

**Comment by SleeplessByte** [comment]
No, @kittinunf and I both run IntelliJ (NO Android Studio).

**Comment by panpanini** [comment]
I can take a look at this if people are busy 🙋

**Comment by lucasqueiroz** [comment]
Is there any updates on this issue?
Thanks
