### ISSUE TITLE
Can't post parameters correctly

### ISSUE THREAD

**Issue by JoseMCO** [kittinunf/Fuel#67]
When using the following java implementation

        String body = "\"email\": \"some@mail.com\", \"password\": \"somepass\"";

        Fuel.post(login_url).body(body, Charset.forName("UTF-8")).responseString(new Handler<String>() {
            @Override
            public void failure(Request request, Response response, FuelError error) {
                //do something when it is failure
            }

            @Override
            public void success(Request request, Response response, String data) {
                //do something when it is successful
            }
        });

the params get posted as one whole string, as registered on my rails server
    
        {"\"email\": \"some@mail.com\", \"password\": \"somepass\"" => nil }

What is the correct way to post them?

**Comment by yoavst** [comment]
As you can see [here](https://github.com/kittinunf/Fuel/blob/master/fuel%2Fsrc%2Fmain%2Fkotlin%2Fcom%2Fgithub%2Fkittinunf%2Ffuel%2FFuel.kt#L42), `post` can receive a list of `kotlin.pair` as parameters.

**Comment by JoseMCO** [comment]
Yeah, I was reading there just now, tested and it works! Thanks for the fast response (:
