### ISSUE TITLE
ResponseHandler

### ISSUE THREAD

**Issue by marcspraragen** [kittinunf/fuel#674]
Hi--

I'm using android studio 3.4.1 / gradle 3.4.2 / fuel-2.2.0.jar

In files FuelJson.kt and FuelSerialization.kts, the statement

import com.github.kittinunf.fuel.core.ResponseHandler   //("Unresolved reference")

... not finding the file / class ResponseHandler in any package. ResponseHandler doesn't seem to exist in the repository here either.  How to resolve these references?

Thanks,
--Marc
--------------------------

The following lines are in my app module level build.gradle

dependencies{
implementation 'com.github.kittinunf.fuel:fuel-android:1.13.0'
    implementation 'com.github.kittinunf.fuel:fuel:1.13.0'
    implementation 'com.github.kittinunf.fuel:fuel-gson:1.13.0'
    implementation 'org.json:json:20180813'
}

and these are in top level build.gradle:

buildscript {
    ext.kotlin_version = '1.3.41'
    ext.kotlinx_io_version = '0.1.13'
    ext.serialization_version = '0.11.1'
    ext.coroutines_version = '1.3.0-RC2'

    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.ar.sceneform:plugin:1.11.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
    }
}

**Comment by SleeplessByte** [comment]
It's [here](https://github.com/kittinunf/fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Handlers.kt): https://github.com/kittinunf/fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Handlers.kt

**Comment by kittinunf** [comment]
It looks like @marcspraragen using version `1.13.0` ? Maybe, you should upgrade to version 2?

**Comment by kittinunf** [comment]
I guess that should answer your question, I will close this issue for now. But feel free to create new one if you have other issues. Thanks!
