### ISSUE TITLE
Get request instance from FuelError

### ISSUE THREAD

**Issue by GitAntoinee** [kittinunf/fuel#679]
# Feature Request

## Description
Hello, I work with the `responseString` method, and it throw a `FuelError` exception. Then, when I catch this exception I'd like to be able to get the Request instance used. It is returned from the `responseString` but not from the exception.

## Proposed Solution
Add in the FuelError constructor the Request instance used

## Alternatives I've considered
We can add to the Response a field who contains the Request

## Additional context
There is no additional context

**Comment by kittinunf** [comment]
You can get the request object from your first parameter right?

```kotlin
request.responseString { request, response, result ->

}
```

**Comment by GitAntoinee** [comment]
Hello, no this is not possible because I can't get the request variable from the catch block:
```kotlin
// ... request
try {
    val (request, response, result) = request.responseString()
    response = result.get()
    println(response)
} catch(e: FuelError) {
    // I do not have access to request
    TODO("not implemented")
}
```

**Comment by kittinunf** [comment]
Sadly no, you have to save the Request yourself. What do you actually want to have from `Request` object though? If you want just an `URL`, `Response` has it.

**Comment by GitAntoinee** [comment]
Hello, do not worry, I forked fuel and added this feature myself.
I needed the request instance to get the request body
