### ISSUE TITLE
fuel-stetho README doesn't exist

### ISSUE THREAD

**Issue by christophehenry** [kittinunf/fuel#680]
`fuel-stetho`'s README is linked in [Utility section](https://github.com/kittinunf/Fuel#utility) but doesn't exist.

**Comment by kittinunf** [comment]
Opps! I will work on this then.

**Comment by christophehenry** [comment]
(Thank you for your awesome work, BTW. I'm using Fuel for [FreshRSS](https://git.feneas.org/christophehenry/freshrss-android). Awesome to work with :+1:)
