### ISSUE TITLE
How can I send GET request with body?

### ISSUE THREAD

**Issue by dawsonlee1790** [kittinunf/fuel#682]
I have read the Fuel Documentation and learn that: 

### 1. The default client is HttpClient

The default client is HttpClient which is a thin wrapper over java.net.HttpUrlConnection. java.net.HttpUrlConnection does not support a [PATCH](https://download.java.net/jdk7/archive/b123/docs/api/java/net/HttpURLConnection.html#setRequestMethod(java.lang.String)) method. HttpClient converts PATCH requests to a POST request and adds a X-HTTP-Method-Override: PATCH header. While this is a semi-standard industry practice not all APIs are configured to accept this header by default. 

### 2. Request Body Not Support Get

When you're using the default Client, bodies are supported for:
- POST
- PUT
- PATCH (actually a POST, as noted above)
- DELETE

My Question Is: 
Is there any way I can send GET request with body?

Can someone help me? Thank you very much.

**Comment by iNoles** [comment]
Android’s HttpurlConnection doesn’t support it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dawsonlee1790** [comment]
Thank you for your answer.
