### ISSUE TITLE
Can not deserialize in RxJava when i use T for request Object in base Response

### ISSUE THREAD

**Issue by blank15** [kittinunf/fuel#683]
# Bug Report

## Description
Can not deserialize in RxJava when i use T for request Object in base Response 
how i can fix it?
## Screenshoot
![image](https://user-images.githubusercontent.com/17905489/64000550-359f1e80-cb30-11e9-8b63-512afbae4f5c.png)

**Comment by kittinunf** [comment]
Could you please tell me what the error says?

**Comment by kittinunf** [comment]
I think I will close this. But feel free to reopen to discuss/add more information.
