### ISSUE TITLE
Please release a 2.2.1

### ISSUE THREAD

**Issue by bagage** [kittinunf/fuel#686]
I didn't find any chat/IRC room or equivalent to contact you by another mean, but could you release a 2.2.1 release to fix the current latest broken version please?

The 2.2.0 breaks localhost tests (#669). We downgraded to 2.1.0, but there are other bugs fix we'd love to have (#671)…

Thanks!

**Comment by SleeplessByte** [comment]
https://github.com/kittinunf/fuel/pull/684

**Comment by bagage** [comment]
:man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: my bad, I checked all opened/closed issues and merged PRs but didn't think to look at actually opened PRs :laughing:. Thanks @SleeplessByte!
