### ISSUE TITLE
Getting raw response

### ISSUE THREAD

**Issue by Nohus** [kittinunf/fuel#687]
I am connecting to a server using `gzip` Content-Encoding. I want to verify responses to my Fuel requests are using gzip, but it seems there is no way? When I check the response length, it seems it's always the length after it's ungzipped, and I cannot access the original gzipped response, only the plain text. How do I access the original response, or it's length, or verify in another way the response was in fact gzipped?

**Comment by Nohus** [comment]
Solved by adding a breakpoint in `GZIPInputStream.java` and verifying it's hit when the response comes back (and does not when not adding the `Accept-Encoding: gzip` header).

Issue still stands that the original server response seems inaccessible in Fuel.

**Comment by SleeplessByte** [comment]
This is implemented per the HTTP spec. Content-Encoding is handled as follows:

https://github.com/kittinunf/fuel/blob/37867031dc7f50722d83f2d703b9567c16579291/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L103-L115

https://github.com/kittinunf/fuel/blob/37867031dc7f50722d83f2d703b9567c16579291/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L147-L161

We take care of deserialization of Transfer-Encoding like so:
https://github.com/kittinunf/fuel/blob/37867031dc7f50722d83f2d703b9567c16579291/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L103-L115

https://github.com/kittinunf/fuel/blob/37867031dc7f50722d83f2d703b9567c16579291/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L163-L186

From these contents you can _see_ that there is no REAL way to turn off gzip decoding, if the `Content-Encoding` field is used, thanks JVM! Their implementation is non-spec compliant. There is nothing fuel can do about that.

**Comment by Nohus** [comment]
I understand, thank you for the response. :)
