### ISSUE TITLE
Handle empty body for Delete method and have a valid Result object

### ISSUE THREAD

**Issue by baillyjamy** [kittinunf/fuel#689]
# Feature Request

## Description
I try to do a request delete HTTP method in a coroutine. My api return an empty body for a delete but I would like to receive a `com.github.kittinunf.result.Result` after a call of `Request.awaitObjectResult()`.
I know I shouldn't use this class request method because my body is empty so I can't deserialize nothing but I use your `Result` class to check if my request is a success or not. I can work around the problem by returning a `Result<ByteArray, FuelError>` but for me it doesn't make sense when you read it.

## Proposed Solution
Maybe a new `awaitResult` extension method for `Request` that return a `Result` and doesn't take any serializer as a parameter.

## Alternatives I've considered
Do nothing and use `Result<ByteArray, FuelError>`

## Additional context
I may make a mistake or have missed something

**Comment by kittinunf** [comment]
@baillyjamy Do you think we can just use `Result<Unit, FuelError>` to represent the data that you want?

**Comment by baillyjamy** [comment]
Yes, I think it's more convenient. But I don't think that's possible at the moment.

**Comment by kittinunf** [comment]
🤔 Just to make sure I understand you correctly. If the backend returns you with an empty JSON like `{}`, you can map that into a `Unit`, right?

You said that it is not possible, it means that your backend returns you nothing?!?!

**Comment by baillyjamy** [comment]
The backend return a empty body for a delete http call. Not a empty JSON. But I have the rest of my response (size, status code, etc..). 
I said that it is not possible because i can't deserialize a empty body. I would like to return a `Result<Unit, FuelError>` but at the moment `Request.awaitObjectResult()` need a `ResponseDeserializable` object. I can't create a `ResponseDeserializable<Unit>`
Or I don't know how to do it and I apologize for it

**Comment by kittinunf** [comment]
🤔 Can you provide a some sort of "dummy" Deserializable? Like

```kotlin
object UnitDeserializable : Deserializable<Unit> {
    fun deserialize(response: Response) = Unit
}
```

Then, pass it into your `awaitObjectResult`?

**Comment by baillyjamy** [comment]
Oh :open_mouth:. It was so simple. Sorry about that. Thank you very much !
Yes, I also think it's too specific. Besides, you just showed me that there's no need to do too much.
