### ISSUE TITLE
App:dexDebug?

### ISSUE THREAD

**Issue by cferreira-growit** [kittinunf/Fuel#69]
Hello,
First of all, thanks for this awesome lib, it's really hard to find something clean and flexible.

I create a whole web service api using this lib but, when I try to run the app, this happens:

**Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2**

I'm using Gradle to import the lib and, if I remove the dependency, the app works.
Do you have any idea?

Thank you!
Best wishes;

**Comment by kittinunf** [comment]
I have no issue with the latest version `1.1.3` on my android project. Can you try to clean and rebuild project and see whether it solves problem?

**Comment by cferreira-growit** [comment]
For some reason an unused library was causing a conflict. I just removed and it worked!

Thank you.

**Comment by kittinunf** [comment]
Alright! Thanks so much to using `Fuel`. I will close this as it is solved somehow.
