### ISSUE TITLE
Query parameters doesn't work with POST request

### ISSUE THREAD

**Issue by C06A** [kittinunf/fuel#695]
# Bug Report

## Description
I try to login into Artsy API. For that they require POST request with query parameters.
My code looks like:

```Kotlin
fun main() {
    val tmp = "https://api.artsy.net/api/tokens/xapp_token?client_id=XXXX&client_secret=XXXX"
            .httpPost()
            .responseString()
    println(tmp.first.cUrlString())
    println(tmp.second.statusCode)
}
```

(with appropriate values)
The Fuel reports code 403, but when I run its curi from the shell prompt (with quoting the URL according https://github.com/kittinunf/fuel/issues/690) I got 201 with expected body.

## To Reproduce

1. register at https://developers.artsy.net/v2/start to get `client_id` and `client_secret`
2. try the code above. Observe failure status code
3. copy curi command to *NIX shell and add quotes around the URL. Observe working fine

## Expected behavior
Should return status 201 and session token in JSON body

### Development Machine
_Complete the following information if applicable_

 - OS: Mac OSX 10.14.6
 - IDE: IntelliJ IDEA 2019.2.3
 - Fuel version: 2.2.1
 - Kotlin version: 1.3.40

### Smartphone or Emulator
N/A

**Comment by kittinunf** [comment]
I tried with this snippet

``` kotlin
Fuel.post("https://api.artsy.net/api/tokens/xapp_token", listOf("client_id" to "xxx", "client_secret" to "770904531ab257d5b022eb197217ea7d")).responseString { req, resp, res ->
        println(res.component1())
      }
```

I got the result as expected;

```
10-26 16:16:42.776 3564-3564/com.example.fuel I/System.out: {"type":"xapp_token","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IiIsInN1YmplY3RfYXBwbGljYXRpb24iOiI1ZGIzZjBlNWU0ZWZhYzAwMTM0YTQwYmQiLCJleHAiOjE1NzI2Nzg1MDIsImlhdCI6MTU3MjA3MzcwMiwiYXVkIjoiNWRiM2YwZTVlNGVmYWMwMDEzNGE0MGJkIiwiaXNzIjoiR3Jhdml0eSIsImp0aSI6IjVkYjNmMGU2NGEyYzVhMDAwZWU0OTQyMSJ9.0wg7hQR-WC7Bl8SYdOdE_h9Jaw3mLR-417ivtpFPSEw","expires_at":"2019-11-02T07:08:22+00:00","_links":{}}
```

I did it on Android emulator, but I don't think that difference is significant 🤔 Did you do something different that this?

**Comment by C06A** [comment]
I guess Android makes the difference. I tried your code from my Mac and still got 403.

Also your code generate a different request: putting parameters into body of the POST request while mine -- to the query. It seems in this case the problem is not in the location of parameters, but in the platform.

Could you try this on Mac or other *NIX systems? I can try on Linux next week.

**Comment by kittinunf** [comment]
It is a problem for the `artsy` website that they require you to send something more? e.g. 🤔 Could you try to make sure that the header you send have a correct `user-agent` or accept `application/json`?

```kotlin
Fuel.post("https://api.artsy.net/api/tokens/xapp_token", listOf("client_id" to "xxx", "client_secret" to "yyy"))
          .header(Headers.USER_AGENT to "AWESOME APP", Headers.ACCEPT to "application/json")
          .responseString()
```

**Comment by kittinunf** [comment]
Any development on this? :)

**Comment by C06A** [comment]
Sorry, I was out-of-state.

It is not Antsy problem as the curl command generated by Fuel works fine from shell (see original post). No headers, no user-agent needed.

**Comment by kittinunf** [comment]
I have created a sample and try above code and it works. Can you do the same and report back?

**Comment by C06A** [comment]
I got this. I also created my sample and ran it. My code results in 403 when I am running on my Mac. Your code (after I added call to `join()`) also returns 403.
Also the curl command generated by my code works as expected from the Terminal. This means that all elements are correct and it seems the problem somewhere in the way Fuel submitting it.

```
fun main() {
    val url = "https://api.artsy.net/api/tokens/xapp_token"

    val tmp2 = Fuel.post(url, listOf("client_id" to clientID, "client_secret" to clientSecret)).responseString { req, resp, res ->
        println(req.cUrlString())
        println(resp.statusCode)
        println(res.component1())
    }
    val tmp3 = tmp2.join()

    println(tmp3)

    val tmp = "$url?client_id=$clientID&client_secret=$clientSecret"
            .httpPost()
            .responseString()
    println(tmp.first.cUrlString())
    println(tmp.second.statusCode)
}

```

Once I printed the response from your code I see the message in the returned error HTML page:

```
    <div class="error-message">
      <h1>Internal Error</h1>

      <div class="error-trace">
        <div class="cf-error-details cf-error-1010">
  <h1>Access denied</h1>
  <p>The owner of this website (api.artsy.net) has banned your access based on your browser's signature (530c003cdaa4ebec-ua21).</p>
  <ul class="cferror_details">
    <li>Ray ID: 530c003cdaa4ebec</li>
    <li>Timestamp: 2019-11-05 04:14:27 UTC</li>
    <li>Your IP address: 24.91.140.192</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: api.artsy.net/api/tokens/xapp_token </li>
    <li>Error reference number: 1010</li>
    <li>Server ID: FL_106F34</li>
    <li>User-Agent: Java/1.8.0_112</li>
  </ul>
</div>
```

What's wrong with `browser's signature`? Is it a way to change it? As I mentioned the curl command from Terminal works just fine...

**Comment by kittinunf** [comment]
🤔 Oh sorry for not being clear, can you add this line into your `main()` function too? `.header(Headers.USER_AGENT to "AWESOME APP", Headers.ACCEPT to "application/json")` ?

**Comment by C06A** [comment]
OK, this works.
Thanks for the link to StackOverflow for explanation.
