### ISSUE TITLE
responseJson() can not be used in block mode

### ISSUE THREAD

**Issue by denghongcai** [kittinunf/Fuel#71]
```
val(request, response, reulst) = "http://test.com".httpGet().responseJson()
```

**Comment by yoavst** [comment]
You are right. the function `responseJson()` is missing from [Requests.kt](https://github.com/kittinunf/Fuel/blob/master/fuel-android%2Fsrc%2Fmain%2Fkotlin%2Fcom%2Fgithub%2Fkittinunf%2Ffuel%2Fandroid%2Fextension%2FRequests.kt)

 Would you mind open to PR to fix this?
