### ISSUE TITLE
could not import

### ISSUE THREAD

**Issue by gvincenta** [kittinunf/fuel#715]
# Bug Report

## Description
Could not import. when my android project's sync-ing,  it said : 
`ERROR: Failed to resolve: com.github.kittinunf.fuel:fuel-gson:2.8.5
Show in Project Structure dialog
Affected Modules: app`

## To Reproduce
i was using gradle  to import : "implementation 'com.github.kittinunf.fuel:fuel-gson:2.8.5' "

 

```Kotlin
 ```

## Expected behavior
Sync should be successful, but it wasn't 

 - OS: Windows 10
 - IDE:  Android Studio
 - Fuel GSON version: 2.8.5
 - Kotlin version:  i dont know

**Comment by SleeplessByte** [comment]
Make sure you follow all the instructions.

Is `jcenter` present in your gradle sourced?

**Comment by kittinunf** [comment]
@gvincenter have you resolved the problem?

**Comment by lyckligtax** [comment]
I do have the same Problem:

> Could not find com.github.kittinunf.fuel:fuel-jackson:2.9.8.

after reading @SleeplessByte comment I looked for a way to include `jcenter` and found it within the pull requests.

Unfortunately still not able to find the package :-/

`
repositories {   
  jcenter()   
  mavenLocal()   
}
`

On the other hand `fuel` alone is found without any problems

**Comment by kittinunf** [comment]
I guess the issue get staled. I will close the issue for now. Feel free to reopen this if you want to.
