### ISSUE TITLE
.progress exceeding rate limiting of notification updates 

### ISSUE THREAD

**Issue by sal0max** [kittinunf/fuel#717]
I'm downloading a file to an OutputStream with Fuel. While doing this, my app shows a [notification](https://developer.android.com/guide/topics/ui/notifiers/notifications), informing about the download progress.

I'm using `.progress` for this:
```kotlin
Fuel
   .download(downloadUrl)
   .streamDestination { response, _ ->
      Pair(outputStream, { response.body().toStream() })
   }
   .progress { readBytes, totalBytes ->
      Log.d("progress", "$readBytes/$totalBytes")
      notificationHelper.notifyDownloadProgress(notificationId, readBytes.toInt(), totalBytes.toInt())
   }
   .response()
```

The buffer size seems to be 4096, which results in case of a 203kB file in 51 updates in a very short period of time:
```
2020-02-19 03:32:12.546  D/progress: 4096/203746
2020-02-19 03:32:12.570  D/progress: 8192/203746
... 47 more ...
2020-02-19 03:32:14.570  D/progress: 203746/203746
2020-02-19 03:32:14.574  D/progress: 203746/203746
```

From Nougat on, only 10 updates per second are allowed for notifications. Anything greater will result in `E/NotificationService: Package enqueue rate is 10.062265. Shedding events. package=...`

I guess I'm probably not the only one, using `.progress` in combination with the `NotificationManager`. So what I'm putting to discussion: **What's probably the best practice to do here?**

**Comment by sal0max** [comment]
Alright, here my solution for now:

```kotlin
var lastUpdate = 0L
Fuel
   .download(downloadUrl)
   .streamDestination { response, _ ->
      Pair(outputStream, { response.body().toStream() })
   }
   .progress { readBytes, totalBytes ->
      // max 2 updates/second - more than 10/second will be blocked
      if (System.currentTimeMillis() - lastUpdate > 500) {
         lastUpdate = System.currentTimeMillis()
         Log.d("progress", "$readBytes/$totalBytes")
         notificationHelper.notifyDownloadProgress(notificationId, readBytes.toInt(), totalBytes.toInt())
      }
   }
   .response()

```

**Comment by kittinunf** [comment]
Ah, i didn't know the "only 10 updates per second are allowed for notifications" part 🧐


Do you think there is anything from library side to help you with this?

**Comment by sal0max** [comment]
I think my current sollution is feasible.
Maybe something like [RX's sample](http://reactivex.io/documentation/operators/sample.html) could be helpful, if integrated in your library. Like maybe a third parameter `refreshRate` in ms for `progress`.
But probably not worth the effort.

The more important thing is, that this behavior is documented here, as it took me a while to find the problem.

Another not-so-good solution I thought about: Increasing the buffer size. Not needed any more, but would this be possible?

**Comment by kittinunf** [comment]
@sal0max yeah agree with you. I don't think it might be a bit too much for the effort. 

I am thinking about document your findings into the Readme.md that we have. Do you think it is good to add?
If you don't mind, you could add the snippet of code into the Readme doc though

**Comment by SleeplessByte** [comment]
Personally this doesn't belong in Fuel. I do like adding an example to our docs :) 

throttling output is a common thing implementors of a library need to do 🗡
