### ISSUE TITLE
How to use with Gson SerializedName annotation?

### ISSUE THREAD

**Issue by tagy** [kittinunf/fuel#719]
I have been using Fuel for a while, and separately adding Gson dependency and using it to parse json fetched by Fuel.

I figured I may as well use the extension package `com.github.kittinunf.fuel:fuel-gson` instead and use `responseObject` instead of `responseString` and then parse it.

This works fine but some data classes use the annotation like:

`@field:SerializedName("Name") val name: String`

But can I use this annotation using the extension package? I can't seem to access it. It doesn't seem correct to use the extension package and then separately add another Gson dependency just to access the annotations? Should I just not use the extension package?

Appreciate this is a question but if any could point me in the right direction that would be great thanks.

**Comment by kittinunf** [comment]
Yeah, I think because we use `implementation` for Gson dependency. So, the API of Gson is not leaking out to the consumer. 
 
You have to include/add the dependency for Gson manually yourself. 

Could you try that and see whether it works?

**Comment by tagy** [comment]
Yes also adding the Gson dependency manually works and I can use `responseObject` etc.

I think doing that, ideally I would want to make sure I am always using the same version of Gson as your extension, so I would need to remember to update them together as needed.

But this isn't a big deal for me, I just wasn't sure if I was missing something. Thanks for you help.

**Comment by kittinunf** [comment]
I think it is okay to add things manually.  It is your project so it is better for you and you should be the one in charge of the dependency version not us. 

Thank you for using Fuel, also thanks for creating this issue though. If you don't mind, I will close this.
