### ISSUE TITLE
    Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 404 Not Found

### ISSUE THREAD

**Issue by IndraRukmana** [kittinunf/fuel#727]
i got error when i try incorrect username or password

```
   private fun onTaskCompleted(response: String, task: Int) {
        Log.d("responsejson", response)
        removeSimpleProgressDialog()  //will remove progress dialog
        when (task) {
            LoginTask -> if (isSuccess(response)) {
                saveInfo(response)
                Toast.makeText(this@LoginActivity, "Login Successfully!", Toast.LENGTH_SHORT).show()
                val intent = Intent(this@LoginActivity, HomeActivity::class.java)
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
                startActivity(intent)
                this.finish()
            } else {
                Toast.makeText(this@LoginActivity, getErrorMessage(response), Toast.LENGTH_SHORT).show()
            }
        }
    }

    fun isSuccess(response: String): Boolean {
        try {
            val jsonObject = JSONObject(response)
            return if (jsonObject.optString("status") == "success") {
                true
            } else {
                false
            }

        } catch (e: JSONException) {
            e.printStackTrace()
        }

        return false
    }

    fun getErrorMessage(response: String): String {
        try {
            val jsonObject = JSONObject(response)
            return jsonObject.getString("message")

        } catch (e: JSONException) {
            e.printStackTrace()
        }
        return "No data"
    }
```
result

>      Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 404 Not Found
>         at com.github.kittinunf.fuel.core.interceptors.ValidatorInterceptorKt$validatorResponseInterceptor$1$1.invoke(ValidatorInterceptor.kt:12) 
>         at com.github.kittinunf.fuel.core.interceptors.ValidatorInterceptorKt$validatorResponseInterceptor$1$1.invoke(Unknown Source:4) 
>         at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:51) 
>         at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(Unknown Source:4) 
>         at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:16) 
>         at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11) 
>         at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6) 
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
> 2020-03-28 18:39:08.923 18170-18170/com.example.quickinvites I/Process: Sending signal. PID: 18170 SIG: 9

**Comment by SleeplessByte** [comment]
By default 404's will throw an HTTP Exception in the old version you're using. I suggest upgrading Fuel, or catching the error. You can then use `response.data` as normally.
