### ISSUE TITLE
Force Fuel to encode space as %20 instead of + in url parameters

### ISSUE THREAD

**Issue by T1ASH** [kittinunf/fuel#735]
I have a vendor built API that I am accessing that has spaces in some of the url parameters. For some reason on a few of the parameters, if it returns "+" it breaks the  call. Is there anyway that I can change the encoding on Fuel to return %20 in the url parameter instead of "+" for a space? Thank you.

Example:
- Fuel.get("<URL>", listOf("keywords" to "John Smith", "service) 
- request.url shows "John+Smith". I need it to show "John%20Smith"

**Comment by SleeplessByte** [comment]
You can use an _interceptor_ (Request variant) as shown [here](https://github.com/kittinunf/fuel/tree/master/fuel#detail-configuration). Here you would explicitly transform `+` to `%20`, if it's a `GET` request.

**Comment by T1ASH** [comment]
that worked perfectly, thank you! 

For anyone stumbling on this with the same issue, here is the Interceptor that I used successfully. 

````kotlin
object GetRequestSpaceInterceptor : FoldableRequestInterceptor {
    override fun invoke(next: RequestTransformer): RequestTransformer {
        return { request ->
            request.url = URL(request.url.toString().replace("+", "%20"))
            next(request)
        }
    }
}
````
