### ISSUE TITLE
Publish the library on Maven Central

### ISSUE THREAD

**Issue by DanySK** [kittinunf/fuel#747]
# Feature Request

Just publishing the library on the Maven Central repository

## Description
I'm about to use this library on a software that is published on Maven Central, and the policy of the repository is to depend only on software hosted (also) there.

## Proposed Solution
I wrote [a plugin for quickly setting up a gradle publication targeting Maven Central](https://github.com/DanySK/maven-central-gradle-plugin). That could be used, or we could resort to manual configuration

## Alternatives I've considered
Alternatively, since the license allows it, I could fork and publish the artifacts under `org.danilopianini:fuel`

## Additional context
n/a

**Comment by kittinunf** [comment]
Thanks! I will set it up the account tonight 🙇 🙏

**Comment by DanySK** [comment]
@jckoenen looks like we are going to be able to use fuel in upgradle!

**Comment by kittinunf** [comment]
Ah, it looks like POM file is invalid maybe

```
Project name missing, Project description missing, Project URL missing, SCM URL missing, Developer information missing
```

**Comment by DanySK** [comment]
I'm preparing a proposal for change

**Comment by DanySK** [comment]
@kittinunf please check #750. I was a bit in a rush, so it may need to get polished. Let me know.

**Comment by kittinunf** [comment]
Please allo me to fix this fully with new version #753

**Comment by DanySK** [comment]
@kittinunf I'm a bit lost with the status of this issue: can you shortly get me up to date with what's going on and (if any ETA is available) when the library will be available on Central?

Thanks

**Comment by kittinunf** [comment]
@DanySK I am pressing sync to MavenCentral and the loading has been spinning for 15 mins or so ... I am not sure whether this is normal or not, 😢. Please wait a bit 🙏, appreciated and sorry for inconveniences!!

**Comment by kittinunf** [comment]
I think it should be ready! ❤️ Thank you so much for pushing for this

**Comment by kittinunf** [comment]
https://search.maven.org/search?q=g:com.github.kittinunf.fuel

Hopefully you can definitely use in your project this time :). Feel free to reopen if you have anything.

**Comment by DanySK** [comment]
This is **fantastic**. Thank you.
