### ISSUE TITLE
The Content-Length header is not included in requests

### ISSUE THREAD

**Issue by felixdivo** [kittinunf/fuel#748]
# Bug Report

## Description
The `Content-Length` header is not included in requests. I did not find out how to prevent this. Is it intentional or actually a bug? I did not find relevant documentation on this behavior of Fuel .

This keeps Fuel ⛽ from being used for APIs that respond with [HTTP 411](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411) is the field is not present. This is the case for example with the [Google Play Developer API](https://developers.google.com/android-publisher/api-ref/).

## To Reproduce
Code to reproduce the behavior:

```Kotlin
import com.github.kittinunf.fuel.Fuel
import com.github.kittinunf.fuel.core.Headers

println(Fuel
        .post("https://httpbin.org/anything")
        .header(Headers.CONTENT_LENGTH, "0")
        .responseString()
        .third
        .component1())
```

Output:
```JSON
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "Java/13.0.1", 
    "X-Amzn-Trace-Id": "Root=1-XXXXXXX-XXXXXXXXXXXXXXXXX"
  }, 
  "json": null, 
  "method": "POST", 
  "origin": "--------", 
  "url": "https://httpbin.org/anything"
}

```

### Development Machine

 - OS: Windows 10
 - Fuel version: 2.2.2
 - Kotlin version: 1.3.72 @ Java/13.0.1

**Comment by SleeplessByte** [comment]
Good question. Places to look at would be HTTPUrlConnection. Might be that you need to add an actual empty body for this to work. Might be that we automatically switch to streaming/chunked (which makes us need to remove content-length per rfc).

**Comment by felixdivo** [comment]
Good idea! I checked it out:
- Adding `.body("")` changes nothing, i.e. `Content-Length` is still missing.
- Adding `.body(" ")` has the desired effect (`"Content-Length": "1"` is added), but is a subtly different request.

**Comment by felixdivo** [comment]
Seems like `com.github.kittinunf.fuel.toolbox.HttpClient::setBodyIfDoOutput` checks for `body.isEmpty()` and immediately returns if that is the case. Could it be that the default is `connection.setChunkedStreamingMode(something)` and that this default is not overridden is the body is empty/has length zero?

**Comment by felixdivo** [comment]
Yes, that actually fixes it:

```diff
     private fun setBodyIfDoOutput(connection: HttpURLConnection, request: Request) {
         val body = request.body
-        if (!connection.doOutput || body.isEmpty()) {
+        if (!connection.doOutput) {
+            return
+        }
+        if (body.isEmpty()) {
+            connection.setFixedLengthStreamingMode(0L)
             return
         }
```

Is that change wanted/should I open a PR?

**Comment by SleeplessByte** [comment]
Yes this is great.
