### ISSUE TITLE
Calling PUT from Android is returning empty Response

### ISSUE THREAD

**Issue by rodrigosalinas** [kittinunf/Fuel#75]
Hi, I'm making a PUT call in this form:
```
val (request, response, result) = Fuel.put("/myApiUrl/$id?access_token=$token", listOf("param1" to value1).header(Pair("Content-Type", "application/x-www-form-urlencoded")).response()
```
Before anyone asks, I'm adding manually the Content-Type in the header because if I don't it is not automatically added despite what the documentation says.

Anyway, the response I debug has a length of 0. The Body is empty. But if I print the cUrlString and I execute it from the command line it works. I get what I'm expecting. Can you help me please? There is some known issue with Android?

Thank you very much.

**Comment by yoavst** [comment]
I can confirm `Content-Type` header is not added, but the request works on [the unit test](https://github.com/kittinunf/Fuel/blob/master/fuel%2Fsrc%2Ftest%2Fkotlin%2Fcom%2Fgithub%2Fkittinunf%2Ffuel%2FBlockingRequestTest.kt#L118).

Did you add the Android dependency? 
`compile 'com.github.kittinunf.fuel:fuel-android:1.1.3' //for Android`

**Comment by rodrigosalinas** [comment]
Yes, that's what I have. Thank you.

**Comment by rodrigosalinas** [comment]
Hi again. I changed the way I'm calling my API with the async mode and now it's working superb. I don't know what the problem was with the sync mode. Anyway, we always should call APIs in async mode. ;-)

Besides, I had to know Kovenant and Result. Very nice projects along with Fuel. Now I feel I'm doing it the right way. Congrats.

**Comment by yoavst** [comment]
#77 will fix the headers bugs.
