### ISSUE TITLE
Async request blocks the app if the device connected to wi-fi without internet connection

### ISSUE THREAD

**Issue by mezhevikin** [kittinunf/fuel#758]
# Bug Report

## Description

I make an asynchronous request at the application startup. If the device is connected to Wi-Fi with no Internet connection, then the request blocks the application.

## To Reproduce

1. Connect Android to wi-fi without an internet connection
2. Open app.
3. Make HTTP request in onCreate method.
4. Application freezes for 30 seconds

```Kotlin
dependencies {
    implementation 'com.github.kittinunf.fuel:fuel:2.2.3'
    implementation 'com.github.kittinunf.fuel:fuel-android:2.2.3'
    implementation 'com.github.kittinunf.fuel:fuel-gson:2.2.3'
}
```

```Kotlin
"https://google.com".httpGet().responseObject<Map<String, Any>> { _, _, result ->

}.join()
```

## Expected behavior

I would like the request to not block the application

### Development Machine
_Complete the following information if applicable_

 - OS: Mac os 10.15
 - IDE: Android Studio
 - Fuel version: 2.2.3
 - Kotlin version: 1.3.61

### Smartphone or Emulator
_Complete the following information if applicable_

 - Device: Any device
 - OS: Android 5.0

**Comment by kittinunf** [comment]
🤔 I think because you use `join()` it is obviously gonna block the thread. 

By default, `fuel-android` performs networks on the bg thread then calling the block on the mainthread. 

Do you think you can try to perform the work in the block instead?

**Comment by mezhevikin** [comment]
@kittinunf I removed `join()` method from the code. 
Now, it works like a charm.
Thk.
