### ISSUE TITLE
jsonBody takes object, not string?

### ISSUE THREAD

**Issue by danpozmanter** [kittinunf/fuel#761]
# Bug Report

## Description
`Fuel.post("https://httpbin.org/post")
    .jsonBody("{ \"foo\" : \"bar\" }")
    .also { println(it) }
    .response { result -> println(result.get()) }`

Doesn't seem to work, but if I change the argument to jsonBody to a map

`
val data = mapOf("foo" to "bar")
Fuel.post("https://httpbin.org/post")
    .jsonBody(data)
    .also { println(it) }
    .response { result -> println(result.get()) }`

It works just dandy (running locally against my own server).

## To Reproduce

Test the above code, you'll see the body is a string in the first instance, json in the second.

```Kotlin
// Test case or sample that shows broken behaviour and expected behaviour
```

## Expected behavior
The string is automatically converted to json, or the documentation is updated to reflect what needs to be passed.

### Development Machine
_Complete the following information if applicable_

 - OS: Linux Mint
 - IDE: IntelliJ
 - Fuel version: 2.2.3
 - Kotlin version: 1.3.72

### Smartphone or Emulator
_Complete the following information if applicable_

**Comment by SleeplessByte** [comment]
Correct. It will serialize it for you.
