### ISSUE TITLE
How can I use the response variable outside of the Fuel.post method?

### ISSUE THREAD

**Issue by jso8910** [kittinunf/fuel#763]
I have a post method like this
```
        Fuel.post("$urlBase/login")
            .jsonBody("{\"username\":\"$username\",\"password\":\"$password\"}")
            .response { request, response, result ->
                val (bytes, error) = result

                if (bytes != null) {
                    val jsonResult = JSONObject(String(bytes))
                    val token = jsonResult["token"].toString()
                }
            }
```
I want to be able to use the result variable or the token variable outside of the method, and inside the function that this is enclosed in. I have tried defining a variable before and changing it, and that hasn't worked. Any way I can do this?

**Comment by C06A** [comment]
So nobody replying for 11 days, so let me give my 2¢

Keep in mind I didn't use this asynchronous call. My understanding is that your statement will return **before** the POST request returns. So the execution reaching your next statement before the closure is executed. You have to wait somehow for the request to come back before your closure is called and your external for it variable is set.

Also alternative, which I also didn't use, is to use coroutines.

**Comment by kittinunf** [comment]
@C06A is right! 
By default, the callback is called asynchronously. You either have to embrace the asynchronicity or you have to block the call. 

@jso8910 For synchronous call, You can also use the `response()` counterpart instead.

Feel free to let me know if you need more information.
