### ISSUE TITLE
Response interceptors not called when request fails

### ISSUE THREAD

**Issue by jrovira037** [kittinunf/fuel#771]
# Bug Report

## To Reproduce

1. Create an interceptor

```
        FuelManager.instance.addResponseInterceptor { next: (Request, Response) -> Response ->
            { req: Request, res: Response ->
                println("INTERCEPTED")
                next(req, res)
            }
        }
```

2. Make a request:

   ` val (req, resp, result) = Fuel.get("www.google.com").response()`

3. Check the console, when the request is successful, INTERCEPTED is printed, otherwise it is not
     
## Expected behavior
I expect Fuel to call the response interceptor whether the request works or not

## Environment

Developing in Android Kotlin using:

```
    // fuel for http requesrs
    implementation 'com.github.kittinunf.fuel:fuel:2.3.0' // fuel-core
    implementation 'com.github.kittinunf.fuel:fuel-android:2.3.0' // fuel-Android
    implementation 'com.github.kittinunf.fuel:fuel-jackson:2.3.0' // fuel-Jackson
    implementation 'com.github.kittinunf.fuel:fuel-coroutines:2.3.0' // fuel-coroutines
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.11.2' // Jackson
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.11.2" // Jackson kotlin
```

### Development Machine
_Complete the following information if applicable_

 - OS: Ubuntu 20.04
 - IDE: [ Android Studio
 - Fuel version: 2.3.0
 - Kotlin version: 1.4

### Smartphone or Emulator
_Complete the following information if applicable_

 - Device: Pixel 3 XL
 - OS: Android 10

**Comment by SleeplessByte** [comment]
This is not a bug. 

There is also no way to differentiate from failure or success interceptors at the moment. However, the chain is only halted **when an error is raised**, which **does not** happen when the request returns, say, a 404. It's actually an interceptor that turns 4xx and 5xx codes into errors.

**Comment by jrovira037** [comment]
I see. So is there a way to intercept the response before the error is raised?

What I want to do is intercept and Unauthorized code to log out the user (which needs to be done in every request). @SleeplessByte

**Comment by SleeplessByte** [comment]
Certainly!

One example is to remove the status code interceptor from the fuelmanager, and add in your own (and then add it back).

**Comment by jrovira037** [comment]
Where can I find documentation about how to do that? Looked at the documentation and could not find anything.

The closes think I found is: `FuelManager.instance.removeAllResponseInterceptors()`, but it does not seem to change anything. 

Thanks a lot for your help! @SleeplessByte
