### ISSUE TITLE
Jackson extensions: responseObject() should return CancellableRequest object

### ISSUE THREAD

**Issue by detouched** [kittinunf/fuel#775]
Some [`responseObject(...)`](https://github.com/kittinunf/fuel/blob/63c5f4c/fuel-jackson/src/main/kotlin/com/github/kittinunf/fuel/jackson/FuelJackson.kt#L20-L26) extension methods for Jackson don't expose result of `CancellableRequest` type, which makes them inconsistent with other helper methods and limits their use cases for no reason (e.g. no way to `cancel()` or `join()` request when these shorthand methods used).

Specifically, shorthand methods that accept the triple of _request_, _response_ and _result_ have `Unit` return type.

**Comment by SleeplessByte** [comment]
This is my fault for not noticing it in #569. Thank you for bringing this up ánd fixing it. You're great.
