### ISSUE TITLE
Assertions in Jackson extensions tests never fail

### ISSUE THREAD

**Issue by detouched** [kittinunf/fuel#776]
Some tests in `FuelJacksonTest` class have assertions that will never fail the test.

The problem is that assertions are executed in the asynchronous response handler. Since the request result is not awaited, they will error out on a non-main thread, so test engine will not know about the failures.

## To Reproduce
1. Put any obviously false assertion into, for example, [`jacksonTestResponseObject()`](https://github.com/kittinunf/fuel/blob/572d907/fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/FuelJacksonTest.kt#L41-L43)
2. Run the test
3. The test will pass though should've failed

## Potential solution
Probably the easiest would be to append `.get()` for every asynchronous call which is inherited from `Future<Response>`. This will let the error bubble  up. This solution, however, depends on fixing #775 because some asynchronous extension functions don't expose `CancellableRequest` object.

**Comment by detouched** [comment]
In fact, 9 out of 15 tests actually fail now if I just add proper awaiting on the result in them. Hopefully they're just out of date, not catching real bugs :)

**Comment by iNoles** [comment]
Should this be closed?

**Comment by SleeplessByte** [comment]
Yeah. 

The PR had Fixes a and b. 

GitHub only understands 

Fixes a
Fixes b

**Comment by detouched** [comment]
Oops, TIL my bad, sorry.
