### ISSUE TITLE
PATCH request

### ISSUE THREAD

**Issue by kuleshovdv** [kittinunf/fuel#779]
I have some problem with PATCH request from Fuel 2.2.0
Code:
```
"$HOST/status".httpPatch()
            .header("Authorization" to BEARER)
            .response { request, response, result ->
            }
```
The problem is that server at the same time receive **POST** request, but not PATCH.
Apache log:
`- - [13/Oct/2020:14:37:59 +0000] "POST /status HTTP/1.1" 404 3771 "-" "Dalvik/2.1.0 (Linux; U; Android 11; sdk_gphone_x86 Build/RSR1.200819.001.A1)"`

**Comment by hestad** [comment]
This is currently a feature I believe :) We are using `FuelManager.instance.forceMethods = true`. This will enable true PATCH. Btw. you'll end up with a reflective warning, i.e. `WARNING: Illegal reflective access by com.github.kittinunf.fuel.toolbox.extensions.ForceMethodK`, so I guess it will stop working some day!

**Comment by kittinunf** [comment]
Yes, @hestad is correct here! Please try and let us know whether that answers your question?

**Comment by kittinunf** [comment]
I guess this should be closed then. Thanks for asking btw! :)

**Comment by vojkny** [comment]
For anyone who stumbles here – it can be hacked even without modifying current version of Fuel.

Two things need to be done:

1. Enable request.executionOptions.forceMethods = true
2. To allow for reflectively forcing PATCH to the string value on JDK11+, one must add JVM command line arguments: --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED
