### ISSUE TITLE
update kotlinx-serialization

### ISSUE THREAD

**Issue by marcblanchet** [kittinunf/fuel#783]
# Refactoring

## Description
kotlinx-serialization has now been updated to 1.0.1, which is much more feature rich.
## Files to process
- https://github.com/kittinunf/fuel/blob/master/fuel-kotlinx-serialization/src/main/kotlin/com/github/kittinunf/fuel/serialization/FuelSerialization.kt

## Why this is necessary**
creates conflict when having the old kotlinx-serialization dependency of Fuel with the current one who is very useful in any app.

**Comment by kittinunf** [comment]
Ok i will take care of this over the weekend 🙇 🙇 🙇
