### ISSUE TITLE
PATCH on HTTPS endpoint doesn't work

### ISSUE THREAD

**Issue by cpuydebois** [kittinunf/fuel#784]
# Bug Report

## Description
Using PATCH method on a HTTPS endpoint doesn't work even when setting `FuelManager.instance.forceMethods = true`

## To Reproduce
```Kotlin
    FuelManager.instance.forceMethods = true
    val (_, _, result) = Fuel.patch("https://httpbin.org/patch")
            .also { println(it) }
            .response()
    if (result is Failure) {
        println(result.error) // HTTP Exception 405 METHOD NOT ALLOWED
    }
```

## Expected behavior
When setting `FuelManager.instance.forceMethods = true`, the HTTP method should be PATCH and not POST with header `X-HTTP-Method-Override`

**Comment by vojkny** [comment]
For anyone who stumbles here – it can be hacked even without modifying current version of Fuel.

Two things need to be done:

1. Enable request.executionOptions.forceMethods = true
2. To allow for reflectively forcing PATCH to the string value on JDK11+, one must add JVM command line arguments: --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED
