### ISSUE TITLE
Connection TimeOut and Response TimeOut

### ISSUE THREAD

**Issue by carmas123** [kittinunf/Fuel#79]
Please can you explain me (if you can) how can I specify the connection timeout and requast timeout different?

**Comment by yoavst** [comment]
Currently they is only one timeout for both connection and response.

**Comment by carmas123** [comment]
I've created a fork with this options.

**Comment by kittinunf** [comment]
This is supported in 1.2.1

**Comment by JairAviles** [comment]
How do I know that a Timeout exception has occurred while executing the asynchronous task? Does the Fuel error object return any specific code our message about it? I think the documentation is not clear enough for handling that exception type.
