### ISSUE TITLE
MavenCentral cannot resolve dependencies

### ISSUE THREAD

**Issue by backdoor20** [kittinunf/fuel#803]
# Feature Request
Can all the Jars be provided to the MavenCentral As Jfrog is going to discontinues its support for  JCenter and Bintray

## Description
As per the article https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/ Jfrog will discontinue its support. We cannot resolve the required dependencies for Fuel by mavenCentral 
```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.kittinunf.result:result:2.2.0.
     Required by:
         project : > com.github.kittinunf.fuel:fuel:2.2.3
      > Could not resolve com.github.kittinunf.result:result:2.2.0.
```
 

## Proposed Solution
Include the latest Jar in the mavenCentral

## Alternatives I've considered
Currently using Jcenter but what will happen to the project onces jfrog discontinues its support.

## Additional context
We need jcenter to resolve the dependencies
```
    implementation("com.github.kittinunf.fuel:fuel:2.2.3")
    implementation("com.github.kittinunf.fuel:fuel-jackson:2.2.3")
```
it throughs error while building if we not include the jcenter as follow

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.kittinunf.result:result:2.2.0.
     Required by:
         project : > com.github.kittinunf.fuel:fuel:2.2.3
      > Could not resolve com.github.kittinunf.result:result:2.2.0.
```

**Comment by btraas** [comment]
Did you get this resolved?
