### ISSUE TITLE
Provide an idiomatic way to flatten/reduce List<Result>

### ISSUE THREAD

**Issue by asarkar** [kittinunf/fuel#805]
# Feature Request

## Description
We are using Fuel to call [GitLab groups API](https://docs.gitlab.com/ee/api/groups.html) as follows:
1. Call `GET /groups` for get a list of all groups the authentication token has access to.
2. Filter the groups based on some criteria.
3. For each group, call `GET /groups/:id` to get details.
4. Merge the results.

The output of step 3 is a `List<Result<GroupDetail>>`. Since there's no good way to flatten it, we use `Result.fold` to collect the intermediate results, and ignore any exception. Something like:
```
Result<List<Group>>.map { groups ->
    val details = mutableListOf<GroupDetail>()
    groups.forEach {
        Fuel.get("/groups/${it.id}")...fold({ detail ->
                details.add(detail)
            }, { error ->
                // log error
            })
    }
    return details
}
```

This works, but is not idiomatic.

## Proposed Solution
It'd be nice to be able to do the following:

```
Result<List<Group>>.map { groups ->
	val acc = groups.map {
		Fuel.get("/groups/${it.id}")
	}
	.fold(ValidationBuilder()) { vb, result ->
		result.fold ({ detail ->
			vb.add(detail)
		}, { error ->
			vb.add(error.exception)
		})

		vb
	}
        .build()
	// log errors
	acc.successes
}
```

This code uses things that don't exist, namely a `ValidationBuilder` that allows for accumulation of results, `ValidationBuilder.add` methods and `Validation.successes`. Hence this ticket.

## Alternatives I've considered
Shown above.

**Comment by kittinunf** [comment]
Actually I ran into something similar and in my use-case, we do [lift()](https://github.com/kittinunf/Result/blob/master/result/src/main/kotlin/com/github/kittinunf/result/Result.kt#L109). Then, you will be able to transform `List<Result<Foo, FuelError>>` into `Result<List<Foo>, FuelError>` however this will make the "lifted" Result failure if any single one of that is a failure.

I think we can expand the lift() to accommodate your usecase, it might be better to move this conversation over to Result repo instead. WDYT?

**Comment by asarkar** [comment]
> it might be better to move this conversation over to Result repo instead

Sounds good. Are you able to do that, or do you want me to create another ticket [here](https://github.com/kittinunf/result/)?
