### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.github.kittinunf.fuel.core.FuelManager" on path: DexPathList

### ISSUE THREAD

**Issue by triandamai** [kittinunf/fuel#813]
# Bug Report

## Description
Hi, I'm trying to implement Fuel in an android app I'm working on. 
When I start my application I get error `java.lang.ClassNotFoundException Didn't find class "com.github.kittinunf.fuel.core.FuelManager" on path: DexPathList`

## Screenshots
![image](https://user-images.githubusercontent.com/41132846/126489005-486cf632-1868-454a-bc45-9f2eb6d6ad3c.png)

 - OS: Windows 10
 - IDE: Android Studio
 - Fuel version: 2.3.1
 - Kotlin version: 2.3.1

### Smartphone or Emulator
_Complete the following information if applicable_

 - Device: Samsung A51
 - OS: Android 11

**Comment by SleeplessByte** [comment]
DO you have a minimal reproducible example?
