### ISSUE TITLE
Multibyte character sets are garbled in Body.asString under certain conditions

### ISSUE THREAD

**Issue by aytdm** [kittinunf/fuel#815]
# Bug Report

## Description

Calling the [Body.asString](https://github.com/kittinunf/fuel/blob/823df71af8d9d70ed477d5d22eb0548045b95fad/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Body.kt#L73) method without setting `charset=utf-8` in the Content-Type header value, the multibyte character sets of response will be garbled.

## To Reproduce

https://github.com/aytdm/fuel-reproduction

```Kotlin
val (_, response, result) = Fuel.get("https://fuel-reproduction-1n8ja4ht.netlify.app/.netlify/functions/greet").responseString()

when (result) {
  is Result.Failure -> {
    val ex = result.getException()
    println(ex)
  }
  is Result.Success -> {
    println("Body.asString(\"application/json\"): ${response.body().asString("application/json")}")
    println("Body.asString(\"application/json;charset=UTF-8\"): ${response.body().asString("application/json;charset=UTF-8")}")
  }
}
```

```bash
# Result
Body.asString("application/json"): [{"id":1,"lang":"en","greeting":"Hello"},{"id":2,"lang":"ja","greeting":"???????????????"}]

# Expected
Body.asString("application/json;charset=UTF-8"): [{"id":1,"lang":"en","greeting":"Hello"},{"id":2,"lang":"ja","greeting":"こんにちは"}]
```

## Expected behavior

The multibyte character sets should not be garbled.

### Development Machine

 - OS: Windows 10
 - IDE: IntelliJ IDEA
 - Fuel version: 2.3.1
 - Kotlin version: 1.5.21
 - JDK: Amazon Corretto 11

## Additional context

I'm using Spring Boot constants ([`APPLICATION_JSON_VALUE`](https://docs.spring.io/spring-framework/docs/5.3.9/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON)) to set the Content-Type header value.
The `APPLICATION_JSON_VALUE` value does not contain charset and [`APPLICATION_JSON_UTF8_VALUE`](https://docs.spring.io/spring-framework/docs/5.3.9/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON_UTF8_VALUE) that contain charset has been deprecated since 5.2.
Therefore, this could happen in applications that handle multibyte character sets with SpringBoot.

**Comment by SleeplessByte** [comment]
Not a bug.
