### ISSUE TITLE
Unresolved Reference: Github

### ISSUE THREAD

**Issue by Code-B1** [kittinunf/fuel#823]
Hi,

I'm new to Kotlin so apologies if I am missing something simple here.

I am trying to implement Fuel into my project, I have added the below dependencies to my Gradle:

```
implementation 'com.github.kittinunf.fuel:fuel:<latest-version>'
implementation 'com.github.kittinunf.fuel:<package>:<latest-version>'
```

Which appeared to sync fine, however, when I try to import Fuel into an activity, as below:

`import com.github.kittinunf.fuel.httpGet
import com.github.kittinunf.result.Result`

I get github showing in red, and the error is as below:

`Unresolved reference: github`

I've had no issues importing other libraries into my project so wondering what I may be missing here in the steps to get this working ?

**Comment by MariusThatsMe** [comment]
How'd you fix it?

**Comment by Code-B1** [comment]
Unfortunately, I cannot remember, which makes me think I possibly had done something silly.

Looking at the code sample I entered above, maybe I hadn't replaced `<package>` and `<latest-version>` with the respective package name and version numbers and maybe that had caused my issues, I hope this may be of some help.
