### ISSUE TITLE
Fuel download large file fails

### ISSUE THREAD

**Issue by jafar-aml** [kittinunf/fuel#824]
When I wanna download big file (200MB) I got OOM error
Is there a solution? (I can set buffer in httpUrl android custom downloader, but here I don't know how to do it properly)
Any idea?

**Comment by SleeplessByte** [comment]
You don't want to set a unsized buffer, because that's exactly what runs out of memory. If you hit this, it means that it's not piping "directly" to disk. 

When I still worked on this lib, we did test large downloads, and they worked. Either it has broken since, or it's a specific option that is being used incorrectly. Want to share an Minimally Reproducible Example?

**Comment by jafar-aml** [comment]
Fuel.download(url)
                .fileDestination { _, _ ->
                    File(path, fileName)
                }
                .progress { readBytes, totalBytes ->

                    activity.runOnUiThread {

                        binding.tvBookSizeInMegabyte.text =
                                context.getString(R.string.byte_to_mega_byte ,
                                                  utils.bytesToMBFormatWithoutLetters(readBytes) ,
                                                  utils.bytesToMBFormatWithoutLetters(totalBytes)
                                )
                    }
                }
                .timeout(8000)
                .response { request, response, result ->

                    result.fold(

                            success = {

                                when (type) {
                                    Constants.DownloadType.AR -> {
                                        downloadARCompleted(fileName)
                                    }
                                    Constants.DownloadType.Ebook -> {
                                        handleDownloadStatus(BookDownloadStatus.Downloaded)
                                    }
                                }

                            },
                            failure = {

                                handleDownloadStatus(BookDownloadStatus.DownloadFailed)

                                when (type) {

                                    Constants.DownloadType.AR -> File(utils.purchasePath(context) + fileName).delete()
                                    Constants.DownloadType.Ebook -> File(utils.EBookPath(context) + fileName).delete()

                                }

                                if (!it.causedByInterruption) {

                                
                                    if (response.statusCode == 404 && response.responseMessage == "Not Found") {

                                        CustomToast().showToast(
                                                context,
                                                activity,
                                                dialogContainer,
                                                context.getString(R.string.nothing_to_download),
                                                Toast.LENGTH_SHORT,
                                                Gravity.BOTTOM
                                        )
                                    }
                                }

                            }
                    )
                }

        }catch (e : Exception){
            handleException(e)
        }

******************************************************************************************

This is the code snippet for downloading files, I get this error (I think it depends on android device ram in my test case it has 3GB memory)

******************************************************************************************

I put error log here:

Failed to allocate a 134217744 byte allocation with 25165824 free bytes and 108MB until OOM, target footprint 112943576, growth limit 201326592
    	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
    	com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
    	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 134217744 byte allocation with 25165824 free bytes and 108MB until OOM, target footprint 112943576, growth limit 201326592
    	java.util.Arrays.copyOf(Arrays.java:3161)
    	java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    	java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    	java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    	kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:108)
    	kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
    	com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:87)
    	com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:50)
    	com.github.kittinunf.fuel.core.Response.getData(Response.kt:32)

**Comment by jafar-aml** [comment]
Here is the code that I can download large files without any issue but actually I don't wanna reinvent the wheel.
**************************************

openConnection = URL(httpsedUrl).openConnection() as HttpURLConnection

                openConnection?.connectTimeout = 20_000 // in milliseconds

                openConnection
                    ?.inputStream
                    ?.buffered(8192).use { input ->
                        FileOutputStream(File(filePath)).use { output ->
                            input?.copyTo(output)
                        }
                    }

**************************************

I just added " buffered(8192) " and now I can download files.
I went through the fuel documentation and I realized there is a function in "Download response to output" section called request.streamDestination() but I have no idea how to implement it or it works in situations like this?

**Comment by SleeplessByte** [comment]
Maybe this?

```kotlin
val outputStream = FileOutputStream(File(filePath))

Fuel.download("https://httpbin.org/bytes/32768")
    .streamDestination { response, _ -> Pair(outputStream, { response.body().toStream() }) }
    .progress { readBytes, totalBytes ->
        val progress = readBytes.toFloat() / totalBytes.toFloat() * 100
        println("Bytes downloaded $readBytes / $totalBytes ($progress %)")
    }
    .response { result -> }
```

**Comment by jafar-aml** [comment]
Wow!! it's working now!
Thank you for your assistance with this matter.
I just added this:

.fileDestination{response, request ->
                File(filePath)
            }
            
without this code snippet we get " Bytes error The input has already been written to an output stream and can not be consumed again.) " error.
****************************************************************************************
I just put working code here:

        val outputStream = FileOutputStream(File(filePath))

        _downloadStatus.postValue(FileDownloadStatus.Downloading)

        Fuel.download(httpsedUrl)
            .streamDestination { response, _ -> Pair(outputStream, { response.body().toStream() }) }
            .fileDestination{response, request ->
                File(filePath)
            }
            .progress { readBytes, totalBytes ->
                val progress = readBytes.toFloat() / totalBytes.toFloat() * 100
                println("Bytes downloaded $readBytes / $totalBytes ($progress %)")
            }
            .response { result ->

                result.fold(
                        success = {
                            _downloadStatus.postValue(FileDownloadStatus.Downloaded)
                        },
                        failure = {
                            _downloadStatus.postValue( FileDownloadStatus.Failed(it) )
                        }
                )
            }

**Comment by SleeplessByte** [comment]
Great. We would love it if you could add a condensed / smaller / minimal snippet to the docs.

**Comment by jafar-aml** [comment]
Sir actually after two days of testing the above code I realized we get still OOM  error (in larger files (>300MB)), then I tried your first suggestion ( .streamDestination { response, _ -> Pair(outputStream, { response.body().toStream() }) } ) as I said  by using this code snippet we get "  The input has already been written to an output stream and can not be consumed again. " error. Then I searched for this error and base on this [article](https://www.baeldung.com/java-stream-operated-upon-or-closed-exception) " Whenever a terminal operation is called on a Stream object, the instance gets consumed and closed. " here is the answer why we get  that error.

**********************************************************

The solution I found is :

**********************************************************

    val outputStream = FileOutputStream(File(filePath))

    _downloadStatus.postValue(FileDownloadStatus.Downloading)

    Fuel.download(httpsedUrl)
        .streamDestination { response, request -> Pair(outputStream, { request.body.toStream() }) }
        .progress { readBytes, totalBytes ->
            val progress = readBytes.toFloat() / totalBytes.toFloat() * 100
            println("Bytes downloaded $readBytes / $totalBytes ($progress %)")
        }
        .response { result ->

            result.fold(
                    success = {
                        _downloadStatus.postValue(FileDownloadStatus.Downloaded)
                    },
                    failure = {
                        _downloadStatus.postValue( FileDownloadStatus.Failed(it) )
                    }
            )
        }

Actually we are using **request body stream**, and now all old errors are gone away!

**Comment by SleeplessByte** [comment]
Ah sorry. Yes, that's correct. That's what I should have written the first time around :)

**Comment by jafar-aml** [comment]
> Ah sorry. Yes, that's correct. That's what I should have written the first time around :)

Thank you for your assistance with this matter.

**Comment by jafar-aml** [comment]
> Great. We would love it if you could add a condensed / smaller / minimal snippet to the docs.

Let me know how to do it!

**Comment by SleeplessByte** [comment]
You'll want to edit this section: https://github.com/kittinunf/fuel/blob/master/fuel/README.md#download-response-to-output-file-or-outputstream (of [this file](https://github.com/kittinunf/fuel/edit/master/fuel/README.md)).
