### ISSUE TITLE
Testing Mode Delay

### ISSUE THREAD

**Issue by Yayo-Arellano** [kittinunf/Fuel#83]
Is there any way to add a delay in the request in order to test in an Android app. 
For example i make the call

`
 Request request = Fuel.delete(URL);
 request.responseString(listener);
`

and wait at least a few seconds until get the response.

**Comment by yoavst** [comment]
You can save the time of the request, and check when the response completed.

**Comment by kittinunf** [comment]
If you use RxJava [delay](http://reactivex.io/documentation/operators/delay.html), it can be use to achieve what you expect too.

**Comment by yoavst** [comment]
I'm marking it closed, since it doesn't belong directly to Fuel.
