### ISSUE TITLE
Virus Trojan.AndroidOS.Facestealer

### ISSUE THREAD

**Issue by sevenCL** [kittinunf/fuel#831]
This library has had viruses since 2.0.0

![微信截图_20220406201107](https://user-images.githubusercontent.com/24243783/161972072-4dd6d0be-405f-49a1-9c3e-fbfccaf9f7a7.png)
![微信截图_20220406200730](https://user-images.githubusercontent.com/24243783/161972090-f4307d6f-530f-449b-b11d-ace4c120bc4a.png)

**Comment by kittinunf** [comment]
I am reluctant to understand where this is coming from. Care to elaborate and also reveal the credibility of the tool you are using to detect?

**Comment by kittinunf** [comment]
No action from the reporter. Closing this.
