### ISSUE TITLE
How to send JSON Array in POST request body

### ISSUE THREAD

**Issue by ArushiJindal** [kittinunf/fuel#834]

**Comment by ArushiJindal** [comment]
val (_, _, result) = urlStr.httpPost()
            .header(mapOf("Ocp-Apim-Subscription-Key" to ""))
            .header(mapOf("Content-Type" to ""))
            .jsonBody(jsonObject.toString())
            .responseString()

jsonObject contains [{"text":"Bonjour"}]

Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

**Comment by ArushiJindal** [comment]
my bad all good. it works

**Comment by kittinunf** [comment]
Alrighty ^^
