### ISSUE TITLE
Check file

### ISSUE THREAD

**Issue by crysan** [kittinunf/Fuel#84]
Hi!
As you can quickly check the availability of a file on the server?
Very slow:

                            Fuel.get("http://samlib.ru/k/kerr_r/strashnyjson.fb2.zip").timeout(Constants.USER_TIMEOUT_FAST).responseString(new Handler<String>() {
                                @Override
                                public void failure(Request request, Response response, FuelError error) {
                                    //do something when it is failure
                                    func.showLog("failure");
                                    func.showLog_int(response.getHttpStatusCode());
                                }

                                @Override
                                public void success(Request request, Response response, String data) {
                                    //do something when it is successful
                                    func.showLog("success");
                                    func.showLog_int(response.getHttpStatusCode());
                                }
                            });

**Comment by yoavst** [comment]
How would you do that yourself? Would you check only the status code and abort the connection?

**Comment by crysan** [comment]
Would you check only the status code and abort the connection? **YES!**
 Is there a reason for the lack of HEAD request? **Example pls.**

**Comment by kittinunf** [comment]
There is no reason not having `HEAD`. It is the thing that `Fuel` has not yet supported. I agree that we should do it.

**Comment by crysan** [comment]
Well do it!
I ask you to.

**Comment by crysan** [comment]
B one more question
Is it possible to implement in the library and check enable html pages?

**Comment by yoavst** [comment]
I didn't understand your question @crysan
