### ISSUE TITLE
Publish to maven central instead of JitPack

### ISSUE THREAD

**Issue by knyttl** [kittinunf/fuel#847]
Hi,

as JitPack.io has been down for more than 24 hours, it would be a good idea to publish Fuel to maven central or similar stable repository 🙏

**Comment by kittinunf** [comment]
Yeah I will work on this!

**Comment by kittinunf** [comment]
We did https://github.com/kittinunf/fuel/releases/tag/3.0.0-alpha01

**Comment by knyttl** [comment]
Hm I still don't see it in Maven central: https://mvnrepository.com/artifact/com.github.kittinunf.fuel

Is that really deployed there?

**Comment by iNoles** [comment]
it is in OSS Sonatypes.

**Comment by knyttl** [comment]
> it is in OSS Sonatypes.

It seems the comment disappeared? Also I still don't see it anywhere. Ideally it would be great to see it in `mvnrepository` like other artifacts.

**Comment by kittinunf** [comment]
Hmm, I think it should be here https://mvnrepository.com/artifact/com.github.kittinunf.fuel/fuel/3.0.0-alpha1

Together with -jvm and others artifacts for Kmm

Could you please try again and see whether that works?

**Comment by knyttl** [comment]
I finally see it there! Thanks!
