### ISSUE TITLE
Accept `java.net.URL` as PathStringConvertible

### ISSUE THREAD

**Issue by marcomorain** [kittinunf/Fuel#85]
In my code I'm using `java.net.URL` to store URLs, but I need to convert them into string to pass them in to Fuel.

```Kotlin
    val authUrl = URL(BASE, "/cloverapi/app")
    Fuel.post(authUrl)
```

```
Error:(147, 14) None of the following functions can be called with the arguments supplied:
@kotlin.jvm.JvmStatic @kotlin.jvm.JvmOverloads public final fun post(convertible: com.github.kittinunf.fuel.Fuel.PathStringConvertible, parameters: kotlin.collections.List<kotlin.Pair<kotlin.String, kotlin.Any?>>? = ...): com.github.kittinunf.fuel.core.Request defined in com.github.kittinunf.fuel.Fuel.Companion
@kotlin.jvm.JvmStatic @kotlin.jvm.JvmOverloads public final fun post(path: kotlin.String, parameters: kotlin.collections.List<kotlin.Pair<kotlin.String, kotlin.Any?>>? = ...): com.github.kittinunf.fuel.core.Request defined in com.github.kittinunf.fuel.Fuel.Companion
```

It would be great if I could pass a URL to the post function without having to convert to string.

I'm using URLs to give me extra integrity checks versus using strings.

**Comment by yoavst** [comment]
First, `Fuel` comes with support for base URL:
```kotlin
FuelManager.instance.basePath = BASE

Fuel.post("/cloverapi/app")
```
So it can be useful for the case you've mentioned. 

Second, If we will support `java.net.URL`, we will probably need to support also `java.net.URI`. But why stop here? an `android.net.Uri` support for the android module.

I do think you are right, but we can't just add methods to Fuel for every object that can store URL, that is why we have `PathStringConvertible`. However, Kotlin doesn't support  implicit conversion, so it doesn't help.

**Workaround:**
```kotlin
fun post(url: URL, parameters: List<Pair<String, Any?>>? = null): Request {
     return Fuel.post(url.toString(), parameters)
}
```

**Comment by marcomorain** [comment]
👍 that makes sense, thanks.
