### ISSUE TITLE
Fuel download and upload missing on 3.0 [Question]

### ISSUE THREAD

**Issue by nksaroj** [kittinunf/fuel#862]
Hi I am uplifting our code to 3.0. 

Noticed Fuel.download and Fuel.upload are missing and couldn't find any code related to it. 

Any guidance on it is appreciated.  @iNoles @kittinunf

**Comment by iNoles** [comment]
I think I have not implemented a file upload method yet. I am open to a PR for that one.

As for download, I don't recommend it for right now because you get a string for it.

**Comment by nksaroj** [comment]
Thanks @iNoles will wait for the featue.
