### ISSUE TITLE
Identify the test coverages area 

### ISSUE THREAD

**Issue by iNoles** [kittinunf/fuel#869]
![image](https://github.com/kittinunf/fuel/assets/49764/d0198a68-b616-4de3-b09b-08f2fc618c13)

This was taken from the Kover 0.7.0 coverages HTML pages.

**Comment by pouyan021** [comment]
Care to elaborate a little about this?

**Comment by iNoles** [comment]
As for Fuel, setHttpLoader and setHttpLoader
As for FuelsKt, any methods other than get. However, the request method is 1/2 for headers
As for HttpUrlFetcher, the fetch methods are 1/2 on the request.parameters
As for fillURLWithParameters, there is 1/2 in contains("?") and 0/2 in parameters.isNotEmpty
As for StringsKt, the entire class is under red

So far

**Comment by iNoles** [comment]
the only test coverage left for two Fuel methods, FuelKt, and StringsKt.
