### ISSUE TITLE
Basic auth with fuel 3

### ISSUE THREAD

**Issue by acaliaro** [kittinunf/fuel#878]
Hi.
I need a GET with Fuel 3 and basic auth, but I can't find how to use it.
Seems that "authentication" is not present.
Can I have a sample?
Thanks

**Comment by enricolo4** [comment]
you can do some like this

```kotlin
val okHttpClient = OkHttpClient().newBuilder()
    .readTimeout(TIMEOUT, TimeUnit.SECONDS)
    .addInterceptor(LoggingInterceptor())
    .addInterceptor {
        val credentials = Credentials.basic(username, pasword)
        val request = it.request().newBuilder()
            .addHeader("Content-Type", "application/json")
            .addHeader("Authorization", credentials)
            .build()

        it.proceed(request)
    }.build()

val fuelClient = Fuel.apply {
    setHttpLoader(
        factory = {
            HttpLoader(okHttpClient)
        }
    )
}

val response: String = fuelClient.post(url = "https://xpto.com", body="someBody").body
```

**Comment by acaliaro** [comment]
> you can do some like this
> 
> ```kotlin
> val okHttpClient = OkHttpClient().newBuilder()
>     .readTimeout(TIMEOUT, TimeUnit.SECONDS)
>     .addInterceptor {
>         val credentials = Credentials.basic(username, pasword)
>         val request = it.request().newBuilder()
>             .addHeader("Content-Type", "application/json")
>             .addHeader("Authorization", credentials)
>             .build()
> 
>         it.proceed(request)
>     }.build()
> 
> val fuelClient = Fuel.apply {
>     setHttpLoader(
>         factory = {
>             HttpLoader(okHttpClient)
>         }
>     )
> }
> 
> val response: String = fuelClient.post(url = "https://xpto.com", body="someBody").body
> ```

Thanks @enricolo4 , I will take a look
