### ISSUE TITLE
Make fuel usable by common code again

### ISSUE THREAD

**Issue by dalewking** [kittinunf/fuel#927]
#863 Basically made Fuel unusable from common code.

i just use Fuel to get the content of urls from common code. #863 basically makes that impossible. The view of HttpResponse in common code is now just an empty class. It only has properties in platform specific code.

You need to expose `statusCode` and `body` properties in common code.

**Comment by iNoles** [comment]
@dalewking I believe that Alpha 04 fixed this issue.

**Comment by dalewking** [comment]
Looks like it is fixed, but I have not been able to fully test it due to the switch to Source.
