### ISSUE TITLE
Unable to download Fuel v2.3.1 from Jitpack

### ISSUE THREAD

**Issue by Ananthakr-Jupiter** [kittinunf/fuel#939]
We are facing this issue mainly in our CI tool github actions and Codemagic for a React Native app.
<img width="1318" alt="Screenshot 2024-08-14 at 11 12 26 PM" src="https://github.com/user-attachments/assets/d6c736f5-3b38-49d6-b3ef-0351ac1f1932">

When we try to access the url that it search at https://jitpack.io/com/github/kittinunf/fuel/fuel/2.3.1/fuel-2.3.1.jar
the response says `Artifact available on Maven Central`. Not sure what this means.

Can anyone help understand what is the issue here?

**Comment by kittinunf** [comment]
Hey there, Jcenter is end-of-life and I don't think there is anything we can do about it. Please point your dependencies repository to mavenCentral instead 

https://repo1.maven.org/maven2/com/github/kittinunf/fuel/fuel/2.3.1
