### ISSUE TITLE
Allow setting timeout on FuelManager

### ISSUE THREAD

**Issue by ismail-s** [kittinunf/Fuel#94]
Atm, the timeouts are hardcoded [here](https://github.com/kittinunf/Fuel/blob/c6e3b748a706dbee3cb37813676e3f7cdc1518f8/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt#L29). It would be nice to be able to modify the timeout for all requests on the `FuelManager.instance` object, rather than having to manually configure the timeout for each request.

**Comment by yoavst** [comment]
```
Fuel.testMode {
    timeout = 15000
    timeoutRead = 60000
}

**Comment by ismail-s** [comment]
@yoavst I could do that. But it just seems a bit weird to be using a test mode when I am not actually running tests.

**Comment by kittinunf** [comment]
@ismail-s I kinda of agree that using `testMode` seems like a workaround. However, I don't have a need to configure this value, but I do understand why this is handy. 

If you convince that this feature is useful, I am happy to accept PR.

**Comment by gahfy** [comment]
I just did a pull request to solve this issue
