### ISSUE TITLE
fuel, fuel-jackson 1.15.0 upload plz...

### ISSUE THREAD

**Issue by dijer119** [kittinunf/fuel#943]
Hello.
I'm using fuel, fuel-jackson 1.15.0
jcenter is closed and compilation build is not possible.
I'd appreciate it if you could post it on mavenCentral.

**Comment by rafaeuw** [comment]
same!! please upload 1.15.0!!

![IM CRYING!!](https://media1.tenor.com/m/uAsn3ULvQe8AAAAd/sad.gif)

**Comment by petergorcak** [comment]
Same here :/

**Comment by friedScotch** [comment]
I thought of forking the plugin that caused the compilation error, however on further inspection I found out that there are multiple layers of nested dependencies that It seems like the best approach is to have them (in my case fuel:1.15.0 and fuel-android:1.15.0)  reuploaded. 

If you need any help with uploading, please let me know!

**Comment by kittinunf** [comment]
Hi there obviously, v1.15.0 is pretty old and I don't think we would do anything about it again. Either consider using v2.x or a recent v3 which is currently in support.
