### ISSUE TITLE
Hangs on at exit

### ISSUE THREAD

**Issue by alex920** [kittinunf/Fuel#99]
Hangs on at exit when using async mode,

``` Kotlin
Fuel.get("http://www.google.com/").responseString { request, response, result ->
        println(result.getAs<String>())
    }

FuelManager.instance.executor.shutdown() // this line fixes problem
```

**Comment by kittinunf** [comment]
I am not sure I understand your problem. Are you using this on Android?

**Comment by alex920** [comment]
On desktop. Executor prevents jvm from stopping if not shutdown it (executor) explicity,

**Comment by kittinunf** [comment]
Ok. If you happen to know how to fix it please let me know. Even better you could do PR which I am happy to accept it.

**Comment by kittinunf** [comment]
Close as it stales.
